---
output:
  html_document:
    theme: cerulean
    highlight: monochrome 
    self_contained: yes
---

```{r chunk_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      cache = FALSE, 
                      cache.path = "/caches/", 
                      comment = "",
                      collapse = TRUE,  
                      fig.show = "hold",
                      fig.asp = 7/9, 
                      out.width = "75%", 
                      fig.align = "center")
```

\
\
\

### Predicción con Datos Temporales (36519). Grado en Inteligencia y Analítica de Negocios (GBIA)

-------------------

\


Hola a tod&#64;s y bienvenid&#64;s a la página web del curso. 

\

Esta es la página web de la edición 2020-21 del curso de Predicción con Datos Temporales (GBIA) de la Universitat de València. El repositorio para crear esta web lo tenéis [aquí](https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/){target="_blank"} en Github.

**Resumen del curso:** la idea principal es aprender a manejarse con datos con estructura temporal (en contraposición a datos de corte transversal (que has visto en el primer semestre con Paco Goerlich) o espacial. Veremos cómo describir una serie temporal, como ajustarla a un modelo, cómo hacer predicciones y, lo que es más importante, a valorar la calidad de las predicciones desde un enfoque de *Machine Learning*.

Para más información de este módulo, por favor visita la sección [Guía del curso](https://iarribasf.github.io/PrediccionSeriesTemporales-GBIA/01-Guia-curso.html) de esta página web o descárgate la **Guía Docente** desde la web de la Universitat de València.

\


-- Iván Arribas


\
\
\
\

  