<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Técnicas de Alisado Exponencial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Inicio</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html">Guía del curso</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html">Logística</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">Diapos</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: Media móvil</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html">
 <span class="dropdown-text">Tema 6: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html">
 <span class="dropdown-text">Tema 7: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-12-Ejemplo6.html">
 <span class="dropdown-text">Ejemplo Tema 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo7.html">
 <span class="dropdown-text">Ejemplo Tema 7</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">Píldoras</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Pasajeros.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html">Recursos de la asignatura</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html">Evaluacion Continua</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">Más</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="toc-section-number">1</span>  Introducción</a></li>
  <li><a href="#componentes-de-una-serie-en-el-contexto-del-alisado-exponencial" id="toc-componentes-de-una-serie-en-el-contexto-del-alisado-exponencial" class="nav-link" data-scroll-target="#componentes-de-una-serie-en-el-contexto-del-alisado-exponencial"><span class="toc-section-number">2</span>  Componentes de una serie en el contexto del alisado exponencial</a></li>
  <li><a href="#casos-posibles" id="toc-casos-posibles" class="nav-link" data-scroll-target="#casos-posibles"><span class="toc-section-number">3</span>  Casos posibles</a>
  <ul class="collapse">
  <li><a href="#las-funciones-ets-y-forecast" id="toc-las-funciones-ets-y-forecast" class="nav-link" data-scroll-target="#las-funciones-ets-y-forecast"><span class="toc-section-number">3.1</span>  Las funciones <code>ets</code> y <code>forecast</code></a></li>
  </ul></li>
  <li><a href="#alisado-exponencial-simple-a-n-n" id="toc-alisado-exponencial-simple-a-n-n" class="nav-link" data-scroll-target="#alisado-exponencial-simple-a-n-n"><span class="toc-section-number">4</span>  Alisado exponencial simple (A, N, N)</a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición"><span class="toc-section-number">4.1</span>  Definición</a></li>
  <li><a href="#formulas-interactivas-de-sus-componentes" id="toc-formulas-interactivas-de-sus-componentes" class="nav-link" data-scroll-target="#formulas-interactivas-de-sus-componentes"><span class="toc-section-number">4.2</span>  Formulas interactivas de sus componentes</a></li>
  <li><a href="#estimación-de-los-parámetros-del-modelo" id="toc-estimación-de-los-parámetros-del-modelo" class="nav-link" data-scroll-target="#estimación-de-los-parámetros-del-modelo"><span class="toc-section-number">4.3</span>  Estimación de los parámetros del modelo</a></li>
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo"><span class="toc-section-number">4.4</span>  Ejemplo</a></li>
  </ul></li>
  <li><a href="#alisado-exponencial-de-holt-a-a-n" id="toc-alisado-exponencial-de-holt-a-a-n" class="nav-link" data-scroll-target="#alisado-exponencial-de-holt-a-a-n"><span class="toc-section-number">5</span>  Alisado exponencial de Holt (A, A, N)</a>
  <ul class="collapse">
  <li><a href="#formulas-interactivas-de-sus-componentes-1" id="toc-formulas-interactivas-de-sus-componentes-1" class="nav-link" data-scroll-target="#formulas-interactivas-de-sus-componentes-1"><span class="toc-section-number">5.1</span>  Formulas interactivas de sus componentes</a></li>
  <li><a href="#estimación-de-los-parámetros-del-modelo-1" id="toc-estimación-de-los-parámetros-del-modelo-1" class="nav-link" data-scroll-target="#estimación-de-los-parámetros-del-modelo-1"><span class="toc-section-number">5.2</span>  Estimación de los parámetros del modelo</a></li>
  <li><a href="#ejemplo-1" id="toc-ejemplo-1" class="nav-link" data-scroll-target="#ejemplo-1"><span class="toc-section-number">5.3</span>  Ejemplo</a></li>
  </ul></li>
  <li><a href="#alisado-exponencial-con-pendiente-amortiguada-a-ad-n" id="toc-alisado-exponencial-con-pendiente-amortiguada-a-ad-n" class="nav-link" data-scroll-target="#alisado-exponencial-con-pendiente-amortiguada-a-ad-n"><span class="toc-section-number">6</span>  Alisado exponencial con pendiente amortiguada (A, Ad, N)</a>
  <ul class="collapse">
  <li><a href="#formulas-interactivas-de-sus-componentes-2" id="toc-formulas-interactivas-de-sus-componentes-2" class="nav-link" data-scroll-target="#formulas-interactivas-de-sus-componentes-2"><span class="toc-section-number">6.1</span>  Formulas interactivas de sus componentes</a></li>
  <li><a href="#ejemplo-2" id="toc-ejemplo-2" class="nav-link" data-scroll-target="#ejemplo-2"><span class="toc-section-number">6.2</span>  Ejemplo</a></li>
  </ul></li>
  <li><a href="#alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" id="toc-alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" class="nav-link" data-scroll-target="#alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m"><span class="toc-section-number">7</span>  Alisado de Holt-Winters aditivo (A, A, A) y multiplicativo (M, A, M)</a>
  <ul class="collapse">
  <li><a href="#alisado-de-holt-winters-aditivo-a-a-a" id="toc-alisado-de-holt-winters-aditivo-a-a-a" class="nav-link" data-scroll-target="#alisado-de-holt-winters-aditivo-a-a-a"><span class="toc-section-number">7.1</span>  Alisado de Holt-Winters aditivo (A, A, A)</a></li>
  <li><a href="#alisado-de-holt-winters-multiplicativo-m-a-m" id="toc-alisado-de-holt-winters-multiplicativo-m-a-m" class="nav-link" data-scroll-target="#alisado-de-holt-winters-multiplicativo-m-a-m"><span class="toc-section-number">7.2</span>  Alisado de Holt-Winters multiplicativo (M, A, M)</a></li>
  <li><a href="#ejemplo-con-demanda-electrica" id="toc-ejemplo-con-demanda-electrica" class="nav-link" data-scroll-target="#ejemplo-con-demanda-electrica"><span class="toc-section-number">7.3</span>  Ejemplo con Demanda electrica</a></li>
  <li><a href="#ejemplo-con-nacimientos" id="toc-ejemplo-con-nacimientos" class="nav-link" data-scroll-target="#ejemplo-con-nacimientos"><span class="toc-section-number">7.4</span>  Ejemplo con Nacimientos</a></li>
  </ul></li>
  <li><a href="#ejemplo-con-transformación-logarítmica" id="toc-ejemplo-con-transformación-logarítmica" class="nav-link" data-scroll-target="#ejemplo-con-transformación-logarítmica"><span class="toc-section-number">8</span>  Ejemplo con transformación logarítmica</a></li>
  <li><a href="#casos-generales-de-alisado-exponencial-la-función-ets-de-nuevo" id="toc-casos-generales-de-alisado-exponencial-la-función-ets-de-nuevo" class="nav-link" data-scroll-target="#casos-generales-de-alisado-exponencial-la-función-ets-de-nuevo"><span class="toc-section-number">9</span>  Casos generales de alisado exponencial: la función <code>ets</code> (de nuevo)</a>
  <ul class="collapse">
  <li><a href="#criterios-de-optimización" id="toc-criterios-de-optimización" class="nav-link" data-scroll-target="#criterios-de-optimización"><span class="toc-section-number">9.1</span>  Criterios de optimización</a></li>
  <li><a href="#criterios-de-selección-de-modelos" id="toc-criterios-de-selección-de-modelos" class="nav-link" data-scroll-target="#criterios-de-selección-de-modelos"><span class="toc-section-number">9.2</span>  Criterios de selección de modelos</a></li>
  </ul></li>
  <li><a href="#residuo-de-un-modelo" id="toc-residuo-de-un-modelo" class="nav-link" data-scroll-target="#residuo-de-un-modelo"><span class="toc-section-number">10</span>  Residuo de un modelo</a></li>
  <li><a href="#ejemplos-de-aplicación" id="toc-ejemplos-de-aplicación" class="nav-link" data-scroll-target="#ejemplos-de-aplicación"><span class="toc-section-number">11</span>  Ejemplos de aplicación</a>
  <ul class="collapse">
  <li><a href="#libros" id="toc-libros" class="nav-link" data-scroll-target="#libros"><span class="toc-section-number">11.1</span>  Libros</a>
  <ul class="collapse">
  <li><a href="#identificación-y-estimación-del-mejor-modelo" id="toc-identificación-y-estimación-del-mejor-modelo" class="nav-link" data-scroll-target="#identificación-y-estimación-del-mejor-modelo">Identificación y estimación del mejor modelo</a></li>
  <li><a href="#predicción" id="toc-predicción" class="nav-link" data-scroll-target="#predicción">Predicción</a></li>
  <li><a href="#análisis-del-residuo" id="toc-análisis-del-residuo" class="nav-link" data-scroll-target="#análisis-del-residuo">Análisis del residuo</a></li>
  <li><a href="#validación-error-extra-muestral-a-varios-periodos-vista" id="toc-validación-error-extra-muestral-a-varios-periodos-vista" class="nav-link" data-scroll-target="#validación-error-extra-muestral-a-varios-periodos-vista">Validación: error extra-muestral a varios periodos vista</a></li>
  </ul></li>
  <li><a href="#nacimientos" id="toc-nacimientos" class="nav-link" data-scroll-target="#nacimientos"><span class="toc-section-number">11.2</span>  Nacimientos</a>
  <ul class="collapse">
  <li><a href="#identificación-y-estimación-del-mejor-modelo-1" id="toc-identificación-y-estimación-del-mejor-modelo-1" class="nav-link" data-scroll-target="#identificación-y-estimación-del-mejor-modelo-1">Identificación y estimación del mejor modelo</a></li>
  <li><a href="#predicción-1" id="toc-predicción-1" class="nav-link" data-scroll-target="#predicción-1">Predicción</a></li>
  <li><a href="#análisis-del-error" id="toc-análisis-del-error" class="nav-link" data-scroll-target="#análisis-del-error">Análisis del error</a></li>
  <li><a href="#validación-error-extra-muestral-según-horizonte-temporal" id="toc-validación-error-extra-muestral-según-horizonte-temporal" class="nav-link" data-scroll-target="#validación-error-extra-muestral-según-horizonte-temporal">Validación: error extra-muestral según horizonte temporal</a></li>
  </ul></li>
  <li><a href="#demanda-eléctrica" id="toc-demanda-eléctrica" class="nav-link" data-scroll-target="#demanda-eléctrica"><span class="toc-section-number">11.3</span>  Demanda eléctrica</a>
  <ul class="collapse">
  <li><a href="#identificación-y-estimación-del-mejor-modelo-2" id="toc-identificación-y-estimación-del-mejor-modelo-2" class="nav-link" data-scroll-target="#identificación-y-estimación-del-mejor-modelo-2">Identificación y estimación del mejor modelo</a></li>
  <li><a href="#predicción-2" id="toc-predicción-2" class="nav-link" data-scroll-target="#predicción-2">Predicción</a></li>
  <li><a href="#análisis-del-error-1" id="toc-análisis-del-error-1" class="nav-link" data-scroll-target="#análisis-del-error-1">Análisis del error</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#otras-alternativas-para-ajustar-un-modelo-y-predecir" id="toc-otras-alternativas-para-ajustar-un-modelo-y-predecir" class="nav-link" data-scroll-target="#otras-alternativas-para-ajustar-un-modelo-y-predecir"><span class="toc-section-number">12</span>  Otras alternativas para ajustar un modelo y predecir</a></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"><span class="toc-section-number">13</span>  Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Técnicas de Alisado Exponencial</h1>
<p class="subtitle lead">Previsión con Datos Temporales (GBIA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">

</div>
<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Los métodos de alisado exponencial aparecen en los años 50 del siglo pasado de la mano de Brown, Holt y Winters <span class="citation" data-cites="Brown59 Holt Winters60">(see <a href="#ref-Brown59" role="doc-biblioref">Brown 1959</a>; <a href="#ref-Holt" role="doc-biblioref">Holt 2004</a>; <a href="#ref-Winters60" role="doc-biblioref">Winters 1960</a>)</span> y han sido la raíz de uno de los métodos de predicción más sencillos y eficaces. La idea básica es predecir usando una media ponderada de los datos pasados, donde los más recientes tienen un peso mayor y este decae exponencialmente conforme usamos observaciones más antiguas.</p>
<p>El alisado exponencial es una familia de métodos de ajuste y previsión que ofrece muy buenos resultados para predicciones a corto plazo o para predecir series con pocos datos o <em>sencillas</em> (sin mucho <em>ruido</em>).</p>
<p>Suponen un grado de modelización mayor que los métodos sencillos vistos previamente, pero sin alcanzar la complejidad de otras metodologías (modelos ARIMA).</p>
<p>En origen, son métodos descriptivos con el único objetivo de producir <strong>predicciones puntuales</strong>. Sin embargo, su enfoque como modelos de <em>espacio de estados</em> posibilita un marco teórico para obtener <strong>intervalos de confianza de las predicciones</strong>.</p>
<p><br>
<br>
</p>
</section>
<section id="componentes-de-una-serie-en-el-contexto-del-alisado-exponencial" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Componentes de una serie en el contexto del alisado exponencial</h1>
<p>Para obtener una predicción en el periodo <span class="math inline">\(t+1\)</span> con datos hasta el periodo <span class="math inline">\(t\)</span> necesitamos tres componentes:</p>
<ul>
<li>La estimación del nivel de la serie en el periodo <span class="math inline">\(t\)</span>: <span class="math inline">\(l_t\)</span></li>
<li>La estimación de la pendiente de la serie en el periodo <span class="math inline">\(t\)</span>: <span class="math inline">\(b_t\)</span></li>
<li>La estimación de la estacionalidad en el mes correspondiente al periodo <span class="math inline">\(t+1\)</span> con datos hasta <span class="math inline">\(t\)</span>: <span class="math inline">\(s_{t + 1 - m}\)</span> (recuerda, <span class="math inline">\(m\)</span> es el orden estacional</li>
</ul>
<p>A partir de estas componentes, obtenidas en el periodo <span class="math inline">\(t\)</span> y para un esquema aditivo, se tendría que la predicción en el periodo <span class="math inline">\(t+1\)</span> es: <span class="math display">\[\widehat{y}_{t+1} = l_t+b_t+s_{t+1-m}.\]</span> En general, las componentes pueden <strong>existir o no</strong> y se pueden combinar entre ellas <strong>aditiva o multiplicativamente</strong>. Veamos algunos casos:</p>
<ul>
<li>Existen todas y son multiplicativas: <span class="math display">\[\widehat{y}_{t+1}=l_t \cdot b_t \cdot s_{t + 1 - m}\]</span></li>
<li>Existen todas, nivel y pendiente aditivas, y estacionalidad multiplicativa: <span class="math display">\[\widehat{y}_{t+1}=(l_t+b_t)s_{t + 1 - m}\]</span></li>
<li>No hay pendiente y la estacionalidad es aditiva: <span class="math display">\[\widehat{y}_{t+1}=l_t+s_{t + 1 - m}\]</span></li>
</ul>
<p>¿Como obtenemos los valores de <span class="math inline">\(l_t\)</span>, <span class="math inline">\(b_t\)</span> y <span class="math inline">\(s_{t + 1 - m}\)</span>? Mediante <strong>expresiones recursivas</strong>, donde cada componente se calcula a partir de los valores hasta <span class="math inline">\(t\)</span> de la serie y de las componentes: <span class="math display">\[
\begin{aligned}
l_t&amp; = f_l(y_t,y_{t-1}\ldots, l_{t-1},l_{t-2}\ldots,b_{t-1},b_{t-2}\ldots,s_{t-1},s_{t-2}\ldots) \\
b_t&amp; = f_b(y_t,y_{t-1}\ldots, l_{t},l_{t-1}\ldots,b_{t-1},b_{t-2}\ldots,s_{t-1},s_{t-2}\ldots) \\
s_t&amp; = f_s(y_t,y_{t-1}\ldots, l_{t},l_{t-1}\ldots,b_{t},b_{t-1}\ldots,s_{t-1},s_{t-2}\ldots)
\end{aligned}
\]</span> Por ejemplo, el <em>método ingenuo I</em> se puede interpretar dentro de este contexto como un método de alisado donde <span class="math inline">\(l_t = y_t\)</span> y no hay ni pendiente ni estacionalidad. Por tanto, <span class="math inline">\(\widehat{y}_{t+1} = l_{t} = y_{t}\)</span>.</p>
<p>De la misma forma, el <em>método ingenuo II</em> se puede interpretar como un método de alisado donde <span class="math inline">\(l_t = y_t\)</span>, <span class="math inline">\(b_t = y_t - y_{t-1}\)</span> y no hay estacionalidad. Entonces, <span class="math inline">\(\widehat{y}_{t+1}=l_t + b_t = y_t + (y_t - y_{t-1})\)</span>.</p>
<p>En las expresiones previas hemos supuesto que se quería obtener una predicción a un periodo vista (<span class="math inline">\(\widehat{y}_{t+1}\)</span>). Si el objetivo es estimar una previsión <span class="math inline">\(h\)</span> periodos hacia delante desde el periodo <span class="math inline">\(t\)</span>, <span class="math inline">\(\widehat{y}_{t+h}\)</span>, hay que modificar la ecuación de predicción adecuadamente. Por ejemplo, para el caso aditivo se tendría que <span class="math display">\[\widehat{y}_{t+h} = l_t+hb_t+s_{t+h-m(k+1)}\]</span> donde <span class="math inline">\(k = \lfloor (h-1)/m\rfloor\)</span>.</p>
<p>El concepto de componentes aquí visto no coincide con el definido en el Tema 1. Sin embargo, podemos asimilar la tendencia de una serie como la suma (o multiplicación) del nivel y la pendiente <span class="math inline">\(T_{t+1} = l_t + b_t\)</span> (o <span class="math inline">\(T_{t+1} = l_t \cdot b_t\)</span>) y de esta forma ambas definiciones de componentes de una serie se hacen compatibles.</p>
<p><br>
<br>
</p>
</section>
<section id="casos-posibles" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Casos posibles</h1>
<p>Todas las series tiene nivel, pero dependiendo del tipo de pendiente y estacionalidad hay 15 casos posibles, mostrados en la <a href="#tbl-taxonomia">Tabla&nbsp;1</a>.</p>
<div id="tbl-taxonomia" class="anchored">
<table class="table">
<caption>Tabla&nbsp;1: Casos de alisado según el tipo de tendencia y estacionalidad</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tendencia</th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Estacionalidad</th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Ninguna (N)</td>
<td style="text-align: center;">Aditiva (A)</td>
<td style="text-align: center;">Multiplicativa (M)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ninguna (N)</td>
<td style="text-align: center;"><strong>N, N</strong></td>
<td style="text-align: center;">N, A</td>
<td style="text-align: center;">N, M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aditiva (A)</td>
<td style="text-align: center;"><strong>A, N</strong></td>
<td style="text-align: center;"><strong>A, A</strong></td>
<td style="text-align: center;"><strong>A, M</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Aditiva Amortiguada (Ad)</td>
<td style="text-align: center;"><strong>Ad, N</strong></td>
<td style="text-align: center;">Ad, A</td>
<td style="text-align: center;">Ad, M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Multiplicativa (M)</td>
<td style="text-align: center;">M, N</td>
<td style="text-align: center;">M, A</td>
<td style="text-align: center;">M, M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiplicativa Amortiguada (Md)</td>
<td style="text-align: center;">Md, N</td>
<td style="text-align: center;">Md, A</td>
<td style="text-align: center;">Md, M</td>
</tr>
</tbody>
</table>
</div>
<p>Cada caso difiere en las componentes que se observan y su esquema, dando lugar a un conjunto diferente de ecuaciones recursivas de actualización.</p>
<p>Si se añade que el error puede ser aditivo (A) o multiplicativo (M), da 30 posibilidades. El tipo de error (aditivo o multiplicativo) es relevante en el cálculo del intervalo de confianza de las predicciones.</p>
<p>Los modelos más usuales son (error, tendencia, estacionalidad):</p>
<ul>
<li>(A, N, N): Alisado exponencial simple</li>
<li>(A, A, N): Alisado de Holt</li>
<li>(A, Ad, N): Alisado con tendencia amortiguada (d de <em>damped</em>)</li>
<li>(A, A, A): Alisado de Holt-Winters aditivo</li>
<li>(A, A, M): Alisado de Holt-Winters multiplicativo</li>
</ul>
<p>Acude al artículo de <span class="citation" data-cites="Hyndman08">Hyndman and Khandakar (<a href="#ref-Hyndman08" role="doc-biblioref">2008</a>)</span> para saber más de cada modelo, o al libro de <span class="citation" data-cites="Hyndman08b">Hyndman et al. (<a href="#ref-Hyndman08b" role="doc-biblioref">2008</a>)</span>.</p>
<p><br>
</p>
<section id="las-funciones-ets-y-forecast" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="las-funciones-ets-y-forecast"><span class="header-section-number">3.1</span> Las funciones <code>ets</code> y <code>forecast</code></h2>
<p>Podemos estimar cualquiera de los treinta modelos usando la función <code>ets</code> del paquete <code>forecast</code>.</p>
<ul>
<li>El tipo de modelo en <code>ets</code> se especifica con el argumento <code>model</code>, un código de tres letras indicando el tipo de Error, Tendencia y eStacionalidad (ETS). Por ejemplo, <code>model = "ANN"</code> indica un modelo con error aditivo, sin tendencia ni estacionalidad, es decir, el alisado exponencial simple; <code>model = "AAN"</code> indica un modelo con error aditivo, pendiente aditiva, pero sin estacionalidad, el alisado exponencial de Holt. El alisado exponencial de Holt-Winters multiplicativo sería <code>model = "AAM"</code>.</li>
<li>Si se desea incluir amortiguamiento, hay que añadir el argumento <code>damped = TRUE</code>.</li>
<li>Por defecto <code>ets</code> no considera modelos con tendencia multiplicativa (últimas dos líneas de la <a href="#tbl-taxonomia">Tabla&nbsp;1</a>). Debes fijar el parámetro <code>allow.multiplicative.trend=TRUE</code> para contemplar esta opción.</li>
</ul>
<p>A diferencia de las funciones vistas en el Tema 3 (<code>naive</code>, <code>meanf</code>, <code>rwf</code> y <code>snaive</code>), la función <code>ets</code> solo estima los modelos, pero no produce predicciones. Para ello habrá que usar la función <code>forecast</code> sobre un modelo estimado con <code>ets</code>. El principal argumento de esta función es <code>h</code> que especifica el horizonte temporal de predicción. También puedes usar <code>level</code> para fijar el nivel de confianza del intervalo de predicción.</p>
<p>Mira la ayuda de <code>R</code> para ver una explicación detallada de los argumentos de estas las funciones <code>ets</code> y <code>forecast</code>.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-exponencial-simple-a-n-n" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Alisado exponencial simple (A, N, N)</h1>
<p><br>
</p>
<section id="definición" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="definición"><span class="header-section-number">4.1</span> Definición</h2>
<p>El alisado exponencial simple es adecuado para una serie estacionaria y sin estacionalidad. Es decir, una serie que se mueve alrededor de un nivel constante.</p>
<p>La ecuación de la <strong>predicción intra-muestral</strong> es <span class="math display">\[\widehat{y}_{t+1} = \alpha y_t + \alpha (1-\alpha) y_{t-1} + \alpha (1-\alpha)^2 y_{t-2} + \alpha (1-\alpha)^3 y_{t-3} + \ldots =  \alpha y_t + (1-\alpha)\widehat{y}_{t},\]</span> donde <span class="math inline">\(0 \leq \alpha \leq 1\)</span> es el parámetro de suavizado. La primera <strong>predicción extra-muestral</strong> queda <span class="math display">\[\widehat{y}_{T+1}=\alpha y_T + (1-\alpha)\widehat{y}_{T}\]</span> y para las restantes <span class="math display">\[\widehat{y}_{T+h} = \widehat{y}_{T+1}.\]</span><br>
</p>
</section>
<section id="formulas-interactivas-de-sus-componentes" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="formulas-interactivas-de-sus-componentes"><span class="header-section-number">4.2</span> Formulas interactivas de sus componentes</h2>
<p>En el alisado exponencial simple solo hay una componente, el nivel <span class="math inline">\(l_t\)</span>.</p>
<ul>
<li>La <strong>ecuación recursiva</strong> de suavizado es <span class="math inline">\(l_t=\alpha y_t + (1-\alpha)l_{t-1}\)</span></li>
<li>La ecuación de <strong>predicción intra-muestral</strong> es <span class="math inline">\(\widehat{y}_{t+1} = l_t\)</span></li>
<li>La ecuación de <strong>predicción extra-muestral</strong> es <span class="math inline">\(\widehat{y}_{T+h} = \widehat{y}_{T+1} = l_T\)</span></li>
</ul>
<p>Dos estimaciones razonables de <span class="math inline">\(l_t\)</span>, el nivel de la serie en el periodo <span class="math inline">\(t\)</span>, son el valor observado para la serie en ese periodo <span class="math inline">\(y_t\)</span> y el nivel del periodo previo <span class="math inline">\(l_{t-1}\)</span>. La estimación final de <span class="math inline">\(l_t\)</span> es una media ponderada de ambas y esta estimación final es la previsión de la serie para el periodo siguiente.</p>
<p><br>
</p>
</section>
<section id="estimación-de-los-parámetros-del-modelo" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="estimación-de-los-parámetros-del-modelo"><span class="header-section-number">4.3</span> Estimación de los parámetros del modelo</h2>
<p>Dado el proceso iterativo para el cálculo de <span class="math inline">\(l_t\)</span> se necesita un <strong>valor inicial</strong> de arranque <span class="math inline">\(l_0\)</span>. Cada programa estadístico usa su propio método para obtener <span class="math inline">\(l_0\)</span>.</p>
<p>Respecto de <span class="math inline">\(\alpha\)</span>, usualmente se estima el valor <strong>optimo</strong> según un criterio de precisión de la predicción. El parámetro <span class="math inline">\(\alpha\)</span> <strong>se puede interpretar</strong> como:</p>
<ul>
<li>Si <span class="math inline">\(\alpha = 1\)</span> se tiene el <em>método ingenuo I</em> (<span class="math inline">\(\widehat{y}_{t+1}=y_t\)</span>), óptimo cuando el nivel de la serie varía constantemente en el tiempo.</li>
<li>Si <span class="math inline">\(\alpha = 0\)</span> se tiene <span class="math inline">\(\widehat{y}_{t} =l_0\)</span>, óptimo cuando el nivel permanece constante en el tiempo.</li>
</ul>
<p>En concreto <code>ets</code> estima por defecto los parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(l_0\)</span> maximizando la función de verosimilitud. Esta búsqueda está restringida a <span class="math inline">\(0 &lt; \alpha &lt; 1\)</span>. Es decir el parámetro <span class="math inline">\(\alpha\)</span> nunca puede ser 0 o 1 y en la práctica sus valores limite son 0.0001 y 0.9999.</p>
<p><br>
</p>
</section>
<section id="ejemplo" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="ejemplo"><span class="header-section-number">4.4</span> Ejemplo</h2>
<p>Vamos a usar el método de alisado exponencial simple para predecir la serie Demanda eléctrica semanal desde la primera semana de febrero (semana 6 del año) hasta la última semana de mayo (semana 22 del año), en total 17 semanas. Usaremos para ello la función <code>ets</code> con <code>model = "ANN</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Consumo electrico.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">ts</span>(electricidad[, <span class="dv">2</span>],</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Nos quedamos con los meses de febrero a mayo.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">window</span>(electricidad, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">7</span>)) </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos la serie de consumo semanal</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>electricidadSemanal <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(electricidad, <span class="at">FUN =</span> sum) </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>electricidadEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(electricidadSemanal, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model =</span> <span class="st">"ANN"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(electricidadEts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,N,N) 

Call:
 ets(y = electricidadSemanal, model = "ANN") 

  Smoothing parameters:
    alpha = 0.5839 

  Initial states:
    l = 5034.1607 

  sigma:  158.4303

     AIC     AICc      BIC 
224.2576 226.1037 226.7572 

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -40.34035 148.8194 82.91992 -0.9090506 1.789911 0.8506723
                   ACF1
Training set 0.01332464</code></pre>
</div>
</div>
<p>Veamos la salida en detalle:</p>
<ul>
<li>El valor de <span class="math inline">\(\alpha\)</span> que optimiza el criterio usado para medir la calidad del ajuste es <span class="math inline">\(\alpha =\)</span> 0.58, un valor intermedio, ni cercano a 0 ni cercano a 1. Es decir, la serie Demanda eléctrica cambia de nivel poco a poco.</li>
<li>El valor de arranque <span class="math inline">\(l_0\)</span> óptimo es 5034.16.</li>
<li><em>sigma</em> es la desviación típica del error (aditivo) de predicción. Se diferencia de RMSE en el denominador. Para calcular <em>sigma</em> en lugar de dividir por <span class="math inline">\(T\)</span> se divide por <span class="math inline">\(T\)</span> menos el número de parámetros estimados, en este caso 3: <span class="math inline">\(l_0\)</span>, <span class="math inline">\(\alpha\)</span> y <em>sigma</em>. Sí, <em>sigma</em>, se considerará siempre otro parámetro estimado.</li>
<li>La calidad del ajuste es bueno, como evidencia el error porcentual medio del 1.8%.</li>
</ul>
<p>En el objeto <code>electricidadEts</code> la matriz <code>electricidadEts$states</code> guarda todos los valores del nivel obtenidos con la ecuación recursiva, incluidos el valor de arranque, así que es una matriz con <span class="math inline">\(T+1\)</span> filas (18 en el ejemplo). Puedes ver el valor de <span class="math inline">\(l_{22}\)</span> de la última semana de mayo de 2021 (semana 22 del año) en su última fila, que vale 4633.76.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(electricidadEts<span class="sc">$</span>states, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time Series:
Start = 22 
End = 22 
Frequency = 1 
            l
[1,] 4633.761</code></pre>
</div>
</div>
<p>Así, la predicción para la primera semana de junio es <span class="math inline">\(\widehat{y}_{23}=l_{22}=\)</span> 4633.76. Igualmente <span class="math inline">\(\widehat{y}_{24}=l_{22}=\)</span> 4633.76. Es decir, todas las previsiones son iguales a <span class="math inline">\(l_{22}\)</span>.</p>
<p>Mediante la función <code>forecast</code> podemos predecir los casos de Demanda eléctrica para las próximas 5 semanas. Por tratarse de un modelo sin pendiente ni estacionalidad, la predicción es constante en el tiempo. Recuerda que <span class="math inline">\(\widehat{y}_{T+h} = l_T\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>electricidadf <span class="ot">&lt;-</span> <span class="fu">forecast</span>(electricidadEts,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>electricidadf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Point Forecast    Lo 95    Hi 95
23       4633.761 4323.243 4944.279
24       4633.761 4274.192 4993.330
25       4633.761 4231.072 5036.450
26       4633.761 4192.142 5075.380
27       4633.761 4156.376 5111.146</code></pre>
</div>
</div>
<p>La <a href="#fig-electricidadANN">Figura&nbsp;1</a> muestra la serie Demanda eléctrica, las previsiones extra-muestrales que son constantes y el intervalo de confianza. Conforme aumentamos el horizonte de predicción, el intervalo de confianza es más amplio como reflejo de la mayor incertidumbre en la predicción.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(electricidadf,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadANN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-electricidadANN-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;1: Consumo semanal de electricidad (febrero a mayo 2021) y predicción con alisado simple</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-exponencial-de-holt-a-a-n" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Alisado exponencial de Holt (A, A, N)</h1>
<p>El alisado exponencial de Holt es adecuado para una serie no estacionaria y sin estacionalidad.</p>
<p><br>
</p>
<section id="formulas-interactivas-de-sus-componentes-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="formulas-interactivas-de-sus-componentes-1"><span class="header-section-number">5.1</span> Formulas interactivas de sus componentes</h2>
<p>Las <strong>ecuaciones recursivas</strong> son</p>
<span class="math display">\[\begin{aligned}
l_t &amp; =\alpha y_t + (1-\alpha)(l_{t-1}+b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)b_{t-1}
\end{aligned}\]</span>
<p>La ecuación de la <strong>predicción intra-muestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1} = l_t + b_t,\]</span> de forma que la ecuación de <strong>predicción extra-muestral</strong> es <span class="math display">\[\widehat{y}_{T+h}=l_T + h b_T.\]</span></p>
<p>Dos estimaciones razonables del nivel de la serie en el periodo <span class="math inline">\(t\)</span> son el valor observado para la serie en ese periodo <span class="math inline">\(y_t\)</span>, y una estimación del nivel del periodo <span class="math inline">\(t\)</span> realizada desde el periodo <span class="math inline">\(t-1\)</span>: <span class="math inline">\(l_{t-1} + b_{t-1}\)</span>. Por otro lado, dos estimaciones razonables de la pendiente de la serie en el periodo <span class="math inline">\(t\)</span> son el cambio de nivel de <span class="math inline">\(t-1\)</span> a <span class="math inline">\(t\)</span> (el último observado) <span class="math inline">\(l_t-l_{t-1}\)</span>, y el valor de la pendiente en el periodo previo, <span class="math inline">\(b_{t-1}\)</span>. En ambos casos, nivel y pendiente, la estimación final es una media ponderada, parametrizada por <span class="math inline">\(0 \leq \alpha, \: \beta \leq 1\)</span>.</p>
<p>Observa que el <em>método ingenuo II</em> es un caso concreto de Alisado de Holt. Si hacemos <span class="math inline">\(\alpha=\beta = 1,\)</span> queda <span class="math inline">\(l_t=y_t\)</span> y <span class="math inline">\(b_t=y_t-y_{t-1}\)</span>, por tanto <span class="math display">\[\widehat{y}_{t+1}=l_t + b_t = y_t + (y_t - y_{t-1}).\]</span> y <span class="math display">\[\widehat{y}_{T+h}=l_T + h \cdot b_T = y_T + h(y_T - y_{T-1}).\]</span></p>
<p><br>
</p>
</section>
<section id="estimación-de-los-parámetros-del-modelo-1" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="estimación-de-los-parámetros-del-modelo-1"><span class="header-section-number">5.2</span> Estimación de los parámetros del modelo</h2>
<p>Para aplicar este método es necesario estimar unos valores iniciales <span class="math inline">\(l_0\)</span> y <span class="math inline">\(b_0\)</span> de las ecuaciones recursivas e identificar los valores más adecuados de los parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>.</p>
<p>La función <code>ets</code> estima por defecto los parámetros <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, <span class="math inline">\(l_0\)</span> y <span class="math inline">\(b_0\)</span> maximizando la función de verosimilitud. En este caso la búsqueda está restringida a <span class="math inline">\(0 &lt; \beta &lt; \alpha &lt; 1\)</span>. Por tanto, <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span> nunca pueden ser 0 o 1 y en la práctica sus valores limite son 0.0001 y 0.9999.</p>
<p>La interpretación del parámetro <span class="math inline">\(\alpha\)</span> es similar al caso del alisado exponencial simple.</p>
<p><strong>Interpretación del parámetro</strong> <span class="math inline">\(\beta\)</span>:</p>
<ul>
<li>Si <span class="math inline">\(\beta = 1\)</span>, <span class="math inline">\(b_t = l_t - l_{t-1}\)</span>, la pendiente se actualiza constantemente porque varía periodo a periodo Puede ser un indicador de mal ajuste (tendencia no lineal o pendiente no aditiva).</li>
<li>Si <span class="math inline">\(\beta = 0\)</span>, <span class="math inline">\(b_t = b_{t-1}= \ldots = b_0\)</span>, la pendiente se mantiene constante en el tiempo.</li>
</ul>
<p><br>
</p>
</section>
<section id="ejemplo-1" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="ejemplo-1"><span class="header-section-number">5.3</span> Ejemplo</h2>
<p>Vamos a usar el método de alisado de Holt para predecir la serie Libros. Usaremos para ello la función <code>ets</code> con los argumentos <code>model = "AAN"</code> y <code>damped = FALSE</code>. El segundo argumento previene el uso de tendencia amortiguada que veremos en el siguiente epígrafe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/libros.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">ts</span>(libros[, <span class="dv">2</span>], </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">start =</span> <span class="dv">1993</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">frequency  =</span> <span class="dv">1</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>librosEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(libros, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">model =</span> <span class="st">"AAN"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(librosEts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,A,N) 

Call:
 ets(y = libros, model = "AAN", damped = FALSE) 

  Smoothing parameters:
    alpha = 0.9461 
    beta  = 0.0001 

  Initial states:
    l = 43015.3558 
    b = 866.6661 

  sigma:  6235.705

     AIC     AICc      BIC 
566.5129 569.3700 572.9921 

Training set error measures:
                    ME     RMSE     MAE        MPE    MAPE      MASE
Training set -91.75606 5755.295 4179.61 -0.3817069 6.68946 0.9237963
                    ACF1
Training set 0.004201274</code></pre>
</div>
</div>
<p>Los valores óptimos de los cuatro parámetros son <span class="math inline">\(\alpha=\)</span> 0.95, <span class="math inline">\(\beta=\)</span> 0, <span class="math inline">\(l_0 =\)</span> 43015.36 y <span class="math inline">\(b_0 =\)</span> 866.67. Observa que <span class="math inline">\(\alpha\)</span> es prácticamente 1 y que <span class="math inline">\(\beta\)</span> es cero. Si aplicamos estos valores de los parámetros a las ecuaciones recursivas y la predicción extra-muestral, obtenemos <span class="math inline">\(y_{T+h}=y_T + hb_0\)</span>: la predicción es el último valor observado más <span class="math inline">\(h\)</span> veces la primera pendiente estimada. La calidad de las predicciones es razonable, con un error porcentual medio del 6.7%.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Parámetros estimados
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Cuántos parámetros se han estimado (y la respuesta no es 4)? ¿Cuál es el denominador en el cálculo de RMSE y de <em>sigma</em>?</p>
</div>
</div>
<p>En el objeto <code>librosEts</code> la matriz <code>librosEts$states</code> guarda todos los valores obtenidos con las ecuaciones recursivas, en este caso el nivel y la pendiente, incluidos los valores de arranque. Puedes ver los valores de <span class="math inline">\(l_{2019}\)</span> y <span class="math inline">\(b_{2019}\)</span> en su última fila, que valen respectivamente 64091.02, 866.42.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(librosEts<span class="sc">$</span>states, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time Series:
Start = 2019 
End = 2019 
Frequency = 1 
            l        b
2019 64091.02 866.4181</code></pre>
</div>
</div>
<p>Así, la predicción para <span class="math inline">\(2020\)</span> es <span class="math inline">\(\widehat{y}_{2020}=l_{2019} + b_{2019}=\)</span> 64091.02 <span class="math inline">\(+\)</span> 866.42 <span class="math inline">\(=\)</span> 64957.43. Igualmente <span class="math inline">\(\widehat{y}_{2021}=l_{2019} + 2\cdot b_{2019}=\)</span> 65823.85. Es decir, el incremento entre previsiones es constante e igual a <span class="math inline">\(b_{2019}\)</span> que, por ser <span class="math inline">\(\beta\)</span> prácticamente nulo, coincide con <span class="math inline">\(b_0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>librosf <span class="ot">&lt;-</span> <span class="fu">forecast</span>(librosEts,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>librosf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020       64957.43 52735.68 77179.19
2021       65823.85 48998.58 82649.13
2022       66690.27 46273.69 87106.85
2023       67556.69 44091.57 91021.81
2024       68423.11 42261.77 94584.44</code></pre>
</div>
</div>
<p>La <a href="#fig-librosAAN">Figura&nbsp;2</a> muestra la serie Libros y las previsiones extra-muestrales que muestran una ligera tendencia creciente.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(librosf,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-librosAAN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-librosAAN-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: Libros y predicción con alisado de Holt</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-exponencial-con-pendiente-amortiguada-a-ad-n" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Alisado exponencial con pendiente amortiguada (A, Ad, N)</h1>
<p>Las previsiones con el método de Holt presentan siempre una pendiente constante. En previsiones a corto plazo esto no es un problema, pero para previsiones a largo plazo la experiencia indica que suele aparecer un sesgo de previsión. El alisado exponencial con pendiente amortiguada trata de corregir esta limitación. El mecanismo, propuesto por <span class="citation" data-cites="Gardner85">Everette S. Gardner and Mckenzie (<a href="#ref-Gardner85" role="doc-biblioref">1985</a>)</span>, es introducir un nuevo parámetro <span class="math inline">\(0 \leq \phi \leq 1\)</span> que <em>amortigua</em> la tendencia hasta hacerla plana en el largo plazo.</p>
<p><br>
</p>
<section id="formulas-interactivas-de-sus-componentes-2" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="formulas-interactivas-de-sus-componentes-2"><span class="header-section-number">6.1</span> Formulas interactivas de sus componentes</h2>
<p>Las <strong>ecuaciones recursivas</strong> son <span class="math display">\[
\begin{aligned}
l_t &amp; =\alpha y_t + (1-\alpha)(l_{t-1}+\phi b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)\phi b_{t-1}
\end{aligned}
\]</span></p>
<p>La ecuación de la <strong>predicción intra-muestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1} = l_t + \phi b_t,\]</span> de forma que la ecuación de <strong>predicción extra-muestral</strong> es <span class="math display">\[\widehat{y}_{T+h}=l_T + (\phi + \phi^2 + \ldots + \phi^h) b_T.\]</span></p>
<p>Como observas, se ha añadido un nuevo parámetro <span class="math inline">\(\phi\)</span>, que acompaña siempre a la pendiente $b_t. $Si <span class="math inline">\(\phi = 1\)</span>, se tiene el alisado de Holt y si <span class="math inline">\(\phi = 0\)</span>, se tiene el alisado simple. Para valores entre <span class="math inline">\(0\)</span> y <span class="math inline">\(1\)</span> en el corto plazo las predicciones tienen pendiente y en el largo plazo se hacen constantes e iguales a <span class="math inline">\(l_T + \phi b_T/(1 - \phi)\)</span>.</p>
<p>Por razones prácticas el rango de búsqueda de <span class="math inline">\(\phi\)</span> queda en el intervalo <span class="math inline">\([0.8, 0.98]\)</span>. Si el valor óptimo de <span class="math inline">\(\phi\)</span> fuera su valor máximo de <span class="math inline">\(0.98\)</span> o muy cercano a este valor, cabría plantearse si no sería más adecuado un modelo sin amortiguamiento.</p>
<p><br>
</p>
</section>
<section id="ejemplo-2" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="ejemplo-2"><span class="header-section-number">6.2</span> Ejemplo</h2>
<p>Vamos a usar el método de alisado con amortiguamiento para predecir, una vez más, la serie Libros añadiendo a la función <code>ets</code> el argumento <code>damped = TRUE</code>. En este caso, para ver el efecto del <em>amortiguamiento</em> vamos a pedir un horizonte temporal más largo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>librosEtsD <span class="ot">&lt;-</span> <span class="fu">ets</span>(libros, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">model =</span> <span class="st">"AAN"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">damped =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(librosEtsD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,Ad,N) 

Call:
 ets(y = libros, model = "AAN", damped = TRUE) 

  Smoothing parameters:
    alpha = 0.8971 
    beta  = 0.0001 
    phi   = 0.9083 

  Initial states:
    l = 41396.6242 
    b = 2881.012 

  sigma:  6239.024

     AIC     AICc      BIC 
567.3414 571.5414 575.1164 

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -159.4816 5631.786 3984.248 -0.6273468 6.314471 0.8806165
                   ACF1
Training set 0.01091024</code></pre>
</div>
</div>
<p>El valor óptimo del parámetro <span class="math inline">\(\phi\)</span> es <span class="math inline">\(0.91\)</span> y el error porcentual 6.3%, algo inferior al obtenido con el alisado de Holt sin amortiguamiento. La inclusión de un nuevo parámetro en el modelo mejora el ajuste.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Parámetros estimados
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Cuántos parámetros se han estimado en este caso? ¿Cuáles?</p>
</div>
</div>
<p>La <a href="#fig-librosAAdN">Figura&nbsp;3</a> muestra la serie Libros, su estimación (intra-muestral) y las predicciones a 15 años vista. Observa que la pendiente de las previsiones se <em>amortigua</em> en el tiempo, de forma que al principio las previsiones crecen más rápidamente que en los últimos años.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>librosfD <span class="ot">&lt;-</span> <span class="fu">forecast</span>(librosEtsD, <span class="at">h =</span> <span class="dv">15</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>librosfD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 80    Hi 80    Lo 95     Hi 95
2020       64148.96 56153.33 72144.59 51920.70  76377.22
2021       64325.91 53583.64 75068.19 47897.02  80754.81
2022       64486.65 51568.74 77404.55 44730.42  84242.88
2023       64632.65 49855.75 79409.55 42033.33  87231.96
2024       64765.27 48338.19 81192.34 39642.22  89888.32
2025       64885.73 46959.54 82811.92 37469.99  92301.47
2026       64995.15 45685.72 84304.58 35463.92  94526.37
2027       65094.54 44494.40 85694.68 33589.35  96599.73
2028       65184.82 43370.08 86999.55 31822.06  98547.58
2029       65266.82 42301.54 88232.11 30144.45 100389.20
2030       65341.31 41280.33 89402.29 28543.22 102139.40
2031       65408.97 40299.99 90517.95 27008.10 103809.84
2032       65470.43 39355.40 91585.46 25530.94 105409.92
2033       65526.26 38442.47 92610.05 24105.17 106947.34
2034       65576.97 37557.83 93596.10 22725.40 108428.54</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(librosfD,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PI =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-librosAAdN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-librosAAdN-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;3: Libros y predicción con alisado exponencial con amortiguamiento</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="alisado-de-holt-winters-aditivo-a-a-a-y-multiplicativo-m-a-m" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Alisado de Holt-Winters aditivo (A, A, A) y multiplicativo (M, A, M)</h1>
<p>El método de alisado exponencial de Holt-Winters es adecuado para una serie con tendencia y estacionalidad. Existen dos versiones según que el esquema sea aditivo o multiplicativo.</p>
<p><br>
</p>
<section id="alisado-de-holt-winters-aditivo-a-a-a" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="alisado-de-holt-winters-aditivo-a-a-a"><span class="header-section-number">7.1</span> Alisado de Holt-Winters aditivo (A, A, A)</h2>
<p>Las <strong>ecuaciones recursivas</strong> de actualización son: <span class="math display">\[
\begin{aligned}
l_t &amp; =\alpha (y_t - s_{t-m} ) + (1-\alpha)(l_{t-1}+b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)b_{t-1} \\
s_t &amp; =\gamma (y_t - l_{t-1} - b_{t-1}) + (1 - \gamma)s_{t-m}
\end{aligned}
\]</span> con <span class="math inline">\(0 \leq \alpha, \beta, \gamma \leq 1\)</span>.</p>
<p>La ecuación de la <strong>predicción intra-muestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1}  = l_t + b_t + s_{t+1-m},\]</span> de forma que la ecuación de <strong>predicción extra-muestral es</strong>: <span class="math display">\[\widehat{y}_{T+h}=l_T + h b_T + s_{T+h - m(k+1)},\]</span> con <span class="math inline">\(k = \lfloor(h-1)/m\rfloor\)</span>.</p>
<p><br>
</p>
</section>
<section id="alisado-de-holt-winters-multiplicativo-m-a-m" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="alisado-de-holt-winters-multiplicativo-m-a-m"><span class="header-section-number">7.2</span> Alisado de Holt-Winters multiplicativo (M, A, M)</h2>
<p>Las <strong>ecuaciones recursivas</strong> de actualización son: <span class="math display">\[
\begin{aligned}
l_t &amp; =\alpha \frac{y_t}{s_{t-m}} + (1-\alpha)(l_{t-1}+b_{t-1}) \\
b_t &amp; =\beta (l_t - l_{t-1}) + (1-\beta)b_{t-1} \\
s_t &amp; =\gamma \frac{y_t}{l_{t-1} + b_{t-1}} + (1 - \gamma)s_{t-m}
\end{aligned}
\]</span></p>
<p>La ecuación de la <strong>predicción intra-muestral</strong> a un periodo vista es <span class="math display">\[\widehat{y}_{t+1}  = (l_t + b_t)s_{t+1-m},\]</span> de forma que la ecuación de <strong>predicción extra-muestral es</strong>: <span class="math display">\[\widehat{y}_{T+h}=(l_T + h b_T)s_{T+h - m(k+1)}.\]</span></p>
<p><br>
</p>
</section>
<section id="ejemplo-con-demanda-electrica" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="ejemplo-con-demanda-electrica"><span class="header-section-number">7.3</span> Ejemplo con Demanda electrica</h2>
<p>Vamos a usar el método de <strong>Holt-Winters Aditivo</strong> para predecir la serie Demanda eléctrica, que presentaba un esquema aditivo. Para ello usaremos la función <code>ets</code> con el argumento <code>model = "AAA"</code> (y <code>damped = FALSE</code>). Vamos a considerar la serie desde el 1 de febrero (lunes) hasta el 30 de mayo (domingo), 17 semanas, y pedir una previsión a dos semanas vista.</p>
<p>En el proceso de estimación, el parámetro <span class="math inline">\(\gamma\)</span> que gobierna la componente estacional está restringido a <span class="math inline">\(0 &lt; \gamma &lt; 1 - \alpha\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Consumo electrico.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">ts</span>(electricidad[, <span class="dv">2</span>],</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Nos quedamos con los meses de febrero a mayo.</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">window</span>(electricidad, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">7</span>)) </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>electricidadEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(electricidad, </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model =</span> <span class="st">"AAA"</span>, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(electricidadEts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,A,A) 

Call:
 ets(y = electricidad, model = "AAA", damped = FALSE) 

  Smoothing parameters:
    alpha = 0.8355 
    beta  = 0.0001 
    gamma = 0.0001 

  Initial states:
    l = 741.55 
    b = 0.0601 
    s = -88.686 -47.5536 19.731 30.4514 35.9361 36.6726
           13.4485

  sigma:  17.5704

     AIC     AICc      BIC 
1263.333 1266.276 1296.682 

Training set error measures:
                     ME     RMSE      MAE        MPE     MAPE      MASE
Training set -0.7940567 16.73864 10.45847 -0.1438659 1.587029 0.5252875
                   ACF1
Training set 0.03820125</code></pre>
</div>
</div>
<p>Los valores óptimos de los parámetros son <span class="math inline">\(\alpha=\)</span> 0.84, <span class="math inline">\(\beta=\)</span> 0 y <span class="math inline">\(\gamma=\)</span> 0. Los valores nulos para <span class="math inline">\(\beta\)</span> y <span class="math inline">\(\gamma\)</span> indican que ambas, la pendiente y la estacionalidad, permanecen constantes en el tiempo. La calidad de las predicciones es notable, con un error porcentual medio del 1.6%.</p>
<p>Los últimos valores de las componentes son</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(electricidadEts<span class="sc">$</span>states)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>      l       b      s1      s2      s3      s4      s5      s6      s7 
668.923   0.051 -88.685 -47.554  19.729  30.452  35.934  36.667  13.448 </code></pre>
</div>
</div>
<p>Como el último dato de la serie es domingo 30 de mayo, los valores del nivel <span class="math inline">\(l\)</span> y la pendiente <span class="math inline">\(b\)</span> mostrados corresponden a ese día. Sin embargo, la componente estacional tiene un orden muy peculiar: s1 es el valor estacional para domingo (día del último dato), s2 el de sábado, s3 de viernes, hasta s7 que sería lunes. Podemos reproducir las predicciones para los próximos 7 días, 31 de mayo a 6 de junio (ojo, el etiquetado de la salida no es correcto):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>)<span class="sc">*</span>electricidadEts<span class="sc">$</span>states[TT, <span class="dv">2</span>] <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  electricidadEts<span class="sc">$</span>states[TT, <span class="dv">9</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      s7       s6       s5       s4       s3       s2       s1 
682.4217 705.6918 705.0094 699.5780 688.9063 621.6741 580.5928 </code></pre>
</div>
</div>
<p>O mejor usar la función <code>forecast</code> para obtener las predicciones y sus intervalos a dos semanas vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>electricidadf <span class="ot">&lt;-</span> <span class="fu">forecast</span>(electricidadEts,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">h =</span> <span class="dv">14</span>, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>electricidadf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
23.00000       682.4217 647.9844 716.8591
23.14286       705.6918 660.8134 750.5702
23.28571       705.0094 651.6952 758.3236
23.42857       699.5780 638.9897 760.1663
23.57143       688.9063 621.8267 755.9859
23.71429       621.6741 548.6768 694.6714
23.85714       580.5928 502.1216 659.0640
24.00000       682.7765 599.1867 766.3664
24.14286       706.0466 617.6340 794.4592
24.28571       705.3642 612.3776 798.3508
24.42857       699.9328 602.5858 797.2798
24.57143       689.2611 587.7399 790.7823
24.71429       622.0289 516.4975 727.5603
24.85714       580.9476 471.5520 690.3432</code></pre>
</div>
</div>
<p>La <a href="#fig-electricidadAAA">Figura&nbsp;4</a> muestra la serie Demanda eléctrica y las previsiones extra-muestrales.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(electricidadf,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PI =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadAAA" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-electricidadAAA-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4: Demanda eléctrica y predicción con alisado de Holt-Winters aditivo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="ejemplo-con-nacimientos" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="ejemplo-con-nacimientos"><span class="header-section-number">7.4</span> Ejemplo con Nacimientos</h2>
<p>Vamos a usar el método de <strong>Holt-Winters multiplicativo</strong> para predecir la serie Nacimientos, que presentaba un esquema multiplicativo. En este caso usaremos el argumento <code>model = "MAM"</code> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Vamos a considerar la serie Nacimientos desde enero de 2000 y pedir una previsión a dos años vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/nacimientos.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">ts</span>(nacimientos[, <span class="dv">2</span>],</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1975</span>, <span class="dv">1</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>nacimientosb <span class="ot">&lt;-</span> <span class="fu">window</span>(nacimientos, <span class="at">start =</span> <span class="dv">2000</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>nacimientosbEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(nacimientosb, </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">model =</span> <span class="st">"MAM"</span>, </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nacimientosbEts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(M,A,M) 

Call:
 ets(y = nacimientosb, model = "MAM", damped = FALSE) 

  Smoothing parameters:
    alpha = 0.3187 
    beta  = 0.0541 
    gamma = 0.1828 

  Initial states:
    l = 33016.8308 
    b = 134.4179 
    s = 0.9976 0.9806 1.0479 1.0246 1.0248 1.0326
           0.9789 1.0242 0.9739 1.0001 0.919 0.996

  sigma:  0.0236

     AIC     AICc      BIC 
4575.865 4578.621 4635.035 

Training set error measures:
                    ME     RMSE      MAE        MPE     MAPE      MASE
Training set -13.31703 860.7476 675.2864 -0.0726126 1.823373 0.4868175
                  ACF1
Training set 0.0980623</code></pre>
</div>
</div>
<p>L os valores óptimos de los parámetros son <span class="math inline">\(\alpha=\)</span> 0.32, <span class="math inline">\(\beta=\)</span> 0.05 y <span class="math inline">\(\gamma=\)</span> 0.18. Los valores tan bajos para <span class="math inline">\(\beta\)</span> y <span class="math inline">\(\gamma\)</span> indican que ambas, la pendiente y la estacionalidad, modifican su valor muy lentamente. La calidad de las predicciones es notable, con un error porcentual medio del 1.8%.</p>
<p>Los últimos valores de las componentes son</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(nacimientosbEts<span class="sc">$</span>states)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>nacimientosbEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>        l         b        s1        s2        s3        s4        s5        s6 
29462.334   -77.537     0.995     1.000     1.066     1.042     1.046     1.049 
       s7        s8        s9       s10       s11       s12 
    0.978     0.999     0.949     0.980     0.896     0.994 </code></pre>
</div>
</div>
<p>Como el último dato de la serie es diciembre de 2019, los valores del nivel <span class="math inline">\(l\)</span> y la pendiente <span class="math inline">\(b\)</span> mostrados corresponden a ese mes. Sin embargo, recuerda que la componente estacional sigue un orden inverso: s1 es el valor estacional para diciembre (mes del último dato), s2 el de noviembre, s3 de octubre, hasta s11 que sería febrero y s12 que es enero.</p>
<p>Podemos reproducir las predicciones para los primeros 12 meses de enero a diciembre (ojo, el etiquetado de la salida no es correcto) para ver que coinciden con las obtenidas con la función <code>forecast</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(nacimientosbEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)<span class="sc">*</span>nacimientosbEts<span class="sc">$</span>states[TT, <span class="dv">2</span>]) <span class="sc">*</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  nacimientosbEts<span class="sc">$</span>states[TT, <span class="dv">14</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     s12      s11      s10       s9       s8       s7       s6       s5 
29208.44 26261.08 28659.28 27669.53 29035.26 28350.73 30332.66 30170.34 
      s4       s3       s2       s1 
29982.89 30583.87 28610.96 28402.26 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>nacimientosbf <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nacimientosbEts,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">h =</span> <span class="dv">24</span>, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>nacimientosbf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2020       29208.44 27858.19 30558.69
Feb 2020       26261.08 24965.01 27557.14
Mar 2020       28659.28 27134.81 30183.74
Apr 2020       27669.53 26072.36 29266.71
May 2020       29035.26 27208.76 30861.76
Jun 2020       28350.73 26403.10 30298.36
Jul 2020       30332.66 28056.12 32609.20
Aug 2020       30170.34 27698.52 32642.16
Sep 2020       29982.89 27305.72 32660.06
Oct 2020       30583.87 27614.07 33553.67
Nov 2020       28610.96 25597.03 31624.89
Dec 2020       28402.26 25164.92 31639.60
Jan 2021       28286.46 24710.45 31862.47
Feb 2021       25429.93 21982.37 28877.49
Mar 2021       27749.82 23723.48 31776.16
Apr 2021       26789.14 22637.45 30940.82
May 2021       28108.94 23465.20 32752.67
Jun 2021       27443.82 22620.07 32267.58
Jul 2021       29359.74 23879.54 34839.95
Aug 2021       29200.02 23422.41 34977.63
Sep 2021       29015.99 22940.65 35091.33
Oct 2021       29594.92 23048.56 36141.28
Nov 2021       27683.28 21224.32 34142.25
Dec 2021       27478.84 20726.54 34231.15</code></pre>
</div>
</div>
<p>La <a href="#fig-nacimientosMAM">Figura&nbsp;5</a> muestra la serie Nacimientos y las previsiones extra-muestrales.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientosbf,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PI =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientosMAM" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-nacimientosMAM-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;5: Nacimientos y predicción con alisado de Holt-Winters multiplicativo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="ejemplo-con-transformación-logarítmica" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Ejemplo con transformación logarítmica</h1>
<p>Una alternativa para predecir la serie Nacimientos, que tiene esquema multiplicativo, es predecir la transformación logarítmica de la serie, que tendrá un esquema aditivo. Después, se aplica la transformación inversa y se obtienen las predicciones de la serie original.</p>
<p>Este proceso se puede realizar de forma sencilla y transparente con cualquiera de las funciones de que hemos visto a partir de los argumentos <code>lambda</code> y <code>biasadj</code>.</p>
<ul>
<li><code>lambda = 0</code> indica que se ha de realizar la transformación logarítmica de la serie previamente a su modelización. Es un parámetro de la transformación Box-Cox que comentaremos en el tema 6.</li>
<li><code>biasadj = TRUE</code> es necesario si tras una transformación de la serie original queremos que las predicciones sean insesgadas. Sea <span class="math inline">\(y_t\)</span> la serie original y <span class="math inline">\(z_t=log(y_t)\)</span> su transformación logarítmica. Si obtenemos una predicción <span class="math inline">\(\widehat{y}_t\)</span> de la serie original, esta será insesgada <span class="math inline">\(E[\widehat{y}_t]=y_t\)</span>. Ahora bien, si obtenemos una predicción <span class="math inline">\(\widehat{z}_t\)</span> de la serie transformada, podemos pensar que <span class="math inline">\(e^{\widehat{z}_t}\)</span> es una predicción insesgada de la serie original, pero resulta que <span class="math inline">\(E[e^{\widehat{z}_t}] \neq y_t\)</span>. Es decir, la exponencial de la predicción de la serie con transformada logarítmica no es insesgada. Si el argumento <code>biasadj</code> es fijado a FALSE, las predicciones se calcularán de forma directa deshaciendo la transformación y serán sesgadas; si es fijado a TRUE, las predicciones se calcularán por medio de una fórmula alternativa y serán insesgadas. En ambos casos las estimaciones son consistentes, así que para series largas no debería observarse mucha diferencia entre las dos alternativas. Sin entrar en detalles matemáticos, cuanto menor es <em>sigma</em> menor será el sesgo en las predicciones.</li>
</ul>
<p>Vamos a practicar el uso de estos argumentos con la serie Nacimientos. Como se va a predecir el logaritmo de la serie, se debe indicar a la función <code>ets</code> <code>model = "AAA"</code> que estima el modelo Holt-Winters aditivo. Además, vamos a pedir que las predicciones sean insesgadas con <code>biasadj = TRUE</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>nacimientosbEtsl <span class="ot">&lt;-</span> <span class="fu">ets</span>(nacimientosb, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">model =</span> <span class="st">"AAA"</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">damped =</span> <span class="cn">FALSE</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">biasadj =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nacimientosbEtsl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,A,A) 

Call:
 ets(y = nacimientosb, model = "AAA", damped = FALSE, lambda = 0,  

 Call:
     biasadj = TRUE) 

  Box-Cox transformation: lambda= 0 

  Smoothing parameters:
    alpha = 0.1837 
    beta  = 0.0388 
    gamma = 0.2065 

  Initial states:
    l = 10.4277 
    b = 0.0054 
    s = -0.002 -0.0129 0.0234 0.0279 0.0247 0.0463
           -0.0196 0.0249 -0.0159 0.0048 -0.0917 -0.01

  sigma:  0.0251

      AIC      AICc       BIC 
-435.0269 -432.2701 -375.8560 

Training set error measures:
                    ME     RMSE      MAE        MPE    MAPE      MASE      ACF1
Training set -41.36344 920.7979 725.9736 -0.1486283 1.95657 0.5233582 0.3028936</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>nacimientosbfl <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nacimientosbEtsl,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">h =</span> <span class="dv">24</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">level =</span> <span class="dv">95</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">biasadj =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>nacimientosbfl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2020       29254.96 27839.14 30723.35
Feb 2020       26281.62 24979.19 27633.61
Mar 2020       28628.09 27164.86 30148.82
Apr 2020       27589.67 26124.95 29114.26
May 2020       28904.00 27299.75 30576.95
Jun 2020       28198.65 26553.18 29918.37
Jul 2020       30208.17 28346.45 32158.83
Aug 2020       30108.75 28142.19 32175.16
Sep 2020       29953.46 27875.09 32144.30
Oct 2020       30594.89 28336.41 32983.84
Nov 2020       28662.62 26410.16 31054.13
Dec 2020       28450.02 26069.89 30987.22
Jan 2021       28342.75 25713.85 31165.40
Feb 2021       25465.54 22966.39 28160.40
Mar 2021       27743.17 24863.99 30861.88
Apr 2021       26741.03 23808.63 29932.45
May 2021       28019.64 24776.14 31567.10
Jun 2021       27340.77 24003.55 31009.48
Jul 2021       29294.73 25528.88 33456.66
Aug 2021       29204.21 25255.37 33592.34
Sep 2021       29059.78 24932.13 33672.57
Oct 2021       29688.73 25264.69 34661.52
Nov 2021       27820.24 23476.76 32731.64
Dec 2021       27620.71 23108.37 32754.26</code></pre>
</div>
</div>
<p>Observa que en este caso la calidad de las predicciones (MAPE = 2.0%) es inferior a la obtenida con la serie sin transformar.</p>
<p>La <a href="#fig-nacimientoslog">Figura&nbsp;6</a> muestra la serie Nacimientos y las previsiones extra-muestrales obtenidas con y sin la transformación logarítmica.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nacimientoslog" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-nacimientoslog-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;6: Nacimientos y dos predicciones con alisado de Holt-Winters</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#tbl-nacimientoslog">Tabla&nbsp;2</a> muestra las predicciones de Nacimientos obtenidas sin transformar la serie, con transformación logarítmica y predicciones insesgadas (<code>biasadj = TRUE</code>), y con transformación logarítmica y predicciones sesgadas (<code>biasadj = FALSE</code>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-nacimientoslog" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabla&nbsp;2: Diferencias en la predicción según transformación logarítmica y corrección por sesgo</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Sin transformar</th>
<th style="text-align: right;">log(Nac) insesgadas</th>
<th style="text-align: right;">log(Nac) sesgadas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">29208.44</td>
<td style="text-align: right;">29254.96</td>
<td style="text-align: right;">29245.71</td>
</tr>
<tr class="even">
<td style="text-align: right;">26261.08</td>
<td style="text-align: right;">26281.62</td>
<td style="text-align: right;">26272.90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28659.28</td>
<td style="text-align: right;">28628.09</td>
<td style="text-align: right;">28617.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">27669.53</td>
<td style="text-align: right;">27589.67</td>
<td style="text-align: right;">27579.14</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29035.26</td>
<td style="text-align: right;">28904.00</td>
<td style="text-align: right;">28891.92</td>
</tr>
<tr class="even">
<td style="text-align: right;">28350.73</td>
<td style="text-align: right;">28198.65</td>
<td style="text-align: right;">28185.60</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30332.66</td>
<td style="text-align: right;">30208.17</td>
<td style="text-align: right;">30192.53</td>
</tr>
<tr class="even">
<td style="text-align: right;">30170.34</td>
<td style="text-align: right;">30108.75</td>
<td style="text-align: right;">30091.18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29982.89</td>
<td style="text-align: right;">29953.46</td>
<td style="text-align: right;">29933.68</td>
</tr>
<tr class="even">
<td style="text-align: right;">30583.87</td>
<td style="text-align: right;">30594.89</td>
<td style="text-align: right;">30571.95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28610.96</td>
<td style="text-align: right;">28662.62</td>
<td style="text-align: right;">28638.17</td>
</tr>
<tr class="even">
<td style="text-align: right;">28402.26</td>
<td style="text-align: right;">28450.02</td>
<td style="text-align: right;">28422.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Observa que las predicciones sesgadas son menores que las insesgadas. Esto siempre es así. La diferencia depende fundamentalmente de la desviación típica del error, <em>sigma</em> en la salida de los métodos de alisado exponencial. Cuanto mayor es <em>sigma</em>, mayores son las diferencias.</p>
<p>Por otro lado, las predicciones obtenidas sin y con la transformación logarítmica no guardan ninguna relación.</p>
<p><strong>Ni la transformación logarítmica ni el uso de predicciones insesgadas aseguran mejores predicciones respecto de otras opciones</strong>, como puede ser trabajar con predicciones sesgadas o no realizar la transformación logarítmica.</p>
<p><br>
<br>
</p>
</section>
<section id="casos-generales-de-alisado-exponencial-la-función-ets-de-nuevo" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Casos generales de alisado exponencial: la función <code>ets</code> (de nuevo)</h1>
<p>En los epígrafes previos hemos visto cinco de los casos expuestos en la taxonomía de la <a href="#tbl-taxonomia">Tabla&nbsp;1</a>, fijados a partir del argumento <code>model</code> de la función <code>ets</code>. Veamos ahora como estimar cualquiera de los treinta modelos que surgen según las diferentes posibilidades de la tendencia (N, A, Ad, M y Md), la estacionalidad (N, A y M) y el error (A, M).</p>
<p>Recordemos que el tipo de error no influye en el cálculo de las previsiones, solo influye en el cálculo del intervalo de confianza de estas.</p>
<p><strong>Podemos estimar cualquiera de los treinta modelos usando la función <code>ets</code> del paquete <code>forecast</code>.</strong></p>
<p>Lo más habitual es no saber cual es el mejor modelo, entendiendo como tal, el que mejor se ajusta a la serie temporal. De hecho, si lo que buscamos es predecir bien, el mejor modelo será el que mejor prediga.</p>
<p>Si en una de las tres letras del código del modelo se indica “Z”, la función <code>ets</code> selecciona de entre los modelos posibles el que mejor se ajusta. Por ejemplo, <code>model = "AAZ"</code> indica un modelo con error y pendiente aditivos y dejaría a <code>ets</code> la búsqueda de la mejor opción para la estacionalidad (aditiva o multiplicativa). Si se especifica <code>model = "ZZZ</code> junto con <code>damped = NULL</code> (opciones por defecto) se dejaría a la función total libertad para buscar entre todos los modelos (excepto aquellos con pendiente multiplicativa). Si se desea restringir la búsqueda a modelos sin amortiguamiento basta indicar <code>damped = FALSE</code> y si se desea restringir la búsqueda solo a modelos aditivos se puede usar el argumento <code>additive.only = TRUE</code>.</p>
<section id="criterios-de-optimización" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="criterios-de-optimización"><span class="header-section-number">9.1</span> Criterios de optimización</h2>
<p>Fijado un modelo, <code>ets</code> estima por defecto sus parámetros maximizando la función de verosimilitud. Esta búsqueda esta restringida a <span class="math inline">\(0 &lt; \beta &lt; \alpha &lt; 1\)</span>, <span class="math inline">\(0 &lt; \gamma &lt; 1 - \alpha\)</span> y <span class="math inline">\(0.8 &lt; \phi &lt; 0.98\)</span>. Es decir, los tres primeros parámetros nunca pueden ser 0 o 1, y en la práctica sus valores límite son 0.0001 y 0.9999.</p>
<p>Puedes cambiar el criterio de optimización con el argumento <code>opt.crit</code>. Por defecto vale “lik” (de <em>likelihood</em> o verosimilitud), pero si lo fijas a <code>opt.crit = "mse"</code> se estiman los parámetros que minimizan el error cuadrático medio. Otra opción interesante es <code>opt.crit = "amse"</code> que minimiza la media de los errores cuadráticos medios obtenido sobre las previsiones hasta <code>nmse</code> periodos vista. En este caso usa el argumento <code>nmse</code> para fijar el valor numérico del horizonte temporal.</p>
</section>
<section id="criterios-de-selección-de-modelos" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="criterios-de-selección-de-modelos"><span class="header-section-number">9.2</span> Criterios de selección de modelos</h2>
<p>Queda pendiente saber que criterio se usa para seleccionar el modelo cuando se ofrece esta opción. Esto se hace a partir de un criterio de información entre Akaike (aic), Akaike corregido para pequeñas muestras (aicc) y el Bayesiano (bic). Sus fórmulas son: <span class="math display">\[aic = -2log(L) + 2k\]</span> <span class="math display">\[aicc = aic + \frac{k(k+1)}{T-k-1}\]</span> <span class="math display">\[bic=aic + k(log(T) - 2)\]</span> donde <span class="math inline">\(L\)</span> es la verosimilitud, <span class="math inline">\(T\)</span> el número de datos y <span class="math inline">\(k\)</span> el de parámetros estimados (incluidos los puntos iniciales de arranque y la desviación típica del error).</p>
<p><strong>Cuanto menor es el criterio de información, mejor modelo</strong>. Por defecto se usa Akaike corregido para pequeñas muestras (aicc), pero el argumento <code>ic</code> permite cambiar de criterio.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Una reflexión sobre los métodos automáticos de selección de modelos
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con el comando <code>forecast(ets(nacimientos), h = 24)</code> obtenemos una predicción mensual a dos años vista del número de nacimientos en España. Así de simple, solo 31 caracteres. Todo esto gracias a que un algoritmo interno ha estimado los parámetros de múltiples modelos, elegido el mejor modelo de todos y lo ha usado para obtener las predicciones. Podemos afirmar que tenemos las mejores predicciones. Un momento, ¿podemos?</p>
<p>Parémonos a reflexionar sobre lo que hemos hecho o, más bien, lo que el algoritmo ha hecho y a contrastarlo con lo que nosotros queríamos. Por un lado, el algoritmo estima los parámetros de un menú fijo de modelos y para ello usa un criterio de optimización, que por defecto es maximizar la función de verosimilitud; cuando ya tiene estimados todos los modelos, elije el mejor usando el criterio de información de Akaike corregido para muestras pequeñas; y finalmente, nosotros medimos la capacidad predictiva del modelo seleccionado usando el error absoluto porcentual medio. Vaya, resulta que en los procesos de identificación y estimación del mejor modelo se usan dos criterios diferentes, que además no coinciden con nuestro criterio de calidad de las predicciones.</p>
<p>Si consideramos que la calidad de un modelo viene dada por el error absoluto porcentual medio en las predicciones intra-muestrales a un periodo vista (lo que hemos decidido llamar MAPE), ¿no deberíamos estimar los parámetros del modelo usando como criterio la minimización del MAPE?, ¿no deberíamos elegir entre varios modelos aquel que presenta un MAPE menor? De esta forma, en todos los pasos del proceso se usa el mismo criterio, que es, además, el criterio que hemos considerado adecuado para valorar la calidad de las predicciones.</p>
<p>Pero no es esto lo que hacemos.</p>
<p>Nada nos garantiza que el modelo estimado y seleccionado por el algoritmo estime las mejores predicciones posibles. Y por <em>mejores</em> quiero decir que de entre todos los posibles modelos del menú y todos los posibles valores de sus parámetros, el seleccionado sea que el minimiza nuestro criterio de calidad de las predicciones.</p>
<p>Ahora ya podemos dar respuesta a la pregunta del primer párrafo: no, no podemos afirmar que nuestras predicciones sean las mejores.</p>
<p>Alguien dirá que casi seguro entre las predicciones subóptimas obtenidas por el algoritmo con su extraña mezcla de criterios y las predicciones óptimas de verdad no habrá mucha diferencia. Total, que más da una función de verosimilitud que un criterio de información que una medida del error medio. Pero lo cierto es que no lo sabemos, no tenemos ni idea de la distancia que hay entre lo óptimo y lo sub-óptimo, y si el coste de equivocarme en las predicciones es alto, puede que incluso una pequeña diferencia sea relevante.</p>
<p>Esta reflexión realizada en el contexto de series temporales y para la función <code>ets</code> es aplicable a todos los casos donde dejamos que un algoritmo ya programado elija el mejor modelo, y se basa en el hecho de que rara vez los criterios de estimación y elección que usan los algoritmos coinciden con el concepto de calidad de ajuste que estamos interesados</p>
<p>A pesar de lo aquí expuesto, como es más cómodo (y rápido) tirar de rutinas ya programadas que escribir tu propio código, seguiremos trabajando con modelos sub-óptimos y obteniendo estimaciones sub-óptimas, pero diciendo que son las mejores.</p>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="residuo-de-un-modelo" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Residuo de un modelo</h1>
<p>Todo modelo estimado con una función de <code>R</code> tiene asociado un residuo que podemos <em>extraer</em> con la función <code>residuals</code>. En los modelos más sencillos este error se define de la forma usual, <span class="math inline">\(\widehat{\varepsilon}_t = y_t - \widehat{y}_t\)</span>, pero no siempre es así. Veamos algunas excepciones y como proceder.</p>
<p><br>
</p>
<p><strong>Residuo aditivo versus residuo multiplicativo</strong></p>
<p>En los modelos de alisado estimados por la función <code>ets</code> la fórmula para el cálculo del residuo estimado depende de su naturaleza aditiva o multiplicativa.</p>
<p>Si el <strong>residuo es aditivo</strong>, entonces el modelo es <span class="math inline">\(y_t = \widehat{y}_t + \widehat{\varepsilon}_t\)</span> y el residuo se define de la forma usual <span class="math display">\[\widehat{\varepsilon}_t = y_t - \widehat{y}_t.\]</span></p>
<p>Ahora bien, si el <strong>residuo es multiplicativo</strong>, entonces el modelo es <span class="math inline">\(y_t = \widehat{y}_t \cdot (1 + \widehat{\varepsilon}_t)\)</span>, y no <span class="math inline">\(y_t = \widehat{y}_t \cdot \widehat{\varepsilon}_t\)</span> como se podría esperar. Por tanto, el residuo multiplicativo se define como <span class="math display">\[\widehat{\varepsilon}_t = (y_t - \widehat{y}_t)/\widehat{y}_t.\]</span></p>
<p>De esta forma en ambos casos –aditivo y multiplicativo– el residuo evoluciona alrededor del valor 0 y se le pueden imponer las hipótesis usuales de ruido blanco. Nota que el error aditivo tampoco es el error porcentual tal y como se define para el calculo del MPE o del MAPE.</p>
<p>Si hemos estimado con la función <code>ets</code> un modelo con residuo multiplicativo y extraemos el residuo con la función <code>residuals</code> se usará la fórmula previamente indicada. Si se desea obtener el residuo aditivo, se debe usar la función <code>residuals</code> con el argumento <code>type = "response"</code>.</p>
<p><strong>Residuo de un modelo logarítmico</strong></p>
<p>Si tenemos una serie <span class="math inline">\(y_t\)</span>, pero el modelo se ha obtenido sobre su transformación logarítmica <span class="math inline">\(z_t = \log(y_t)\)</span>, el residuo (que siempre será aditivo) que obtendremos por defecto es <span class="math display">\[\widehat{\varepsilon}_t = z_t - \widehat{z}_t.\]</span></p>
<p>Si se desea obtener el error sobre la serie original, es decir <span class="math inline">\(\widehat{\varepsilon}_t = y_t - \widehat{y}_t\)</span>, de nuevo hay que usar la función <code>residuals</code> con el argumento <code>type = "response"</code>.</p>
<p><br>
<br>
</p>
</section>
<section id="ejemplos-de-aplicación" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Ejemplos de aplicación</h1>
<p><br>
</p>
<section id="libros" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="libros"><span class="header-section-number">11.1</span> Libros</h2>
<section id="identificación-y-estimación-del-mejor-modelo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-del-mejor-modelo">Identificación y estimación del mejor modelo</h3>
<p>Si estimamos el mejor modelo de alisado exponencial para la serie Libros sin ningún tipo de restricción, nos encontramos:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>librosEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(libros)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(librosEts) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(M,N,N) 

Call:
 ets(y = libros) 

  Smoothing parameters:
    alpha = 0.9999 

  Initial states:
    l = 40459.0122 

  sigma:  0.0902

     AIC     AICc      BIC 
557.0738 558.1173 560.9613 

Training set error measures:
                   ME     RMSE      MAE      MPE     MAPE      MASE        ACF1
Training set 877.6729 5798.394 4367.896 1.318359 6.900756 0.9654123 -0.03788908</code></pre>
</div>
</div>
<p>El modelo estimado es ETS(M,N,N) o “MNN”, un modelo sin pendiente ni estacionalidad y con error multiplicativo. Es decir, <span class="math inline">\(y_{t+1} = l_t \cdot (1 + \varepsilon_{t+1})\)</span>.</p>
<p>El valor de <span class="math inline">\(\alpha\)</span> técnicamente es 1, indicando que el nivel de la serie varia en el tiempo y que realmente estamos usando para las previsiones el método ingenuo I.</p>
<p>Respecto de la calidad del modelo, el valor de MAPE= <span class="math inline">\(6.9\)</span>% evidencia que estamos ante un modelo que se ajusta moderadamente bien a los datos. MASE= <span class="math inline">\(0.97\)</span> indica que el modelo de alisado exponencial simple reduce en solo un <span class="math inline">\(3\)</span>% el error del método ingenuo I. Además, el modelo estimado presenta un marcado sesgo positivo, las predicciones en promedio son menores que los valores reales.</p>
</section>
<section id="predicción" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción">Predicción</h3>
<p>Mediante la función <code>forecast</code> podemos predecir los casos de Libros. Por tratarse de un modelo sin pendiente ni estacionalidad, la predicción es constante en el tiempo (véase <a href="#fig-librosETSLibre">Figura&nbsp;7</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>librosEtsPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(librosEts, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">h =</span> <span class="dv">5</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>librosEtsPre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020        64153.8 52808.97 75498.64
2021        64153.8 48077.97 80229.63
2022        64153.8 44425.26 83882.34
2023        64153.8 41327.01 86980.59
2024        64153.8 38580.71 89726.89</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(librosEtsPre,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-librosETSLibre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-librosETSLibre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;7: Libros y predicción a 5 años vista</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-del-residuo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="análisis-del-residuo">Análisis del residuo</h3>
<p>El error de un modelo de alisado <em>contiene</em> la componente de <strong>Intervención</strong> y el propio término de <strong>Error</strong>. Ver numérica o gráficamente el error permite identificar fácilmente la presencia de valores atípicos (intervención). Obtenemos el error con la función <code>residuals</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(librosEts)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Periodo"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span> ,<span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1993</span>, <span class="dv">2019</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-librosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-librosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-librosError">Figura&nbsp;8</a> muestra que aunque algún error supera las dos desviaciones típicas, ninguno puede ser considerado claramente como atípico.</p>
</section>
<section id="validación-error-extra-muestral-a-varios-periodos-vista" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-error-extra-muestral-a-varios-periodos-vista">Validación: error extra-muestral a varios periodos vista</h3>
<p>Vamos a mejorar la estimación de la calidad de las predicciones obteniendo el MAPE para <strong>previsiones extra-muestrales a varios periodos vista</strong>. Para ello vamos a reservar, por ejemplo, las últimas 6 observaciones de la serie Libros y ajustar el modelo con las restantes. Después usaremos este modelo para calcular las predicciones a 6 periodos vista y compararlas con los valores reales de la serie Libros.</p>
<p>Recuerda, este método para valorar la calidad de las predicciones usa la filosofía del método <em>training set/test set</em>: el periodo de datos usado en la estimación no se usa como periodo de datos para la validación. Sin embargo, tiene el problema de que el error obtenido es una mezcla de errores de predicción a corto, medio y largo plazo difícil de valorar. Además, los resultados dependen tremendamente del punto de corte temporal seleccionado.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos las observaciones intra- y extra-muestrales</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>librosIntra <span class="ot">&lt;-</span> <span class="fu">subset</span>(libros, <span class="at">end =</span> <span class="fu">length</span>(libros) <span class="sc">-</span> <span class="dv">6</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>librosExtra <span class="ot">&lt;-</span> <span class="fu">subset</span>(libros, <span class="at">start =</span> <span class="fu">length</span>(libros) <span class="sc">-</span> <span class="dv">5</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimamos el modelo con todos los datos menos los 6 ultimos</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>librosIntraEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(librosIntra, <span class="at">model =</span> <span class="st">"MNN"</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Predecimos los 6 años que hemos quitado de la serie y </span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co"># vemos la calidad del ajuste.</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>librosExtraPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(librosIntraEts, <span class="at">h =</span> <span class="dv">6</span>)</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(librosExtraPre, librosExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE      MPE     MAPE      MASE
Training set  764.4434 6445.919 5075.985 1.116656 7.994644 0.9557225
Test set     4084.3395 4786.634 4219.782 6.586626 6.828358 0.7945138
                    ACF1 Theil's U
Training set -0.04292193        NA
Test set      0.08397051  1.881683</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">

</div>
<p>Atendiendo al MAPE se tiene que el error de <strong>previsión a un periodo vista</strong> en el <strong>periodo intra-muestral</strong> de <strong>1993 a 2013</strong> es del 8%; y el error de <strong>previsión a largo plazo</strong> en el <strong>periodo extra-muestral</strong> de <strong>2014 a 2019</strong> es del 6.8%. Sin embargo, para el periodo extra-muestral el error medio (ME) es muy elevado, un indicativo de que las previsiones están segadas. Para el punto de corte elegido, la calidad de las previsiones no se deteriora cuanto nos salimos de las condiciones óptimas.</p>
<p>Un gráfico puede ayudar a entender este proceso de validación. En la <a href="#fig-librosTSTS">Figura&nbsp;9</a>:</p>
<ul>
<li>La línea de puntos vertical separa el periodo muestral (1993-2013) usado para estimar el modelo, del periodo extra-muestral (2014-2019) usado sólo para hacer las previsiones.</li>
<li>La serie Libros aparece como una línea sólida en negro, desde 1993 hasta 2019.</li>
<li>La previsión <em>intra</em>-muestral (a un periodo vista) de la serie Libros aparece como una línea azul. Observa la previsión puede ser mayor o menor que la serie, no evidenciándose sesgo.</li>
<li>La línea en rojo es la previsión <em>extra</em>-muestral a largo plazo: <span class="math inline">\(\hat{y}_{T+h}=l_T\)</span>, donde <span class="math inline">\(T=2013\)</span>. Observa que todas las previsiones están por debajo del valor real de la serie: la previsión extra-muestral está sesgada.</li>
<li>Al lado de cada previsión se ha indicado el error estimado (MAPE). Para la previsión extra-muestral, el error es la media de errores muy bajos (primeras previsiones) y errores muy elevados (últimas previsiones).</li>
</ul>
<p>Claramente estos resultados dependen del punto de corte seleccionado.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-librosTSTS" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-librosTSTS-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;9: Libros, predicción intra- y extra-muestral</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><strong>Nota:</strong> La presencia de tendencia, primero creciente y luego decreciente, en la serie Libros puede hacernos pensar que un modelo más adecuado para su ajuste y predicción sería ETS(M,A,N), forzando a que haya pendiente. De hecho, el error de estimación de este modelo es del 6.1%, frente al 7% para el modelo ETS(M,N,N). Sin embargo, el error de previsión extra-muestral a largo plazo para el modelo ETS(M,A,N) es del 12.1%, frente al 6.8% para el modelo ETS(M,N,N). <strong>Mejor ajuste no implica mejor predicción.</strong> De nuevo, incidir en que claramente estos resultados dependen del punto de corte seleccionado.</p>
<p><br>
</p>
</section>
</section>
<section id="nacimientos" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="nacimientos"><span class="header-section-number">11.2</span> Nacimientos</h2>
<p>Veamos un segundo ejemplo con la serie Nacimientos (desde el año 2000).</p>
<section id="identificación-y-estimación-del-mejor-modelo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-del-mejor-modelo-1">Identificación y estimación del mejor modelo</h3>
<p>Si damos total libertad al proceso de selección del mejor modelo, el modelo estimado es ETS(M,A,A), es decir, <span class="math inline">\(y_{t+1} = (l_t + b_t + s_{t+1-m}) \cdot (1+ \varepsilon_{t+1})\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>nacimientosEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(nacimientosb, <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nacimientosEts) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(M,A,A) 

Call:
 ets(y = nacimientosb, damped = FALSE) 

  Smoothing parameters:
    alpha = 0.4474 
    beta  = 0.0128 
    gamma = 0.0001 

  Initial states:
    l = 33059.0092 
    b = 133.8769 
    s = 182.5531 -22.7455 1980.873 1425.817 900.8348 1155.648
           -1072.562 328.585 -1319.188 -230.6447 -3327.042 -2.1282

  sigma:  0.0222

     AIC     AICc      BIC 
4548.513 4551.270 4607.684 

Training set error measures:
                    ME    RMSE     MAE        MPE     MAPE      MASE
Training set -75.41839 803.969 635.127 -0.2331352 1.729529 0.4578664
                    ACF1
Training set -0.01404832</code></pre>
</div>
</div>
<p>El bajo valor de <span class="math inline">\(\beta\)</span> y <span class="math inline">\(\gamma\)</span> indican que ambas, la pendiente y la estacionalidad, varían muy lentamente en el tiempo (véase la <a href="#fig-nacimientoscomponentes">Figura&nbsp;10</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientosEts,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Periodo"</span>,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientoscomponentes" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-nacimientoscomponentes-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;10: Componentes del modelo óptimo para Nacimientos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Respecto de la calidad del modelo, el MAPE de 1.7% indica que estamos ante un modelo que se ajusta muy bien a los datos; y el valor de MASE igual a 0.46 indica que este modelo reduce en un 54% el error del método ingenuo con estacionalidad, el más sencillo posible.</p>
<p>Podemos ver los últimos valores estimados del nivel, la pendiente y la estacionalidad para interpretarlos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(nacimientosEts<span class="sc">$</span>states)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>nacimientosEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           l            b           s1           s2           s3           s4 
29320.777216   -97.750950   182.341671   -22.911478  1980.732161  1425.627100 
          s5           s6           s7           s8           s9          s10 
  900.711756  1155.516255 -1072.778571   328.464694 -1319.322763  -230.718073 
         s11          s12 
-3327.380739    -2.092064 </code></pre>
</div>
</div>
<p>Febrero es el mes con menor número de nacimientos: nacen 3327 bebés menos, respecto de la media anual. En octubre es cuando más bebés nacen: 1980 más que la media anual.</p>
<p>Podemos usar estos valores para predecir un año,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">*</span> nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">2</span>] <span class="sc">+</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  nacimientosEts<span class="sc">$</span>states[TT, <span class="dv">14</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     s12      s11      s10       s9       s8       s7       s6       s5 
29220.93 25797.89 28796.81 27610.45 29160.49 27661.49 29792.04 29439.48 
      s4       s3       s2       s1 
29866.65 30324.00 28222.61 28330.11 </code></pre>
</div>
</div>
<p>Nuestra predicción para enero de 2020 es de 29221 bebés y para diciembre de 2020 de 28330 bebés.</p>
</section>
<section id="predicción-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-1">Predicción</h3>
<p>Si pedimos los valores de predicción tenemos (sólo se muestran los primeros meses):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>nacimientosEtsPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nacimientosEts, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h =</span> <span class="dv">24</span>, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>nacimientosEtsPre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2020       29220.93 27947.01 30494.86
Feb 2020       25797.89 24529.51 27066.28
Mar 2020       28796.81 27311.06 30282.55
Apr 2020       27610.45 26045.43 29175.48
May 2020       29160.49 27434.66 30886.32</code></pre>
</div>
</div>
<p>La <a href="#fig-nacimientosPrediccion">Figura&nbsp;11</a> muestra la serie Nacimientos, su predicción a dos años vista y el intervalo de confianza.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientosEtsPre,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientosPrediccion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-nacimientosPrediccion-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;11: Nacimientos y predicción</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-del-error" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="análisis-del-error">Análisis del error</h3>
<p>Se identifica un valor claramente atípico –supera las 4 desviaciones típicas– que corresponde a enero de 2011. Abril de 2008 y Junio de 2016 son otros candidatos a intervención por superar las 2.5 desviaciones típicas.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nacimientosEts)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Periodo"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span> ,<span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2019</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacimientosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-NacimientosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;12: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="validación-error-extra-muestral-según-horizonte-temporal" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-error-extra-muestral-según-horizonte-temporal">Validación: error extra-muestral según horizonte temporal</h3>
<p>En este ejemplo calcularemos el error extra-muestral según el horizonte temporal de previsión, una metodología que ya hemos visto anteriormente.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">120</span>                 </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span>                  </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">length</span>(nacimientosb)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> TT <span class="sc">-</span> k <span class="sc">-</span> h </span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>mapeAlisado <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacimientosb, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(nacimientosb, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h)</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">ets</span>(train.set, <span class="at">model =</span> <span class="st">"MAA"</span>, <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  fcast<span class="ot">&lt;-</span><span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>  mapeAlisado[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>errorAlisado <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeAlisado)</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>errorAlisado</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.895690 2.132387 2.242887 2.585539 2.558460 2.566431 2.776798 2.744558
 [9] 2.832179 2.999329 3.016310 3.250591</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> errorAlisado)) <span class="sc">+</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Horizonte temporal de predicción"</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"MAPE"</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacimientosErrorRW" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-NacimientosErrorRW-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;13: Error de predicción según horizonte temporal</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-NacimientosErrorRW">Figura&nbsp;13</a> muestra el error de previsión extra-muestral según el horizonte temporal. El error extra-muestral a un periodo vista es comparable al error intra-muestral (1.9% frente a 1.7%). Aunque el error de previsión aumenta conforme lo hace el horizonte temporal, siempre se mantiene muy bajo. Por ejemplo, en las previsiones a 12 meses vista el error es del 3.3%.</p>
</section>
</section>
<section id="demanda-eléctrica" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="demanda-eléctrica"><span class="header-section-number">11.3</span> Demanda eléctrica</h2>
<p>Consideraremos la serie de Demanda eléctrica desde el 1 de febrero hasta el 30 de mayo, 17 semanas completas de 2021.</p>
<section id="identificación-y-estimación-del-mejor-modelo-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-del-mejor-modelo-2">Identificación y estimación del mejor modelo</h3>
<p>El modelo óptimo (ANA) no presenta tendencia y tiene error y estacionalidad aditiva, es decir, <span class="math inline">\(y_{t+1} = l_t + s_{t+1-m} + \varepsilon_{t+1}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>electricidadEts <span class="ot">&lt;-</span> <span class="fu">ets</span>(electricidad)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(electricidadEts) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,N,A) 

Call:
 ets(y = electricidad) 

  Smoothing parameters:
    alpha = 0.8153 
    gamma = 0.0001 

  Initial states:
    l = 722.0988 
    s = -88.4954 -48.1336 18.9787 30.7625 35.2935 36.6034
           14.991

  sigma:  17.1482

     AIC     AICc      BIC 
1255.728 1257.765 1283.519 

Training set error measures:
                     ME     RMSE      MAE        MPE     MAPE      MASE
Training set -0.5481487 16.48698 10.17435 -0.1139339 1.549188 0.5110171
                   ACF1
Training set 0.04689494</code></pre>
</div>
</div>
<p>El valor <span class="math inline">\(\gamma = 0\)</span> indica que las estacionalidad se mantiene contante en el tiempo, mientras que el elevado valor de <span class="math inline">\(\alpha\)</span> indica que el nivel de la serie cambia de forma constante.</p>
<p>Respecto de la calidad del modelo, el MAPE de 1.5% indica que estamos ante un modelo que se ajusta muy bien a los datos; no hay sesgo (ME es casi cero); y el valor de ACF1 casi nulo indica que la fórmula usada para el cálculo del intervalo de confianza de las predicciones es válida.</p>
<p>Podemos ver los últimos valores estimados del nivel y la estacionalidad para interpretarlos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">nrow</span>(electricidadEts<span class="sc">$</span>states)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        l        s1        s2        s3        s4        s5        s6        s7 
668.91416 -88.49612 -48.13342  18.97883  30.76151  35.29273  36.60043  14.98952 </code></pre>
</div>
</div>
<p>El domingo la demanda eléctrica cae 88 GWh respecto de la media semanal. Por el contrario, el martes y el miércoles son los días de mayor demanda respecto de la media semanal: 36 GWh y 35 GWh respectivamente.</p>
<p>También podemos usarlos para predecir una semana,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>electricidadEts<span class="sc">$</span>states[TT, <span class="dv">1</span>] <span class="sc">+</span> electricidadEts<span class="sc">$</span>states[TT, <span class="dv">8</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      s7       s6       s5       s4       s3       s2       s1 
683.9037 705.5146 704.2069 699.6757 687.8930 620.7807 580.4180 </code></pre>
</div>
</div>
</section>
<section id="predicción-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-2">Predicción</h3>
<p>Si pedimos los valores de predicción para las cuatro siguientes semanas tenemos (sólo se muestran las dos primeras):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>electricidadEtsPre <span class="ot">&lt;-</span> <span class="fu">forecast</span>(electricidadEts, </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">h =</span> <span class="dv">28</span>, </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>electricidadEtsPre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
23.00000       683.9037 650.2939 717.5135
23.14286       705.5146 662.1490 748.8802
23.28571       704.2069 652.9085 755.5053
23.42857       699.6757 641.5165 757.8348
23.57143       687.8930 623.6012 752.1848
23.71429       620.7807 550.8923 690.6692
23.85714       580.4180 505.3479 655.4882
24.00000       683.9037 603.9882 763.8192
24.14286       705.5146 621.0312 789.9980
24.28571       704.2069 615.3903 793.0235
24.42857       699.6757 606.7276 792.6238
24.57143       687.8930 590.9894 784.7966
24.71429       620.7807 520.0769 721.4846
24.85714       580.4180 476.0514 684.7847</code></pre>
</div>
</div>
<p>La <a href="#fig-electricidadPrediccion">Figura&nbsp;14</a> muestra la serie Demanda eléctrica, su predicción a cuatro semanas vista y el intervalo de confianza.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(electricidadEtsPre,</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadPrediccion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-electricidadPrediccion-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;14: Demanda eléctrica y predicción</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-del-error-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="análisis-del-error-1">Análisis del error</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(electricidadEts)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Semana"</span>,</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span> ,<span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">6</span>, <span class="dv">26</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacimientosError2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-05-Tema5_files/figure-html/fig-NacimientosError2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;15: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>El la <a href="#fig-NacimientosError2">Figura&nbsp;15</a> se identifican en la semana 14 varios días atípicos –supera las 4 desviaciones típicas– que corresponden a la Semana Santa, que en 2021 fue del 28 de marzo al 4 de abril. Los dos valores mas extremos corresponden al Jueves Santo, que por ser vacacional tuvo un consumo de electricidad inferior al esperado; y el sábado siguiente donde el consumo fue superior al esperado.</p>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="otras-alternativas-para-ajustar-un-modelo-y-predecir" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Otras alternativas para ajustar un modelo y predecir</h1>
<p>A la hora de ajustar un modelo a una serie y predecir hay que ser un poco imaginativos, dedicarle tiempo y probar cosas. Por ejemplo, podríamos considerar la transformación logarítmica de la serie. O podríamos cambiar el criterio de estimación de los parámetros o el de selección del modelo óptimo.</p>
<p>Yendo un poco más lejos, para una serie mensual (como Nacimientos) dado que el valor de la serie dependerá forzosamente del número de días del mes, podríamos ajustar y predecir el valor medio de la serie por día del mes. Por ejemplo, los nacimientos medios por día: cociente entre los nacimientos de cada mes y el número de días del mes. Esta serie tendrá una componente estacional más suave, al eliminar el efecto de los meses de febrero bisiestos, y tendrá, previsiblemente, un mejor ajuste.</p>
<p>También podemos mezclar varios de los enfoques previos o ser aún más imaginativos.</p>
<p>El siguiente código muestra el MAPE (para previsiones intra-muestrales a un periodo vista) para la serie Nacimientos usando varias de estas opciones. Puedes deducir que se está haciendo en cada caso a partir del código. Sería más adecuado usar otro criterio de validación diferente, pero el objetivo de este epígrafe es recalcar que no hay que quedarse con lo inmediato (predecir una serie con las opciones por defecto de las funciones), sino probar y probar.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Serie Nacimientos</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.729529</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.735199</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.733763</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformación logarítmica</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.736988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.736988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.759407</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformación logarítmica insesgada</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.738206</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.738206</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb, </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda =</span> <span class="dv">0</span>, </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">biasadj =</span> <span class="cn">TRUE</span>,</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.760741</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nacimientos por dia</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb<span class="sc">/</span><span class="fu">monthdays</span>(nacimientosb)))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.654761</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb<span class="sc">/</span><span class="fu">monthdays</span>(nacimientosb), </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"mse"</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.651274</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">ets</span>(nacimientosb<span class="sc">/</span><span class="fu">monthdays</span>(nacimientosb), </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">opt.crit =</span> <span class="st">"amse"</span>,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">nmse =</span> <span class="dv">4</span>))[<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.66276</code></pre>
</div>
</div>
<p>La principal conclusión en este caso es que salirse de la estimación directa sobre la serie original no reduce el error significativamente. Sin embargo, cabe destacar que,</p>
<ul>
<li>El error de estimación de los nacimientos por día es menor que el error obtenido con la serie original de nacimiento. Véanse los tres últimos modelos respecto de los tres primeros.</li>
<li>Usar la transformación logarítmica (con o sin predicciones insesgadas) no mejora la capacidad predictiva del modelo. Véanse los modelos 4 a 9 respecto de los modelos 1 a 3.</li>
<li>El mejor modelo estima los nacimientos por día y estima los parámetros minimizando el error cuadrático medio (“mse”). Todo menos lo <em>directo</em>.</li>
</ul>
<p><br>
<br>
</p>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Resumen de los comandos utilizados</h1>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>ets</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Estimación de una amplia familia de métodos de alisado exponencial</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>forecast</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Obtiene la predicción de una serie a partir de un modelo estimado</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>residuals</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">Obtiene el residuo de un modelo estimado</td>
</tr>
</tbody>
</table>
<p><br>
<br>
<br>
<br>
</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Brown59" class="csl-entry" role="doc-biblioentry">
Brown, Robert Goodell. 1959. <em>Statistical Forecasting for Inventory Control</em>. McGraw-Hill, New York.
</div>
<div id="ref-Gardner85" class="csl-entry" role="doc-biblioentry">
Everette S. Gardner, Jr., and Ed. Mckenzie. 1985. <span>“Forecasting Trends in Time Series.”</span> <em>Management Science</em> 31 (10): 1237–46. <a href="https://doi.org/10.1287/mnsc.31.10.1237">https://doi.org/10.1287/mnsc.31.10.1237</a>.
</div>
<div id="ref-Holt" class="csl-entry" role="doc-biblioentry">
Holt, Charles C. 2004. <span>“Forecasting Seasonals and Trends by Exponentially Weighted Moving Averages.”</span> <em>International Journal of Forecasting</em> 20 (1): 5–10. https://doi.org/<a href="https://doi.org/10.1016/j.ijforecast.2003.09.015">https://doi.org/10.1016/j.ijforecast.2003.09.015</a>.
</div>
<div id="ref-Hyndman08" class="csl-entry" role="doc-biblioentry">
Hyndman, Rob J., and Yeasmin Khandakar. 2008. <span>“Automatic Time Series Forecasting: The Forecast Package for r.”</span> <em>Journal of Statistical Software</em> 27 (3): 1–22. <a href="https://doi.org/10.18637/jss.v027.i03">https://doi.org/10.18637/jss.v027.i03</a>.
</div>
<div id="ref-Hyndman08b" class="csl-entry" role="doc-biblioentry">
Hyndman, Rob J., A. Koehler, K. Ord, and R. Snyder. 2008. <em>Forecasting with Exponential Smoothings. The State Space Approach</em>. Springer Berlin, Heidelberg. <a href="https://doi.org/10.1007/978-3-540-71918-2">https://doi.org/10.1007/978-3-540-71918-2</a>.
</div>
<div id="ref-Winters60" class="csl-entry" role="doc-biblioentry">
Winters, Peter R. 1960. <span>“Forecasting Sales by Exponentially Weighted Moving Averages.”</span> <em>Management Science</em> 6 (3): 324–42. <a href="https://doi.org/10.1287/mnsc.6.3.324">https://doi.org/10.1287/mnsc.6.3.324</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Formalmente en el modelo de Holt-Winters multiplicativo el error es aditivo. Es decir, debería ser <code>model = "AAM"</code>. Este modelo se puede estimar mediante la función <code>hw</code> que replica fielmente el modelo definido en su momento por Holt y Winters. Sin embargo, al usar la función <code>ets</code>, que posibilita el cálculo de intervalos de confianza para las predicciones, no es factible estimar un modelo con estacionalidad multiplicativa y error aditivo. Por este motivo se fija <code>model = "MAM"</code>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Una forma sencilla de identificar donde están los valores atípicos es mediante el comando <code>abs(error) &gt; 3 * sderror</code> que devuelve una tabla de FALSE y TRUE, donde TRUE identifica las fechas de los errores que superan las 3 desviaciones típicas. El comando <code>time(error)[abs(error) &gt; 3 * sderror]</code> devuelve solo las fechas asociadas a errores atípicos. El valor de 3 es uno de los posibles y debe ajustarse a las características de la serie y el análisis.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2022, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.e</a></div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>