<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Métodos sencillos de predicción. Evaluación de predicciones</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Inicio</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html">Guía del curso</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html">Logística</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">Diapos</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: Media móvil</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html">
 <span class="dropdown-text">Tema 6: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html">
 <span class="dropdown-text">Tema 7: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-12-Ejemplo6.html">
 <span class="dropdown-text">Ejemplo Tema 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo7.html">
 <span class="dropdown-text">Ejemplo Tema 7</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">Píldoras</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Pasajeros.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html">Recursos de la asignatura</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html">Evaluacion Continua</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">Más</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="toc-section-number">1</span>  Introducción</a></li>
  <li><a href="#criterios-de-calidad" id="toc-criterios-de-calidad" class="nav-link" data-scroll-target="#criterios-de-calidad"><span class="toc-section-number">2</span>  Criterios de calidad</a>
  <ul class="collapse">
  <li><a href="#notación-y-definiciones" id="toc-notación-y-definiciones" class="nav-link" data-scroll-target="#notación-y-definiciones"><span class="toc-section-number">2.1</span>  Notación y definiciones</a></li>
  <li><a href="#medidas-de-precisión-de-la-predicción" id="toc-medidas-de-precisión-de-la-predicción" class="nav-link" data-scroll-target="#medidas-de-precisión-de-la-predicción"><span class="toc-section-number">2.2</span>  Medidas de precisión de la predicción</a></li>
  </ul></li>
  <li><a href="#métodos-sencillos-de-predicción" id="toc-métodos-sencillos-de-predicción" class="nav-link" data-scroll-target="#métodos-sencillos-de-predicción"><span class="toc-section-number">3</span>  Métodos sencillos de predicción</a>
  <ul class="collapse">
  <li><a href="#métodos-sencillos-de-predicción-1" id="toc-métodos-sencillos-de-predicción-1" class="nav-link" data-scroll-target="#métodos-sencillos-de-predicción-1"><span class="toc-section-number">3.1</span>  Métodos sencillos de predicción</a>
  <ul class="collapse">
  <li><a href="#series-sin-tendencia-y-sin-estacionalidad" id="toc-series-sin-tendencia-y-sin-estacionalidad" class="nav-link" data-scroll-target="#series-sin-tendencia-y-sin-estacionalidad">Series <em>sin</em> tendencia y <em>sin</em> estacionalidad</a></li>
  <li><a href="#series-con-tendencia-y-sin-estacionalidad" id="toc-series-con-tendencia-y-sin-estacionalidad" class="nav-link" data-scroll-target="#series-con-tendencia-y-sin-estacionalidad">Series <em>con</em> tendencia y <em>sin</em> estacionalidad</a></li>
  <li><a href="#series-sin-tendencia-y-con-estacionalidad" id="toc-series-sin-tendencia-y-con-estacionalidad" class="nav-link" data-scroll-target="#series-sin-tendencia-y-con-estacionalidad">Series <em>sin</em> tendencia y <em>con</em> estacionalidad</a></li>
  </ul></li>
  <li><a href="#ejemplo-de-aplicación" id="toc-ejemplo-de-aplicación" class="nav-link" data-scroll-target="#ejemplo-de-aplicación"><span class="toc-section-number">3.2</span>  Ejemplo de aplicación</a>
  <ul class="collapse">
  <li><a href="#serie-libros" id="toc-serie-libros" class="nav-link" data-scroll-target="#serie-libros">Serie Libros</a></li>
  <li><a href="#serie-nacimientos" id="toc-serie-nacimientos" class="nav-link" data-scroll-target="#serie-nacimientos">Serie Nacimientos</a></li>
  <li><a href="#serie-demanda-eléctrica" id="toc-serie-demanda-eléctrica" class="nav-link" data-scroll-target="#serie-demanda-eléctrica">Serie Demanda eléctrica</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#evaluación-de-las-predicciones" id="toc-evaluación-de-las-predicciones" class="nav-link" data-scroll-target="#evaluación-de-las-predicciones"><span class="toc-section-number">4</span>  Evaluación de las predicciones</a>
  <ul class="collapse">
  <li><a href="#validación-por-la-metodología-de-training-settest-set-para-series-temporales" id="toc-validación-por-la-metodología-de-training-settest-set-para-series-temporales" class="nav-link" data-scroll-target="#validación-por-la-metodología-de-training-settest-set-para-series-temporales"><span class="toc-section-number">4.1</span>  Validación por la metodología de <em>Training set/Test set</em> para Series Temporales</a>
  <ul class="collapse">
  <li><a href="#serie-libros-1" id="toc-serie-libros-1" class="nav-link" data-scroll-target="#serie-libros-1">Serie Libros</a></li>
  <li><a href="#serie-nacimientos-1" id="toc-serie-nacimientos-1" class="nav-link" data-scroll-target="#serie-nacimientos-1">Serie Nacimientos</a></li>
  <li><a href="#serie-demanda-eléctrica-1" id="toc-serie-demanda-eléctrica-1" class="nav-link" data-scroll-target="#serie-demanda-eléctrica-1">Serie Demanda eléctrica</a></li>
  </ul></li>
  <li><a href="#validación-cruzada-para-series-temporales" id="toc-validación-cruzada-para-series-temporales" class="nav-link" data-scroll-target="#validación-cruzada-para-series-temporales"><span class="toc-section-number">4.2</span>  Validación cruzada para Series Temporales</a>
  <ul class="collapse">
  <li><a href="#ejemplo-de-aplicación-con-nacimientos" id="toc-ejemplo-de-aplicación-con-nacimientos" class="nav-link" data-scroll-target="#ejemplo-de-aplicación-con-nacimientos">Ejemplo de aplicación con Nacimientos</a></li>
  <li><a href="#ejemplo-de-aplicación-con-demanda-eléctrica" id="toc-ejemplo-de-aplicación-con-demanda-eléctrica" class="nav-link" data-scroll-target="#ejemplo-de-aplicación-con-demanda-eléctrica">Ejemplo de aplicación con Demanda eléctrica</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"><span class="toc-section-number">5</span>  Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Métodos sencillos de predicción. Evaluación de predicciones</h1>
<p class="subtitle lead">Previsión con Datos Temporales (GBIA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">

</div>
<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>En muchos casos es preciso aplicar un método de predicción rápido y sencillo:</p>
<ul>
<li>A causa del elevado número de series que tienen que ser analizadas.</li>
<li>Debido a la rapidez con que las predicciones se han de dar.</li>
</ul>
<p>Actualmente existen muchos métodos sencillos de predicción, entre los que cabe destacar dos:</p>
<ul>
<li><strong>Métodos de media móvil</strong> (Tema 4).</li>
<li><strong>Métodos de alisado exponencial</strong> (Tema 5).</li>
</ul>
<p>Estas técnicas, a pesar de su sencillez, son bastante adecuadas cuando la previsión es a corto plazo:</p>
<blockquote class="blockquote">
<p>“Statistically sophisticated or complex methods do not necessarily produce more accurate forecasts than simpler ones.” <span class="citation" data-cites="Makridakis00">Makridakis and Hibon (<a href="#ref-Makridakis00" role="doc-biblioref">2000</a>)</span></p>
</blockquote>
<p>Pero hay métodos aún más sencillos que quedan englobados bajo el paraguas de <strong>métodos sencillos</strong> que veremos en este tema.</p>
<p><br>
<br>
</p>
</section>
<section id="criterios-de-calidad" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Criterios de calidad</h1>
<p>En este tema y en los siguientes se verán diferentes métodos para predecir una serie temporal. Así, es preciso definir criterios de bondad de ajuste que permitan estimar tanto la calidad del ajuste como de las predicciones de un método.</p>
<blockquote class="blockquote">
<p>“The rankings of the performance of the various methods vary according to the accuracy measure being used.” <span class="citation" data-cites="Makridakis00">Makridakis and Hibon (<a href="#ref-Makridakis00" role="doc-biblioref">2000</a>)</span></p>
</blockquote>
<p><br>
</p>
<section id="notación-y-definiciones" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="notación-y-definiciones"><span class="header-section-number">2.1</span> Notación y definiciones</h2>
<p>Dada una serie temporal <span class="math inline">\(\{y_t\}_{t=1}^T\)</span>, se define:</p>
<ul>
<li><strong>Previsión</strong> <span class="math inline">\(h\)</span> periodos adelante, como la previsión de la serie para el periodo <span class="math inline">\(t+h\)</span> disponiendo de información hasta el periodo <span class="math inline">\(t\)</span>, y se denota por <span class="math inline">\(\hat{y}_{t+h|t}\)</span>. Por simplicidad lo escribiremos también como <span class="math inline">\(\hat{y}_{t+h}\)</span>.</li>
</ul>
<ul>
<li>Así, <span class="math inline">\(\hat{y}_{t+1|t}\)</span> es la <strong>previsión un periodo adelante</strong> o a un periodo vista. Es decir, la previsión de la serie en el periodo <span class="math inline">\(t+1\)</span> desde el periodo <span class="math inline">\(t\)</span>.</li>
</ul>
<p>Por simplicidad denotaremos a <span class="math inline">\(\hat{y}_{t+1|t}\)</span> como <span class="math inline">\(\hat{y}_{t+1}\)</span>; y como <span class="math inline">\(\hat{y}_{t}\)</span> a la previsión en <span class="math inline">\(t\)</span>, con datos hasta el periodo <span class="math inline">\(t-1\)</span> (<span class="math inline">\(\hat{y}_{t} = \hat{y}_{t|t-1}\)</span>).</p>
<p>Se define como <strong>error de previsión</strong> a un periodo vista a <span class="math display">\[\hat{e}_t=y_t-\hat{y}_t,\]</span> de forma que la serie <span class="math inline">\(\{\hat{e}_t\}_{t=1}^T\)</span> nos permitirá definir varios criterios de calidad de ajuste.</p>
<p><br>
</p>
</section>
<section id="medidas-de-precisión-de-la-predicción" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="medidas-de-precisión-de-la-predicción"><span class="header-section-number">2.2</span> Medidas de precisión de la predicción</h2>
<p>Dada una serie <span class="math inline">\(\{y_t\}_{t=1}^T\)</span>, un método de predicción y su vector de errores asociado <span class="math inline">\(\{\hat{e}_t\}_{t=1}^T\)</span>, podemos definir múltiples medidas de calidad del método de predicción que hacen referencia a la presencia de sesgo en las predicciones, la magnitud del error cometido y la calidad del intervalo de confianza de las predicciones. Las más habituales son (siglas en inglés):</p>
<ul>
<li>Error medio (ME): <span class="math inline">\(\frac{1}{T}\sum_{t=1}^T \hat{e}_t\)</span></li>
</ul>
<ul>
<li><strong>Raíz del error cuadrático medio (RMSE)</strong>: <span class="math inline">\(\sqrt{\frac{1}{T}\sum_{t=1}^T \hat{e}^2_t}\)</span></li>
</ul>
<ul>
<li>Error absoluto medio (MAE): <span class="math inline">\(\frac{1}{T}\sum_{t=1}^T |\hat{e}_t|\)</span></li>
</ul>
<ul>
<li>Error porcentual medio (MPE): <span class="math inline">\(\frac{100}{T}\sum_{t=1}^T \frac{\hat{e}_t}{y_t}\)</span></li>
</ul>
<ul>
<li><strong>Error porcentual absoluto medio (MAPE)</strong>: <span class="math inline">\(\frac{100}{T}\sum_{t=1}^T \big|\frac{\hat{e}_t}{y_t}\big|\)</span></li>
</ul>
<ul>
<li>Error porcentual absoluto medio simétrico (sMAPE): <span class="math inline">\(\frac{200}{T}\sum_{t=1}^T \Big|\frac{\hat{e}_t}{y_t + \hat{y}_t}\Big|\)</span></li>
</ul>
<ul>
<li>Error escalado absoluto medio (MASE): <span class="math inline">\(\big(\frac{1}{T}\sum_{t=1}^T |\hat{e}_t|\big)/q\)</span>, donde <span class="math inline">\(q\)</span> es el error absoluto medio para un método ingenuo de predicción: el método ingenuo I para series sin estacionalidad y el método ingenuo con estacionalidad para series con estacionalidad.</li>
</ul>
<ul>
<li>Correlación entre <span class="math inline">\(\hat{e}_t\)</span> y <span class="math inline">\(\hat{e}_{t-1}\)</span> (ACF1).</li>
</ul>
<p><br>
</p>
<p>ME y MPE permiten valorar el sesgo de las predicciones (que estas estén sistemáticamente por encima o por debajo de los valores reales).</p>
<ul>
<li>Lo esperado es un valor cercano a cero (con relación al valor medio de la serie). Valores muy alejados de cero son indicadores de sesgo de predicción.</li>
</ul>
<p>RMSE y MAE indican el error medio cometido, medido en las mismas unidades que la serie temporal.</p>
<ul>
<li>Están acotadas inferiormente por el valor óptimo de 0, pero no hay cota superior.</li>
</ul>
<p>MAPE y sMAPE indican el error porcentual medio cometido.</p>
<ul>
<li>Están acotadas inferiormente por el valor óptimo de 0%, y la cota superior natural es 100%, aunque podría sobrepasarse.</li>
<li>Si <span class="math inline">\(y_t\)</span> puede valer 0, entonces MAPE no se puede calcular. Además, MAPE penaliza más los errores negativos frente a los errores positivos. La medida de precisión sMAPE se define a fin de corregir estos problemas.</li>
</ul>
<p>MASE es la ratio entre el error del método usado y el error de un método ingenuo de predicción. Permite saber cuánto ganamos en capacidad predictiva al pasar de un método ingenuo a otro más complicado.</p>
<ul>
<li>Un valor cercano a 1 indica que el método usado no es mejor que el método ingenuo</li>
<li>Cuanto más cercano a 0, mejor es el método usado respecto del método ingenuo</li>
<li>Su complementario a 1 se puede interpretar como la tasa de mejora</li>
</ul>
<p>ACF1 permite saber si la fórmula usada para estimar el intervalo de confianza de las predicciones es válida. Lo veremos con más detalle en el tema de modelos ARIMA. Por ahora basta saber que:</p>
<ul>
<li>Un valor muy cercano a 0 indica que la fórmula es válida.</li>
<li>Valore mínimamente alejados de 0 indican que la fórmula no es válida.</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Cálculo del intervalo de confianza de las predicciones
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ve a la Píldora <em>Bootstrapping para intervalos de predicción</em> para saber más sobre las fórmulas usadas para estimar el intervalo de confianza de las predicciones y alternativas de cálculo cuando estas fórmulas no son válidas.</p>
</div>
</div>
<p>Las <em>medias</em> se pueden sustituir por <em>medianas</em>. Esto es especialmente útil cuando para algunas observaciones hay errores atípicamente altos.</p>
<p><br>
</p>
<p>Si para realizar la predicción del periodo <span class="math inline">\(t\)</span> se usa una metodología que utiliza datos incluido dicho periodo, se hablará de <strong>predicción y error intra-muestral</strong>. En caso contrario, si la predicción del periodo <span class="math inline">\(t\)</span> usa una metodología que solo necesita de datos hasta el periodo <span class="math inline">\(t-1\)</span>, se hablará de <strong>predicción y error extra-muestral</strong>.</p>
<p>Los indicadores de calidad que se basan en predicciones intra-muestrales a un periodo vista presentan dos problemas. Primero, evalúan el error de predicción a un periodo vista, cuando en muchas situaciones reales las predicciones se realizan sobre un horizonte temporal más amplio. Segundo, son errores intra-muestrales, resultantes de predecir los mismos datos que ha usado el método para calcular la predicción y, por tanto, sobrestiman la capacidad predictiva del modelo.</p>
<p>Veremos en el epígrafe 4 de este tema métodos de evaluación de la calidad de las predicciones que superan estas limitaciones.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="métodos-sencillos-de-predicción" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Métodos sencillos de predicción</h1>
<p>Algunos métodos de predicción son extremadamente sencillos y sorprendentemente eficaces. A veces son denominados métodos ingenuos. Estos métodos:</p>
<ul>
<li>posibilitan realizar predicciones prácticamente sin realizar ningún cálculo.</li>
<li>como son muy sencillos, dan las previsiones con mayor error (menos precisas). El error de un método sencillo sirve de punto de referencia (<em>benchmark</em>) para valorar la necesidad de aplicar otros métodos más complicados con el objetivo de mejorar la calidad de las predicciones.</li>
</ul>
<p>Veamos algunos métodos sencillos y sus funciones en el paquete <code>forecast</code>.</p>
<p><br>
</p>
<section id="métodos-sencillos-de-predicción-1" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="métodos-sencillos-de-predicción-1"><span class="header-section-number">3.1</span> Métodos sencillos de predicción</h2>
<section id="series-sin-tendencia-y-sin-estacionalidad" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="series-sin-tendencia-y-sin-estacionalidad">Series <em>sin</em> tendencia y <em>sin</em> estacionalidad</h3>
<p><strong>Método de la Media</strong>: <span class="math inline">\(\hat{y}_{T+h}=(y_1+\ldots,y_T)/T\)</span>.</p>
<ul>
<li>La predicción para cualquier periodo futuro es la <strong>media</strong> de las observaciones disponibles previas.</li>
<li>Función de <code>R</code>: <code>meanf(y, h)</code></li>
</ul>
<p><strong>Método ingenuo I</strong>: <span class="math inline">\(\hat{y}_{T+h}=y_T\)</span>.</p>
<ul>
<li>La predicción para cualquier periodo futuro es la <strong>última</strong> observación disponible.</li>
<li>Función de <code>R</code>: <code>naive(y, h)</code> o <code>rwf(y, h)</code> (<em>rw</em> de random walk)</li>
<li>Para series sin estacionalidad este es el método ingenuo de comparación del MASE.</li>
</ul>
</section>
<section id="series-con-tendencia-y-sin-estacionalidad" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="series-con-tendencia-y-sin-estacionalidad">Series <em>con</em> tendencia y <em>sin</em> estacionalidad</h3>
<p><strong>Método ingenuo II</strong>: <span class="math inline">\(\hat{y}_{T+h}=y_T + h(y_T-y_{T-1})\)</span>.</p>
<ul>
<li>La predicción <span class="math inline">\(h\)</span> periodos adelante es la <strong>última observación</strong> disponible más <span class="math inline">\(h\)</span> veces el <strong>último incremento</strong> observado.</li>
<li>No tiene función en <code>R</code>, pero se podría emular mediante la función <code>ets</code> (véase epígrafe de 5.5 del tema 5, Alisado exponencial de Holt).</li>
</ul>
<p><strong>Método de la deriva</strong>: <span class="math inline">\(\hat{y}_{T+h}=y_T+h\frac{y_T - y_1}{T-1}\)</span>.</p>
<ul>
<li>La predicción <span class="math inline">\(h\)</span> periodos adelante es la <strong>última observación</strong> disponible más <span class="math inline">\(h\)</span> veces el <strong>incremento medio</strong> observado.</li>
<li>Función de <code>R</code>: <code>rwf(y, h, drift = TRUE)</code></li>
</ul>
</section>
<section id="series-sin-tendencia-y-con-estacionalidad" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="series-sin-tendencia-y-con-estacionalidad">Series <em>sin</em> tendencia y <em>con</em> estacionalidad</h3>
<p><strong>Método ingenuo con estacionalidad</strong>: <span class="math inline">\(\hat{y}_{T+h}=y_{T-m(k+1)}\)</span>.</p>
<ul>
<li><span class="math inline">\(k\)</span> es la parte entera de <span class="math inline">\((h-1)/m\)</span>, es decir, el número de estaciones completas en el periodo de predicción previo al periodo <span class="math inline">\(T+h\)</span>.</li>
<li>La predicción para un periodo es la <strong>última observación disponible de la misma estación que la fecha que se desea predecir</strong>.</li>
<li>Función de <code>R</code>: <code>snaive(y, h)</code></li>
<li>Para series con estacionalidad este es el método ingenuo de comparación del MASE</li>
</ul>
<p><strong>No hay métodos sencillos cuando la serie tiene tendencia y estacionalidad</strong>, así que se suele usar el método ingenuo con estacionalidad.</p>
<p><br>
</p>
</section>
</section>
<section id="ejemplo-de-aplicación" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="ejemplo-de-aplicación"><span class="header-section-number">3.2</span> Ejemplo de aplicación</h2>
<section id="serie-libros" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-libros">Serie Libros</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/libros.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">ts</span>(libros[ ,<span class="dv">2</span>], <span class="at">start =</span> <span class="dv">1993</span>, <span class="at">frequency  =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Las siguientes salidas muestra el resultado de la aplicación de algunos de estos métodos sencillos a la serie Libros (número de títulos publicados anualmente en España desde 1993 hasta 2019), con independencia de su adecuación dadas las componentes de esta serie.</p>
<p>Los métodos de la Media e Ingenuo I realizan una predicción constante, el primero la media de títulos en el periodo de análisis (61873) y el segundo el último dato observado (64154). El método de deriva ofrece una predicción creciente porque la serie Libros tiene una pendiente media positiva en el periodo de análisis.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(mediaLibros <span class="ot">&lt;-</span> <span class="fu">meanf</span>(libros, <span class="at">h =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 80    Hi 80    Lo 95   Hi 95
2020       61873.93 47672.32 76075.53 39674.35 84073.5
2021       61873.93 47672.32 76075.53 39674.35 84073.5
2022       61873.93 47672.32 76075.53 39674.35 84073.5
2023       61873.93 47672.32 76075.53 39674.35 84073.5
2024       61873.93 47672.32 76075.53 39674.35 84073.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(naiveLibros <span class="ot">&lt;-</span> <span class="fu">naive</span>(libros, <span class="at">h =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
2020          64154 56581.87 71726.13 52573.42 75734.58
2021          64154 53445.39 74862.61 47776.59 80531.41
2022          64154 51038.68 77269.32 44095.85 84212.15
2023          64154 49009.73 79298.27 40992.84 87315.16
2024          64154 47222.19 81085.81 38259.04 90048.96</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>(derivaLibros <span class="ot">&lt;-</span> <span class="fu">rwf</span>(libros,  <span class="at">h =</span> <span class="dv">5</span>, <span class="at">drift =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
2020       65053.85 57421.83 72685.86 53381.69 76726.00
2021       65953.69 54954.79 76952.60 49132.32 82775.06
2022       66853.54 53135.50 80571.58 45873.60 87833.47
2023       67753.38 51632.77 83874.00 43099.04 92407.73
2024       68653.23 50321.73 86984.74 40617.61 96688.85</code></pre>
</div>
</div>
<p>En la <a href="#fig-librossencillos">Figura&nbsp;1</a> muestra el resultado gráfico de la aplicación de estos métodos. Se ha fijado un horizonte de previsión de cinco años (<code>h = 5</code>). El argumento <code>PI = FALSE</code> hace que no se impriman los intervalos de confianza de las predicciones.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(libros, <span class="at">series =</span> <span class="st">"Libros"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autolayer</span>(mediaLibros, <span class="at">series=</span><span class="st">"Media"</span>, <span class="at">PI =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autolayer</span>(naiveLibros, <span class="at">series=</span><span class="st">"Ingenuo"</span>, <span class="at">PI =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autolayer</span>(derivaLibros, <span class="at">series=</span><span class="st">"Deriva"</span>, <span class="at">PI =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_discrete</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="st">"Libros"</span>, <span class="st">"Media"</span>, <span class="st">"Ingenuo"</span>, <span class="st">"Deriva"</span>)) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">"Métodos"</span>)) <span class="sc">+</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="fu">c</span>(<span class="fl">0.02</span>,<span class="fl">0.98</span>), <span class="at">legend.justification=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-librossencillos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-03-Tema3_files/figure-html/fig-librossencillos-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;1: Libros y predicción por métodos sencillos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Con la función <code>accuracy</code> se puede obtener el error de predicción intra-muestral a un periodo vista de cada método:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(mediaLibros)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(naiveLibros)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(derivaLibros)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              ME     RMSE     MAE   MPE  MAPE MASE  ACF1
Media       0.00 10407.07 7938.30 -3.06 13.66 1.75  0.77
Ingenuo I 899.85  5908.57 4524.38  1.34  7.14 1.00 -0.04
Deriva      0.00  5839.64 4229.65 -0.13  6.66 0.93 -0.04</code></pre>
</div>
</div>
<p>Podemos destacar que:</p>
<ul>
<li>El método de <em>Media</em> presenta una baja calidad de ajuste debido a que la serie Libros tiene tendencia (MAPE = 14%). Además, el intervalo de confianza de las predicciones no es fiable (ACF1 = 0.77).</li>
<li>El método de <em>Deriva</em> tiene la mejor calidad de ajuste, con un error porcentual del 6.7% (MAPE), y un error medio aproximado de 6000 títulos (RMSE). No presenta sesgo (ME = 0) y el intervalo de confianza de las predicciones es fiable (ACF1 = -0.04).</li>
<li>El método <em>Ingenuo I</em> tiene buena calidad de ajuste, pero las previsiones están ligeramente sesgadas (ME = 900).</li>
<li>Para series sin estacionalidad el método sencillo de comparación usado en el cálculo del MASE es el <em>Ingenuo I</em>. Es por ello que este indicador vale 1 para este método.</li>
<li>El error medio (ME) siempre será nulo para el método de la <em>Media</em> y de la <em>Deriva</em>, lo que indica que nos equivocamos tanto por exceso como por defecto. Esta es una buena propiedad, que el método <em>Ingenuo I</em> no verifica.</li>
</ul>
</section>
<section id="serie-nacimientos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-nacimientos">Serie Nacimientos</h3>
<p>Podemos usar el método ingenuo con estacionalidad con la serie Nacimientos para obtener una previsión a dos años vista. El error absoluto porcentual medio es del 3.6%. Es decir, aplicando algo tan simple como predecir el número de nacimientos para un mes como los nacimientos del mismo mes del año previo, tenemos ya un error de predicción muy bajo. La <a href="#fig-nacimientossencillo">Figura&nbsp;2</a> muestra la serie y la predicción que, debido al método usado, no incorpora la tendencia decreciente de los últimos años.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/nacimientos.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">ts</span>(nacimientos[, <span class="dv">2</span>],</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1975</span>, <span class="dv">1</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>(snaive.nacimientos <span class="ot">&lt;-</span> <span class="fu">snaive</span>(nacimientos, <span class="at">h =</span> <span class="dv">24</span>, <span class="at">level =</span> <span class="dv">95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2020          30858 27484.08 34231.92
Feb 2020          27324 23950.08 30697.92
Mar 2020          29333 25959.08 32706.92
Apr 2020          28780 25406.08 32153.92
May 2020          29732 26358.08 33105.92
Jun 2020          28475 25101.08 31848.92
Jul 2020          31329 27955.08 34702.92
Aug 2020          31134 27760.08 34507.92
Sep 2020          31083 27709.08 34456.92
Oct 2020          31896 28522.08 35269.92
Nov 2020          29610 26236.08 32983.92
Dec 2020          29193 25819.08 32566.92
Jan 2021          30858 26086.55 35629.45
Feb 2021          27324 22552.55 32095.45
Mar 2021          29333 24561.55 34104.45
Apr 2021          28780 24008.55 33551.45
May 2021          29732 24960.55 34503.45
Jun 2021          28475 23703.55 33246.45
Jul 2021          31329 26557.55 36100.45
Aug 2021          31134 26362.55 35905.45
Sep 2021          31083 26311.55 35854.45
Oct 2021          31896 27124.55 36667.45
Nov 2021          29610 24838.55 34381.45
Dec 2021          29193 24421.55 33964.45</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(snaive.nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME    RMSE      MAE       MPE     MAPE MASE      ACF1
Training set -588.3163 1721.42 1389.544 -1.512298 3.647559    1 0.7170624</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Interpretación de ACF1
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Es fiable el intervalo de confianza calculado para las predicciones?</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(snaive.nacimientos,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nacimientossencillo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-03-Tema3_files/figure-html/fig-nacimientossencillo-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: Nacimientos y predicción por el método Ingenuo con estacionalidad</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="serie-demanda-eléctrica" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-demanda-eléctrica">Serie Demanda eléctrica</h3>
<p>Podemos usar el método ingenuo con estacionalidad con la serie Demanda eléctrica, que tiene una estacionalidad de orden 7, pero no parece presentar tendencia. El error absoluto porcentual medio es del 4% o 43 GWh (RMSE), un error razonablemente reducido. Sin embargo, como ya pasaba con nacimientos, el ACF1 indica que la fórmula usada para el cálculo del intervalo de confianza de las predicciones no es válida.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Consumo electrico.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>electricidad <span class="ot">&lt;-</span> <span class="fu">ts</span>(electricidad[, <span class="dv">2</span>],</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>snaive.electricidad <span class="ot">&lt;-</span> <span class="fu">snaive</span>(electricidad, <span class="at">h =</span> <span class="dv">28</span>, <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(snaive.electricidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE        MPE     MAPE MASE      ACF1
Training set -2.117489 42.99794 27.93245 -0.4964111 4.000218    1 0.7096965</code></pre>
</div>
</div>
<p>La <a href="#fig-electricidadsencillo">Figura&nbsp;3</a> muestra la serie y la predicción a cuatro semanas vista. Debido a que la semana de referencia para predecir es la semana de Navidad, donde el consumo eléctrico es inferior al usual, las predicciones resultan ser claramente incorrectas. Este es un buen ejemplo de la diferencia entre calidad de ajuste y calidad de las predicciones.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(snaive.electricidad,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"GWh"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-electricidadsencillo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-03-Tema3_files/figure-html/fig-electricidadsencillo-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;3: Demanda eléctrica y predicción por el método Ingenuo con estacionalidad</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="evaluación-de-las-predicciones" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Evaluación de las predicciones</h1>
<p>Las medidas que hemos usado hasta ahora para valorar la calidad de las predicciones son realmente medidas de bondad de ajuste, es decir, medidas de la calidad de <strong>previsiones intra-muestrales a un periodo vista</strong>. Valoran en que medida los datos se ajustan a un patrón o modelo, pero no evalúan la calidad de la previsiones ante nuevos datos.</p>
<p>En este epígrafe vamos a ver dos metodologías que podemos usar para valorar la calidad de las <strong>previsiones extra-muestrales</strong>, que es realmente lo que nos interesa. Estas dos metodologías están relacionadas con los métodos de <em>Training set/Test set</em> y <em>Cross-validation</em> que has visto ya en el grado, pero adaptadas a datos temporales.</p>
<section id="validación-por-la-metodología-de-training-settest-set-para-series-temporales" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="validación-por-la-metodología-de-training-settest-set-para-series-temporales"><span class="header-section-number">4.1</span> Validación por la metodología de <em>Training set/Test set</em> para Series Temporales</h2>
<p>Vamos a mejorar la estimación de la calidad de las predicciones obteniendo las medidas de error para <strong>previsiones extra-muestrales a varios periodos vista</strong> usando la filosofía del método <em>training set/test set</em>. Dividimos la serie temporal <span class="math inline">\(\{y_t\}_{t=1}^T\)</span> en dos subseries. Los primeros datos <span class="math inline">\(\{y_t\}_{t=1}^{T_0}\)</span>, <span class="math inline">\(T_0 &lt; T\)</span>, se usarán para estimar el modelo; y los últimos datos <span class="math inline">\(\{y_t\}_{t={T_0+1}}^{T}\)</span> para validar el modelo.</p>
<p>Esta metodología, muy efectiva para datos de corte transversal, genera dos problemas cuando se aplica a series temporales: <em>i</em>) el error obtenido es una mezcla de errores de predicción a corto, medio y largo plazo; <em>ii</em>) los resultados dependen tremendamente del punto de corte temporal seleccionado.</p>
<section id="serie-libros-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-libros-1">Serie Libros</h3>
<p>Vamos a reservar, por ejemplo, las últimas 7 observaciones de la serie Libros (años 2013 a 2019) y ajustar el modelo con las restantes. Después usaremos este modelo para calcular las predicciones a 7 periodos vista y compararlas con los valores reales de la serie.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos las observaciones intra- y extra-muestrales</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>librosIntra <span class="ot">&lt;-</span> <span class="fu">subset</span>(libros, <span class="at">end =</span> <span class="fu">length</span>(libros) <span class="sc">-</span> <span class="dv">7</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>librosExtra <span class="ot">&lt;-</span> <span class="fu">subset</span>(libros, <span class="at">start =</span> <span class="fu">length</span>(libros) <span class="sc">-</span> <span class="dv">6</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimamos el modelo con todos los datos menos los 7 ultimos y</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># predecimos los 7 años que hemos quitado de la serie </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>librosExtraPre <span class="ot">&lt;-</span> <span class="fu">rwf</span>(librosIntra,  <span class="at">h =</span> <span class="dv">7</span>, <span class="at">drift =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Vemos la calidad del ajuste. Primero la predicción y luego los datos reales</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(librosExtraPre, librosExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE    MPE  MAPE MASE  ACF1 Theil's U
Training set      0.00  5863.85  4279.52  -0.05  6.53 0.87 -0.19        NA
Test set     -15817.32 15867.44 15817.32 -26.44 26.44 3.23 -0.21       6.4</code></pre>
</div>
</div>
<p>Atendiendo al MAPE se tiene que el error de <strong>previsión a un periodo vista</strong> en el <strong>periodo intra-muestral</strong> de <strong>1993 a 2012</strong> es del 6.5%; mientras que el error de <strong>previsión a largo plazo</strong> en el <strong>periodo extra-muestral</strong> de <strong>2014 a 2019</strong> es del 26.4%. Ademas, para el periodo extra-muestral el error medio (ME) es negativo y muy elevado, un indicativo de que las previsiones están segadas (sobrestiman la realidad). En resumen, la calidad del modelo se deteriora muy rápidamente en cuanto nos salimos de las condiciones óptimas.</p>
<p>Un gráfico puede ayudar a entender este proceso de validación. En la <a href="#fig-librostraintest">Figura&nbsp;4</a>:</p>
<ul>
<li>La línea de puntos vertical separa el periodo muestral (1993-2012) usado para estimar el modelo, del periodo extra-muestral (2013-2019) usado sólo para hacer las previsiones.</li>
<li>La serie Libros aparece como una línea sólida en negro, desde 1993 hasta 2019.</li>
<li>La previsión <em>intra</em>-muestral (a un periodo vista) de la serie Libros aparece como una línea azul.</li>
<li>La línea en rojo es la previsión <em>extra</em>-muestral a largo plazo. Observa que todas las previsiones están por encima del valor real de la serie.</li>
<li>Al lado de cada previsión (intra- y extra-muestral) se ha indicado el error estimado (MAPE).</li>
</ul>
<p>Claramente estos resultados dependen del punto de corte seleccionado.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-librostraintest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-03-Tema3_files/figure-html/fig-librostraintest-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4: Libros, predicción intra- y extra-muestral</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Importamcia del punto de corte
</div>
</div>
<div class="callout-body-container callout-body">
<p>Prueba a reservar las últimas 6 observaciones de la serie Libros y repite el análisis.</p>
</div>
</div>
</section>
<section id="serie-nacimientos-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-nacimientos-1">Serie Nacimientos</h3>
<p>Calculamos de nuevo los diferentes criterios de bondad de ajuste para valorar la calidad de las previsiones extra-muestrales a largo plazo. En este caso vamos a reservar los últimos 36 meses como periodo extra-muestral.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>nacimientosIntra <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacimientos, <span class="at">end =</span> <span class="fu">length</span>(nacimientos) <span class="sc">-</span> <span class="dv">36</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>nacimientosExtra <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacimientos, <span class="at">start =</span> <span class="fu">length</span>(nacimientos) <span class="sc">-</span> <span class="dv">35</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>nacimientosExtraPre <span class="ot">&lt;-</span> <span class="fu">snaive</span>(nacimientosIntra, <span class="at">h =</span> <span class="dv">36</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(nacimientosExtraPre, nacimientosExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                   ME    RMSE     MAE   MPE MAPE MASE ACF1 Theil's U
Training set  -529.76 1734.21 1389.62 -1.30 3.59 1.00 0.72        NA
Test set     -2926.75 3221.74 2926.75 -9.57 9.57 2.11 0.69      1.89</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nacimientostraintest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-03-Tema3_files/figure-html/fig-nacimientostraintest-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;5: Nacimientos, predicción intra- y extra-muestral</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Las previsiones extra-muestrales muestran una menor pendiente que los casos reales de nacimientos. Así, conforme se avanza en el horizonte temporal las previsiones se van alejando de la realidad y el error extra-muestral es del 9.6%, no tan reducido como el error de estimación intra-muestral (3.6%).</p>
</section>
<section id="serie-demanda-eléctrica-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="serie-demanda-eléctrica-1">Serie Demanda eléctrica</h3>
<p>Para la serie de consumo eléctrico vamos a reservar las 8 últimas semanas (56 días) como periodo extra-muestral.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>electricidadIntra <span class="ot">&lt;-</span> <span class="fu">subset</span>(electricidad, <span class="at">end =</span> <span class="fu">length</span>(electricidad) <span class="sc">-</span> <span class="dv">56</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>electricidadExtra <span class="ot">&lt;-</span> <span class="fu">subset</span>(electricidad, <span class="at">start =</span> <span class="fu">length</span>(electricidad) <span class="sc">-</span> <span class="dv">55</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>electricidadExtraPre <span class="ot">&lt;-</span> <span class="fu">snaive</span>(electricidadIntra, <span class="at">h =</span> <span class="dv">56</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(electricidadExtraPre, electricidadExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                ME  RMSE   MAE   MPE  MAPE MASE ACF1 Theil's U
Training set -1.78 39.17 25.09 -0.41  3.57 1.00 0.68        NA
Test set     59.30 86.23 73.54  7.82 10.14 2.93 0.48      1.55</code></pre>
</div>
</div>
<p>El error intra-muestral obtenido es del 3.6%, que prácticamente se triplica al obtener el error de previsión extra-muestral (10.1%). El elevado valor positivo del error medio indica que las previsiones extra-muestrales subestiman el consumo real de electricidad.</p>
<p><br>
</p>
</section>
</section>
<section id="validación-cruzada-para-series-temporales" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="validación-cruzada-para-series-temporales"><span class="header-section-number">4.2</span> Validación cruzada para Series Temporales</h2>
<p>Hemos visto dos alternativas para evaluar la calidad de un método de predicción de series temporales, uno basado en predicciones intra-muestrales a un periodo vista y otro basado en predicciones extra-muestrales a largo plazo, ambas con sus inconvenientes.</p>
<p>Veamos ahora una técnica, basada en el concepto de validación cruzada (<em>cross validation</em>) que permite obtener de forma individualizada los errores de previsión extra-muestral a un periodo vista, a dos periodos vista, etc.</p>
<p>Supongamos que para estimar el modelo se necesita un mínimo de <span class="math inline">\(k\)</span> observaciones y que se desea predecir hasta un horizonte temporal <span class="math inline">\(h\)</span>.</p>
<ul>
<li><p>Seleccionamos las observaciones <span class="math inline">\(1,2,...,k\)</span> para estimar el modelo y predecimos las observaciones desde <span class="math inline">\(k+1\)</span> hasta <span class="math inline">\(k+h\)</span>. Tenemos, por tanto, <span class="math inline">\(h\)</span> predicciones.</p></li>
<li><p>Calculamos el error de predicción para las predicciones desde <span class="math inline">\(k+1\)</span> hasta <span class="math inline">\(k+h\)</span>.</p></li>
<li><p>Repetimos este proceso desplazando el número de observaciones seleccionadas para la estimación un periodo adelante. Es decir, ahora usamos las observaciones <span class="math inline">\(2,3,...,k+1\)</span> para estimar el modelo, predecimos las observaciones desde <span class="math inline">\(k+2\)</span> hasta <span class="math inline">\(k+1+h\)</span> y calculamos el error de predicción.</p></li>
<li><p>Iteramos el proceso, desplazando cada vez las observaciones de la estimación un periodo adelante.</p></li>
<li><p>En general para <span class="math inline">\(i=0,1,...,T-k-h\)</span>, donde <span class="math inline">\(T\)</span> es el número total de observaciones:</p>
<ol type="1">
<li>Seleccionamos las observaciones <span class="math inline">\(i+1,i+2,...,i+k\)</span> para estimar el modelo.</li>
<li>Predecimos las observaciones desde <span class="math inline">\(i+k+1\)</span> hasta <span class="math inline">\(i+k+h\)</span>.</li>
<li>Calculamos el error de predicción para las observaciones desde <span class="math inline">\(i+k+1\)</span> hasta <span class="math inline">\(i+k+h\)</span>.</li>
<li>Para cada horizonte temporal de predicción se calcula la medida de error deseada.</li>
</ol></li>
</ul>
<p><br>
<br>
</p>
<div id="fig-rollingwindows" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./imagenes/RollingWindows.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;6: Descripción del proceso de origen de predicción móvil</figcaption><p></p>
</figure>
</div>
<p>Este procedimiento se denomina <strong>origen de predicción móvil</strong> (<em>rolling forecast origin</em>) o <em>rolling windows</em>.</p>
<p>Cuando se aplica esta metodología hay que tener en cuenta que los resultados pueden depender del número <span class="math inline">\(k\)</span> de datos usados para la estimación del modelo.</p>
<section id="ejemplo-de-aplicación-con-nacimientos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-de-aplicación-con-nacimientos">Ejemplo de aplicación con Nacimientos</h3>
<p>Vamos a aplicar la metodología previa a la serie anual de Nacimientos. Asumimos que se precisan veinte años para hacer una buena estimación, <span class="math inline">\(k=20\)</span>, y que el horizonte temporal es de cinco años, <span class="math inline">\(h = 5\)</span>. Como la serie es anual, usaremos el método de la deriva para predecir. La siguiente rutina permite obtener el MAPE para previsiones con un horizonte temporal desde uno a cinco años.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>nacAnual <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(nacimientos, <span class="at">FUN =</span> sum)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">20</span>                   <span class="co">#Minimo numero de datos para estimar</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">5</span>                    <span class="co">#Horizonte de las prediciciones</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">length</span>(nacAnual)    <span class="co">#Longitud serie</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> TT <span class="sc">-</span> k <span class="sc">-</span> h           <span class="co">#Total de estimaciones</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>mapeRwf <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacAnual, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(nacAnual, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">rwf</span>(train.set, <span class="at">h =</span> h, <span class="at">drift =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  mapeRwf[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>mapeRwf <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeRwf)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mapeRwf, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  4.13  8.07 12.16 16.38 20.67</code></pre>
</div>
</div>
<p>El error de previsión extra-muestral crece linealmente con el horizonte de previsión. Para el primer año el error de predicción se mantiene en un moderado 4.1%. Sin embargo, para el segundo año de predicción el MAPE salta al 8.1% y para los restantes años sigue creciendo rápidamente. Predecir usando la tendencia media solo es un buen método para predecir a un año vista.</p>
</section>
<section id="ejemplo-de-aplicación-con-demanda-eléctrica" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-de-aplicación-con-demanda-eléctrica">Ejemplo de aplicación con Demanda eléctrica</h3>
<p>Ahora aplicaremos la metodología origen de predicción móvil la serie de Demanda eléctrica. En este caso se asumirá que se precisan veinte semanas para hacer una buena estimación, <span class="math inline">\(k = 140\)</span>, y que el horizonte temporal es de 4 semanas, <span class="math inline">\(h = 28\)</span>. Como la serie tiene estacionalidad, usaremos el método ingenuo con estacionalidad para predecir. La siguiente rutina permite obtener el MAPE para previsiones con un horizonte temporal desde uno a 28 días.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">140</span>                  <span class="co">#Minimo numero de datos para estimar</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">28</span>                   <span class="co">#Horizonte de las prediciciones</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="fu">length</span>(electricidad)<span class="co">#Longitud serie</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> TT <span class="sc">-</span> k <span class="sc">-</span> h           <span class="co">#Total de estimaciones</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>mapeRwf <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(electricidad, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(electricidad, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">snaive</span>(train.set, <span class="at">h =</span> h)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  mapeRwf[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>mapeRwf <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeRwf)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mapeRwf, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.29 3.31 3.40 3.45 3.52 3.53 3.53 4.55 4.59 4.60 4.60 4.60 4.60 4.60 5.10
[16] 5.12 5.12 5.13 5.14 5.18 5.28 6.29 6.35 6.41 6.48 6.54 6.61 6.72</code></pre>
</div>
</div>
<p>El error de previsión extra-muestral crece lentamente con el horizonte de previsión. Para predicciones a un día vista el error de predicción es del 3.3%, para 14 días vista sube hasta el 4.6% y a 28 días vista alcanza el 6.7%.</p>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Resumen de los comandos utilizados</h1>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>meanf</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Predicción por media</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>naive</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Predicción por método ingenuo I</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>rwf</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Predicción por tendencia media</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>snaive</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Predicción por método ingenuo con estacionalidad</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>accuracy</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Calculo de la precisión del modelo</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>forecast</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">Predice valores extra-muestrales futuros de la serie</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>fitted</code></td>
<td style="text-align: left;">stats</td>
<td style="text-align: left;">Obtiene las predicciones a un periodo vista intra-muestrales</td>
</tr>
</tbody>
</table>
<p><br>
<br>
<br>
<br>
</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Makridakis00" class="csl-entry" role="doc-biblioentry">
Makridakis, Spyros, and Michèle Hibon. 2000. <span>“The M3-Competition: Results, Conclusions and Implications.”</span> <em>International Journal of Forecasting</em> 16 (4): 451–76. <a href="https://doi.org/10.1016/S0169-2070(00)00057-1">https://doi.org/10.1016/S0169-2070(00)00057-1</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2022, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.e</a></div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>