<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Procesos ARIMA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Inicio</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html">Guía del curso</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html">Logística</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">Diapos</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: Media móvil</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html">
 <span class="dropdown-text">Tema 6: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html">
 <span class="dropdown-text">Tema 7: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-12-Ejemplo6.html">
 <span class="dropdown-text">Ejemplo Tema 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo7.html">
 <span class="dropdown-text">Ejemplo Tema 7</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">Píldoras</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Pasajeros.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html">Recursos de la asignatura</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html">Evaluacion Continua</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">Más</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"> <span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#proceso-estocástico" id="toc-proceso-estocástico" class="nav-link" data-scroll-target="#proceso-estocástico"> <span class="header-section-number">2</span> Proceso estocástico</a>
  <ul class="collapse">
  <li><a href="#definición-e-hipótesis-sobre-el-proceso" id="toc-definición-e-hipótesis-sobre-el-proceso" class="nav-link" data-scroll-target="#definición-e-hipótesis-sobre-el-proceso"> <span class="header-section-number">2.1</span> Definición e hipótesis sobre el proceso</a></li>
  <li><a href="#proceso-estacionario" id="toc-proceso-estacionario" class="nav-link" data-scroll-target="#proceso-estacionario"> <span class="header-section-number">2.2</span> Proceso estacionario</a></li>
  <li><a href="#proceso-ergódico" id="toc-proceso-ergódico" class="nav-link" data-scroll-target="#proceso-ergódico"> <span class="header-section-number">2.3</span> Proceso ergódico</a></li>
  <li><a href="#normalidad" id="toc-normalidad" class="nav-link" data-scroll-target="#normalidad"> <span class="header-section-number">2.4</span> Normalidad</a></li>
  </ul></li>
  <li><a href="#transformaciones-de-una-serie" id="toc-transformaciones-de-una-serie" class="nav-link" data-scroll-target="#transformaciones-de-una-serie"> <span class="header-section-number">3</span> Transformaciones de una serie</a>
  <ul class="collapse">
  <li><a href="#ideas-generales" id="toc-ideas-generales" class="nav-link" data-scroll-target="#ideas-generales"> <span class="header-section-number">3.1</span> Ideas generales</a></li>
  <li><a href="#diferenciación" id="toc-diferenciación" class="nav-link" data-scroll-target="#diferenciación"> <span class="header-section-number">3.2</span> Diferenciación</a>
  <ul class="collapse">
  <li><a href="#diferenciación-regular-k1" id="toc-diferenciación-regular-k1" class="nav-link" data-scroll-target="#diferenciación-regular-k1">Diferenciación regular (<span class="math inline">\(k=1\)</span>)</a></li>
  <li><a href="#diferenciación-con-r" id="toc-diferenciación-con-r" class="nav-link" data-scroll-target="#diferenciación-con-r">Diferenciación con <code>R</code></a></li>
  <li><a href="#operador-retardo" id="toc-operador-retardo" class="nav-link" data-scroll-target="#operador-retardo">Operador Retardo</a></li>
  </ul></li>
  <li><a href="#transformación-logarítmica" id="toc-transformación-logarítmica" class="nav-link" data-scroll-target="#transformación-logarítmica"> <span class="header-section-number">3.3</span> Transformación logarítmica</a></li>
  <li><a href="#diferencia-logaritmo-y-tasa-de-variación" id="toc-diferencia-logaritmo-y-tasa-de-variación" class="nav-link" data-scroll-target="#diferencia-logaritmo-y-tasa-de-variación"> <span class="header-section-number">3.4</span> Diferencia, Logaritmo y Tasa de variación</a></li>
  </ul></li>
  <li><a href="#función-de-autocorrelación" id="toc-función-de-autocorrelación" class="nav-link" data-scroll-target="#función-de-autocorrelación"> <span class="header-section-number">4</span> Función de autocorrelación</a></li>
  <li><a href="#procesos-arima" id="toc-procesos-arima" class="nav-link" data-scroll-target="#procesos-arima"> <span class="header-section-number">5</span> Procesos ARIMA</a>
  <ul class="collapse">
  <li><a href="#procesos-autorregresivos-arp" id="toc-procesos-autorregresivos-arp" class="nav-link" data-scroll-target="#procesos-autorregresivos-arp"> <span class="header-section-number">5.1</span> Procesos autorregresivos AR(p)</a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición">Definición</a></li>
  <li><a href="#ejemplos" id="toc-ejemplos" class="nav-link" data-scroll-target="#ejemplos">Ejemplos</a></li>
  </ul></li>
  <li><a href="#procesos-en-medias-móviles-maq" id="toc-procesos-en-medias-móviles-maq" class="nav-link" data-scroll-target="#procesos-en-medias-móviles-maq"> <span class="header-section-number">5.2</span> Procesos en medias móviles MA(q)</a>
  <ul class="collapse">
  <li><a href="#definición-1" id="toc-definición-1" class="nav-link" data-scroll-target="#definición-1">Definición</a></li>
  <li><a href="#ejemplos-1" id="toc-ejemplos-1" class="nav-link" data-scroll-target="#ejemplos-1">Ejemplos</a></li>
  </ul></li>
  <li><a href="#procesos-armapq" id="toc-procesos-armapq" class="nav-link" data-scroll-target="#procesos-armapq"> <span class="header-section-number">5.3</span> Procesos ARMA(p,q)</a>
  <ul class="collapse">
  <li><a href="#definición-2" id="toc-definición-2" class="nav-link" data-scroll-target="#definición-2">Definición</a></li>
  <li><a href="#ejemplos-2" id="toc-ejemplos-2" class="nav-link" data-scroll-target="#ejemplos-2">Ejemplos</a></li>
  </ul></li>
  <li><a href="#proceso-arimapdq" id="toc-proceso-arimapdq" class="nav-link" data-scroll-target="#proceso-arimapdq"> <span class="header-section-number">5.4</span> Proceso ARIMA(p,d,q)</a>
  <ul class="collapse">
  <li><a href="#ejemplos-3" id="toc-ejemplos-3" class="nav-link" data-scroll-target="#ejemplos-3">Ejemplos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#aproximación-de-box-jenkins" id="toc-aproximación-de-box-jenkins" class="nav-link" data-scroll-target="#aproximación-de-box-jenkins"> <span class="header-section-number">6</span> Aproximación de Box-Jenkins</a>
  <ul class="collapse">
  <li><a href="#identificación-automática" id="toc-identificación-automática" class="nav-link" data-scroll-target="#identificación-automática">Identificación automática</a></li>
  </ul></li>
  <li><a href="#ejemplos-4" id="toc-ejemplos-4" class="nav-link" data-scroll-target="#ejemplos-4"> <span class="header-section-number">7</span> Ejemplos</a>
  <ul class="collapse">
  <li><a href="#títulos-de-libros-y-panfletos" id="toc-títulos-de-libros-y-panfletos" class="nav-link" data-scroll-target="#títulos-de-libros-y-panfletos"> <span class="header-section-number">7.1</span> Títulos de libros y panfletos</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie" id="toc-transformación-de-la-serie" class="nav-link" data-scroll-target="#transformación-de-la-serie">Transformación de la serie</a></li>
  <li><a href="#identificación" id="toc-identificación" class="nav-link" data-scroll-target="#identificación">Identificación</a></li>
  <li><a href="#estimación" id="toc-estimación" class="nav-link" data-scroll-target="#estimación">Estimación</a></li>
  <li><a href="#intervención" id="toc-intervención" class="nav-link" data-scroll-target="#intervención">Intervención</a></li>
  <li><a href="#medidas-de-error" id="toc-medidas-de-error" class="nav-link" data-scroll-target="#medidas-de-error">Medidas de error</a></li>
  <li><a href="#predicción" id="toc-predicción" class="nav-link" data-scroll-target="#predicción">Predicción</a></li>
  </ul></li>
  <li><a href="#aforo-de-vehículos" id="toc-aforo-de-vehículos" class="nav-link" data-scroll-target="#aforo-de-vehículos"> <span class="header-section-number">7.2</span> Aforo de vehículos</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-1" id="toc-transformación-de-la-serie-1" class="nav-link" data-scroll-target="#transformación-de-la-serie-1">Transformación de la serie</a></li>
  <li><a href="#identificación-y-estimación" id="toc-identificación-y-estimación" class="nav-link" data-scroll-target="#identificación-y-estimación">Identificación y Estimación</a></li>
  <li><a href="#validación" id="toc-validación" class="nav-link" data-scroll-target="#validación">Validación</a></li>
  <li><a href="#medidas-de-error-1" id="toc-medidas-de-error-1" class="nav-link" data-scroll-target="#medidas-de-error-1">Medidas de error</a></li>
  <li><a href="#interpretación-del-modelo" id="toc-interpretación-del-modelo" class="nav-link" data-scroll-target="#interpretación-del-modelo">Interpretación del modelo</a></li>
  <li><a href="#predicción-1" id="toc-predicción-1" class="nav-link" data-scroll-target="#predicción-1">Predicción</a></li>
  <li><a href="#validación-con-origen-de-predicción-móvil" id="toc-validación-con-origen-de-predicción-móvil" class="nav-link" data-scroll-target="#validación-con-origen-de-predicción-móvil">Validación con origen de predicción móvil</a></li>
  </ul></li>
  <li><a href="#consumo-de-alimentos-en-el-hogar-per-cápita" id="toc-consumo-de-alimentos-en-el-hogar-per-cápita" class="nav-link" data-scroll-target="#consumo-de-alimentos-en-el-hogar-per-cápita"> <span class="header-section-number">7.3</span> Consumo de alimentos en el hogar per cápita</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-2" id="toc-transformación-de-la-serie-2" class="nav-link" data-scroll-target="#transformación-de-la-serie-2">Transformación de la serie</a></li>
  <li><a href="#identificación-y-estimación-1" id="toc-identificación-y-estimación-1" class="nav-link" data-scroll-target="#identificación-y-estimación-1">Identificación y Estimación</a></li>
  <li><a href="#validación-1" id="toc-validación-1" class="nav-link" data-scroll-target="#validación-1">Validación</a></li>
  <li><a href="#medidas-de-error-2" id="toc-medidas-de-error-2" class="nav-link" data-scroll-target="#medidas-de-error-2">Medidas de error</a></li>
  <li><a href="#interpretación-del-modelo-1" id="toc-interpretación-del-modelo-1" class="nav-link" data-scroll-target="#interpretación-del-modelo-1">Interpretación del modelo</a></li>
  <li><a href="#predicciones-de-la-serie" id="toc-predicciones-de-la-serie" class="nav-link" data-scroll-target="#predicciones-de-la-serie">Predicciones de la serie</a></li>
  </ul></li>
  <li><a href="#comparación-con-alisado-exponencial" id="toc-comparación-con-alisado-exponencial" class="nav-link" data-scroll-target="#comparación-con-alisado-exponencial"> <span class="header-section-number">7.4</span> Comparación con alisado exponencial</a></li>
  </ul></li>
  <li><a href="#resumen-de-los-comandos-utilizados" id="toc-resumen-de-los-comandos-utilizados" class="nav-link" data-scroll-target="#resumen-de-los-comandos-utilizados"> <span class="header-section-number">8</span> Resumen de los comandos utilizados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Procesos ARIMA</h1>
<p class="subtitle lead">Previsión con Datos Temporales (GBIA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">

</div>
<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Los <strong>modelos ARIMA</strong> han mostrado ser uno se los métodos de ajuste de series temporales más valiosos desde que fueran formalizados en 1976 por Box y Jenkins <span class="citation" data-cites="BoxJenkins76">(<a href="#ref-BoxJenkins76" role="doc-biblioref">Box and Jenkins 1976</a>)</span>. Además, dieron las pautas a seguir en el ajuste de una serie temporal para alcanzar buenas predicciones (véase epígrafe 6).</p>
<p>En este tema y el siguiente, definiremos estos procesos y aprenderemos a identificarlos, estimarlos y hacer predicciones.</p>
<p><strong>Los procesos ARIMA son ahora el tronco de una amplia familia de procesos</strong> que requieren menos hipótesis para su aplicación o ajustan mejor bajo diferentes hipótesis: ARCH, GARCH, NGARCH, IGARCH, EGARCH, GARCH-M, QGARCH, GJR-GARCH, TGARCH, fGARCH…</p>
<p><strong>Los procesos ARIMA y los métodos de Alisado Exponencial son complementarios</strong>:</p>
<ul>
<li>Los modelos de Alisado lineales son casos especiales de modelos Arima,</li>
<li>Los modelos de Alisado no lineales no tienen su contrapartida en modelos Arima</li>
<li>Muchos modelos Arima no tiene contrapartida en los modelos de Alisado.</li>
</ul>
<p>Pero antes de entrar en materia es necesario definir una serie de conceptos que permitirán entender mejor <strong>una serie temporal como una muestra de un proceso generador de datos</strong> (PGD).</p>
<p><br>
<br>
</p>
</section>
<section id="proceso-estocástico" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Proceso estocástico</h1>
<p><br>
</p>
<section id="definición-e-hipótesis-sobre-el-proceso" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="definición-e-hipótesis-sobre-el-proceso"><span class="header-section-number">2.1</span> Definición e hipótesis sobre el proceso</h2>
<p>Un <strong>proceso estocástico</strong> <span class="math inline">\(Y_t\)</span> es (sin excesiva precisión) una variable aleatoria que corresponde a momentos sucesivos del tiempo. A diferencia de los temas previos, en este vamos a estimar modelos sobre procesos estocásticos. Sería el equivalente para series temporales al modelo de regresión lineal que viste en el primer semestre para datos transversales.</p>
<p>Al igual que en <em>Predicción con datos transversales</em>, la aplicación de estos modelos requiere del cumplimiento de una serie de hipótesis. Para el caso de series temporales el proceso debe ser <strong>estacionario</strong>, <strong>ergódico</strong> y <strong>normal</strong>. Veamos estas hipótesis con algo más de detalle.</p>
<p><br>
</p>
</section>
<section id="proceso-estacionario" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="proceso-estacionario"><span class="header-section-number">2.2</span> Proceso estacionario</h2>
<p>Un proceso es <strong>estacionario en sentido estricto</strong> cuando la distribución conjunta no varía al realizar un desplazamiento en el tiempo de todas las variables.</p>
<ul>
<li>Si <span class="math inline">\(F(Y_{t_1},..., Y_{t_k})\)</span> es la función de distribución conjunta y <span class="math inline">\(h&gt;0\)</span>, entonces el proceso es estacionario en sentido estricto si <span class="math display">\[F(Y_{t_1},..., Y_{t_k}) = F(Y_{t_1+h},..., Y_{t_k+h})\]</span></li>
</ul>
<p>Intuitivamente, <em>la distribución de un proceso estocástico es independiente del momento del tiempo</em>.</p>
<p>Comprobar si un proceso es estacionario en sentido estricto es muy difícil, así que vamos a encontrar condiciones suficientes: <em>estacionariedad en media</em> y en <em>sentido amplio</em> (covarianza). <strong>Bajo normalidad</strong> un proceso estacionario en sentido amplio también lo será en sentido estricto.</p>
<p><strong>Proceso estacionario en media</strong></p>
<p>Un proceso es estacionario en media (o de primer orden) si su nivel se mantiene en el tiempo: <span class="math display">\[E[Y_t] = \mu \; \; \forall t\]</span></p>
<p><strong>Proceso estacionario en sentido amplio</strong></p>
<p>Un proceso (ya estacionario en media) es estacionario en sentido amplio, o de segundo orden, si sus momentos de orden dos no dependen del tiempo:</p>
<ul>
<li>La (auto)covarianza entre dos periodos de tiempo es finita y sólo depende del intervalo de tiempo transcurrido entre estos dos periodos: <span class="math display">\[Cov[Y_t, Y_{t+k}] = E[(Y_t - \mu)(Y_{t+k} - \mu)] = \gamma_k,\,\,\,\forall t\]</span></li>
</ul>
<p>Observa que la varianza será entonces <span class="math inline">\(Var[Y_t] = E[(Y_t - \mu)^2] = \gamma_0\)</span>.</p>
<p><br>
</p>
<p>La <a href="#fig-Nacimientos">Figura&nbsp;1</a> muestra la serie Nacimientos que no es estacionaria ni en media, ni en varianza. No lo es en media por que presenta tendencia y, por tanto, el valor medio de la serie cambia en el tiempo; y no lo es estacionaria en varianza por que al inicio de la serie los datos presenta más variabilidad que a finales del siglo pasado.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-Nacimientos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-Nacimientos-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 1: Nacimientos mensuales</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="proceso-ergódico" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="proceso-ergódico"><span class="header-section-number">2.3</span> Proceso ergódico</h2>
<p>Para que un proceso sea ergódico las observaciones nuevas tienen que aportar suficiente información para que la varianza del valor medio converja a 0.</p>
<p>Una condición necesaria, pero no suficiente, para que un proceso estacionario sea ergódico es: <span class="math display">\[\lim_{k\rightarrow \infty} \gamma_k = 0.\]</span> Es decir, que el pasado cada vez ayuda menos a entender el presente.</p>
<p><br>
</p>
</section>
<section id="normalidad" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="normalidad"><span class="header-section-number">2.4</span> Normalidad</h2>
<p>Asumiremos que el error del modelo se distribuye como una variable aleatoria normal. Esta hipótesis se puede relajar si la serie tiene suficientes datos.</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="transformaciones-de-una-serie" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Transformaciones de una serie</h1>
<p><br>
</p>
<section id="ideas-generales" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="ideas-generales"><span class="header-section-number">3.1</span> Ideas generales</h2>
<p>Una serie temporal <span class="math inline">\(\{y_t\}_{t=1}^T\)</span> no tiene porque verificar las condiciones de estacionariedad y ergodicidad. A continuación veremos una serie de transformaciones que convierten una serie no estacionaria en estacionaria; y no ergódica en ergódica.</p>
<p>En el panel superior de la <a href="#fig-Nacimientos2">Figura&nbsp;2</a> vuelves a tener la serie de nacimientos, que denominaremos <span class="math inline">\(y_t\)</span>; en el segundo panel la diferencia de la serie, <span class="math inline">\(y_t - y_{t-1}\)</span>; y en el panel inferior tienes la diferencia de la transformación logarítmica de la serie, <span class="math inline">\(log(y_t) - log(y_{t-1})\)</span>. La serie nacimientos no es estacionaria en media ni en varianza, su diferencia es estacionaria en media, pero no en varianza. Sin embargo, la transformación logarítmica y la diferencia han logrado que sea estacionaria en ambos sentidos.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-Nacimientos2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-Nacimientos2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 2: Serie Nacimientos, su diferencia y la diferencia del logaritmo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>En este tema veremos con detalle estas dos transformaciones para series sin estacionalidad y dejaremos para el tema siguiente el caso de las series con estacionalidad.</p>
<p><br>
</p>
</section>
<section id="diferenciación" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="diferenciación"><span class="header-section-number">3.2</span> Diferenciación</h2>
<p><strong>La diferenciación permite transformar una serie no estacionaria en media en estacionaria en media</strong>.</p>
<p>Diferenciar de orden <span class="math inline">\(k\)</span> consiste en restar a la observación de un periodo la de <span class="math inline">\(k\)</span> periodos antes: <span class="math display">\[\nabla_k y_t = y_t - y_{t-k}.\]</span></p>
<section id="diferenciación-regular-k1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diferenciación-regular-k1">Diferenciación regular (<span class="math inline">\(k=1\)</span>)</h3>
<p>Un caso concreto es la <strong>diferenciación regular o diferenciación de orden uno</strong>, que consiste en restar a la observación de un periodo la del periodo precedente: <span class="math display">\[\nabla y_t = y_t - y_{t-1}.\]</span></p>
<p>Si <span class="math inline">\(\nabla y_t\)</span> no fuera estacionaria, se diferenciaría (regularmente) una segunda vez para obtener una doble diferenciación de primer orden: <span class="math display">\[\nabla^{2} y_t = \nabla(\nabla y_t) = \nabla y_t - \nabla y_{t-1} = (y_t - y_{t-1}) - (y_{t-1} - y_{t-2}) = y_t - 2y_{t-1} + y_{t-2}\]</span></p>
<p>En la práctica una sola diferenciación suele ser suficiente para obtener la estacionariedad en media; diferenciar dos veces es excepcional; y diferenciar tres o más veces no se da.</p>
<p>Existe la <strong>diferencia estacional</strong>, que consiste en restar a la observación de un periodo la observación precedente de la misma estación y que veremos en detalle en el tema 7.</p>
<p>Además, en series sin estacionalidad <strong>la diferenciación también permite alcanzar la ergodicidad</strong>.</p>
<p>La <a href="#fig-NacimientosAnual">Figura&nbsp;3</a> muestra un ejemplo de diferenciación regular. En el primer panel aparece la serie anual de Nacimientos <span class="math inline">\(y_t\)</span>; en el segundo panel se muestra la serie diferenciada regularmente una vez <span class="math inline">\(\nabla y_t\)</span>; y en el panel inferior la serie doblemente diferenciada <span class="math inline">\(\nabla^2 y_t\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-NacimientosAnual" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosAnual-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 3: Nacimientos (anual) y su primera y segunda diferencia regular</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><em>¿Qué transformación para nacimientos consideras que genera una serie estacionaria?</em> Siempre hay un cierto grado de subjetividad en la elección de las diferencias que hay que aplicar a una serie. En la <a href="#fig-NacimientosAnual">Figura&nbsp;3</a> podemos considerar que la diferenciación regular (panel medio) es suficiente para lograr la estacionariedad (en media y en varianza) y terminar el proceso de diferenciación. Pero también podemos considerar que la serie es no del todo estacionaria en media, y optar por la doble diferenciación regular (panel inferior).</p>
</section>
<section id="diferenciación-con-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diferenciación-con-r">Diferenciación con <code>R</code></h3>
<p><code>R</code> dispone de la función <code>diff</code> para diferenciar una serie:</p>
<ul>
<li><code>diff(x, lag = k)</code> calcula la diferencia de orden <span class="math inline">\(k\)</span>, <span class="math inline">\(\nabla_k y_t\)</span></li>
<li><code>diff(x)</code> calcula la diferencia regular o de orden <span class="math inline">\(1\)</span>, <span class="math inline">\(\nabla y_t\)</span></li>
<li><code>diff(x, difference = d)</code> calcula <span class="math inline">\(d\)</span> diferencias regulares, <span class="math inline">\(\nabla^d y_t\)</span></li>
</ul>
<p>Además, en <code>forecast</code> está disponible la función <code>ndiffs</code> que estima el número de diferencias regulares necesarias para que una serie sea estacionaria. Para ello usa un contraste de raíces unitarias (que no veremos en este curso).</p>
</section>
<section id="operador-retardo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="operador-retardo">Operador Retardo</h3>
<p>Definimos el <strong>operador retardo</strong> <span class="math inline">\(L\)</span> como <span class="math inline">\(Ly_t = y_{t-1}\)</span>, es decir, retrasa un periodo la serie. En inglés se denomina <em>lag operator</em> (L) o <em>backward shift</em> (B)</p>
<p>Así, se tiene que <span class="math display">\[L^k y_t = y_{t-k}\]</span> y por tanto que</p>
<p><span class="math display">\[
\begin{aligned}
  \nabla y_t &amp; =  y_t - y_{t-1} = y_t - Ly_t = (1-L)y_t \\
  \nabla^d y_t &amp; =  (1-L)^d y_t
\end{aligned}
\]</span></p>
<p>La <a href="#tbl-operadorretardo">Tabla&nbsp;1</a> muestra un sencillo ejemplo del efecto del operador retardo sobre la serie <span class="math inline">\(y_t\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-operadorretardo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabla 1: Ejemplo de aplicación del operador retardo</caption>
<thead>
<tr class="header">
<th style="text-align: right;">y</th>
<th style="text-align: right;">lag1_y</th>
<th style="text-align: right;">lag2_y</th>
<th style="text-align: right;">lag3_y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="transformación-logarítmica" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="transformación-logarítmica"><span class="header-section-number">3.3</span> Transformación logarítmica</h2>
<p>Si la serie original no es estacionaria en sentido amplio –por ejemplo porque la amplitud estacional crece con el nivel de la serie–, es posible obtener la estacionariedad por medio de transformaciones simples. La transformación logarítmica de una serie es una alternativa<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>La <a href="#fig-NacimientosLog">Figura&nbsp;4</a> muestra la serie Nacimientos y su logaritmo. La variabilidad estacional con la transformación logarítmica (panel inferior) es más constante que en la serie original (panel superior).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-NacimientosLog" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosLog-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 4: Serie Nacimientos y su transformaciones logarítmica</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Sin embargo, para series sin estacionalidad, el uso de la transformación logarítmica para alcanzar la estacionariedad en varianza es muy excepcional.</p>
<p><br>
</p>
</section>
<section id="diferencia-logaritmo-y-tasa-de-variación" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="diferencia-logaritmo-y-tasa-de-variación"><span class="header-section-number">3.4</span> Diferencia, Logaritmo y Tasa de variación</h2>
<p>La transformación <span class="math inline">\(\nabla y_t\)</span> se puede interpretar como variaciones en nivel, pero <span class="math inline">\(\nabla^2 y_t\)</span> no tiene ninguna interpretación. <strong>No conviene perder de vista la interpretabilidad de las observaciones</strong>.</p>
<p>Cuando una serie tiene que ser diferenciada dos veces para conseguir su estacionariedad, vale la pena probar una transformación alternativa que sea interpretable: <span class="math inline">\(\nabla \log(y_t)\)</span>.</p>
<p>Dado que, <span class="math display">\[\nabla \log(y_t) = \log(y_t) - \log(y_{t-1}) = \log\big(\frac{y_t}{y_{t-1}} \big)
  \approx \frac{y_t}{y_{t-1}} - 1 = \frac{y_t - y_{t-1}}{y_{t-1}} =TV y_t.\]</span></p>
<p>para una serie <em>la diferencia regular del logaritmo (natural) es la Tasa de Variación de la serie</em>, que tiene una clara interpretación como variación porcentual. Si la serie es anual, tendremos la tasa de variación anual; si es semanal, la tasa de variación semanal.</p>
<p><br>
</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
La diferenciacion y el logaritmo en series sin estacionalidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si se tiene una serie sin estacionalidad y no estacionaria, bastará diferenciarla una o, a lo sumo, dos veces para que sea estacionaria en media, en sentido amplio y ergódica.</p>
<p>La transformación logarítmica se puede usar si se desea ganar en interpretabilidad o para intentar mejorar las predicciones. La transformación logarítmica no es necesaria para alcanzar la estacionariedad de la serie.</p>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="función-de-autocorrelación" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Función de autocorrelación</h1>
<p>Si la serie es estacionaria y ergódica, el valor medio de la serie es constante y, por tanto, no informativo. <strong>Son las covarianzas los que caracterizan el proceso estocástico</strong>.</p>
<p>Recordemos que <span class="math inline">\(\gamma_k=Cov(y_t,y_{t-k})\)</span> es la autocovarianza de orden <span class="math inline">\(k\)</span>. Por tanto <span class="math inline">\(\gamma_0\)</span> es la varianza de la serie <span class="math inline">\(y_t\)</span>. Sea <span class="math inline">\(\rho_k\)</span> la autocorrelación se orden <span class="math inline">\(k\)</span>. Se puede verificar que <span class="math display">\[\rho_k = cor(y_t, y_{t-k}) =\frac{\gamma_k}{\gamma_0}.\]</span></p>
<ul>
<li><span class="math inline">\(\rho_1\)</span> mide la información que se transmite de un periodo al siguiente periodo.</li>
<li><span class="math inline">\(\rho_k\)</span> mide la información que se transmite k periodos hacia adelante.</li>
</ul>
<p>Las autocorrelaciones caracterizan el proceso estocástico, y <strong>la función de autocorrelación o correlograma (FAC, o ACF en inglés) es el gráfico de</strong> <span class="math inline">\(r_k\)</span> contra <span class="math inline">\(k\)</span>, donde <span class="math inline">\(r_k\)</span> es la estimación de <span class="math inline">\(\rho_k\)</span> obtenida con las observaciones.</p>
<p>La figura 5 muestra la FAC para la serie Nacimientos y algunas de sus transformaciones. Observa el uso del argumento <code>lag</code> que en la función <code>ggAcf</code> indica el orden máximo de la autocorrelación. La primera columna muestra la FAC para Nacimientos y varias diferenciaciones, mientras que la segunda columna muestra la FAC para el logaritmo de los nacimientos y sus diferenciaciones. Se puede observar que:</p>
<ul>
<li>La FAC de una serie y de su transformación logarítmica son muy similares.</li>
<li>En los paneles de la primera y segunda fila las autocorrelaciones decrecen lentamente, indicando que la serie analizada no es estacionaria ni ergódica.</li>
<li>Solo la doble diferenciación regular de la serie (original o su logaritmo) muestran un rápido descenso en los coeficientes de autocorrelación (paneles de la última fila), indicando que la serie así transformada es estacionaria y ergódica.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nacimientosAnual es la seria anual de Nacimientos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(nacimientosAnual, <span class="at">lag =</span> <span class="dv">10</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(nacimientosAnual), <span class="at">lag =</span> <span class="dv">10</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(nacimientosAnual), <span class="at">lag =</span> <span class="dv">10</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientosAnual)), <span class="at">lag =</span> <span class="dv">10</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(nacimientosAnual, <span class="at">differences =</span> <span class="dv">2</span>), <span class="at">lag =</span> <span class="dv">10</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientosAnual), <span class="at">differences =</span> <span class="dv">2</span>), <span class="at">lag =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-NacimientosFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(b) Logaritmo de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(c) Dif. regular de la serie</figcaption><p></p>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(d) Dif. regular del logaritmo la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-5.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(e) Doble dif. regular de la serie</figcaption><p></p>
</figure>
</div>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 10.0%;justify-content: center;">
<p>&nbsp;</p>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 45.0%;justify-content: center;">
<div id="fig-NacimientosFAC-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-NacimientosFAC-6.png" class="img-fluid figure-img" data-ref-parent="fig-NacimientosFAC"></p>
<p></p><figcaption class="figure-caption">(f) Doble dif. regular del logaritmo la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 5: FAC para Nacimientos</figcaption><p></p>
</figure>
</div>
<p>También podemos pedir <code>R</code> que nos sugiera el orden de diferenciación con la función <code>ndiffs</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(nacimientosAnual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Si queremos ver los valores numéricos de las autocorrelaciones debemos añadir a la función <code>ggAfc</code> el argumento <code>plot = FALSE</code>. Para la serie doblemente diferenciada vemos que la relación más elevada se da para el primer retardo (<span class="math inline">\(r_{1}=-0.468\)</span>), el dato que más se parece a los nacimientos de un año son los nacimientos del año previo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(nacimientosAnual, <span class="at">differences =</span> <span class="dv">2</span>), </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">lag=</span><span class="dv">10</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Autocorrelations of series 'diff(nacimientosAnual, differences = 2)', by lag

     0      1      2      3      4      5      6      7      8      9     10 
 1.000 -0.468  0.218 -0.140  0.229 -0.261  0.092 -0.102  0.148 -0.004 -0.260 </code></pre>
</div>
</div>
<p>Las bandas azules de la FAC muestran el intervalo de confianza al 95% (IC95). Si <span class="math inline">\(\rho_k = 0\)</span>, la distribución del estimador <span class="math inline">\(r_k\)</span> se distribuye aproximadamente como una normal de media <span class="math inline">\(-1/T\)</span> y varianza <span class="math inline">\(1/T\)</span>. Las líneas punteadas de la FAC están dibujadas en las posiciones <span class="math inline">\(\frac{-1}{T} \pm \frac{1.96}{\sqrt{T}}\)</span>.</p>
<ul>
<li><p>Si un <span class="math inline">\(r_k\)</span> cae fuera del IC95, hay evidencia para rechazar la hipótesis nula de que <span class="math inline">\(\rho_k = 0\)</span> a un nivel del 5%. Recordemos que incluso si todos los <span class="math inline">\(\rho_k\)</span> son cero, cabe esperar que un 5% de sus estimaciones <span class="math inline">\(r_k\)</span> caigan fuera del IC95.</p></li>
<li><p>Los <span class="math inline">\(\rho_k\)</span> no son independientes. Si uno cae fuera del IC95, es más probable que los valores vecinos caigan también fuera.</p></li>
</ul>
<p><br>
<br>
</p>
</section>
<section id="procesos-arima" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Procesos ARIMA</h1>
<p>ARIMA surge de combinar las siglas de tres procesos diferentes: <strong>AR</strong> de AutoRegresive, <strong>I</strong> de Integrated y <strong>MA</strong> de Moving Average. Veamos cada uno de estos tres conceptos por separado y luego su combinación.</p>
<p>A lo largo de lo que resta del tema asumiremos que:</p>
<ul>
<li><p><span class="math inline">\(\{y_t\}_{t=1}^T\)</span> es una realización de un proceso estocástico desconocido.</p></li>
<li><p>El proceso estocástico es <strong>estacionario en sentido amplio</strong>: $$E[y_t] = &lt; ;;; t,</p>
<p><span class="math display">\[ \]</span>Cov[y_t, y_{t-k}] = _k ;;; k.$$</p></li>
<li><p>El proceso estocástico es <strong>ergódico</strong>, o su condición suficiente: <span class="math display">\[\lim_{k \rightarrow \infty} \gamma_k  = 0.\]</span></p></li>
<li><p>El proceso se distribuye como una normal.</p></li>
</ul>
<p><br>
</p>
<section id="procesos-autorregresivos-arp" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="procesos-autorregresivos-arp"><span class="header-section-number">5.1</span> Procesos autorregresivos AR(p)</h2>
<section id="definición" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición">Definición</h3>
<p>El modelo general <strong>autorregresivo de orden p</strong>, <span class="math inline">\(y_t \sim AR(p)\)</span> viene definido por <span class="math display">\[y_t=c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \ldots + \phi_p y_{t-p} + \varepsilon_t,\]</span> que usando el operador retardo queda <span class="math display">\[(1 - \phi_1 L - \phi_2 L^2 - \ldots - \phi_p L^p)y_t = c + \varepsilon_t\]</span></p>
<p>En este y en cualquier proceso ARIMA, al polinomio en <span class="math inline">\(L\)</span> que acompaña a <span class="math inline">\(y_t\)</span> se le denomina <strong>polinomio autorregresivo</strong>.</p>
<p>Se suele asumir que el error del modelo <span class="math inline">\(\varepsilon_t\)</span> verifica las hipótesis estándar de media cero, incorrelación, homocedasticidad e idéntica distribución: <span class="math inline">\(\varepsilon_t \sim iid(0, \sigma^2)\)</span>. En este curso no vamos a prestar atención a este conjunto de hipótesis porque no jugarán ningún papel en la elección del modelo óptimo –aquel con mejores predicciones.</p>
</section>
<section id="ejemplos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim AR(1): \;\;y_t = c + \phi_1 y_{t-1} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_1 L)y_t = c + \varepsilon_t\)</span></li>
<li><span class="math inline">\(y_t \sim AR(2): \;\;y_t = c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_1 L - \phi_2 L^2)y_t = c + \varepsilon_t\)</span></li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="procesos-en-medias-móviles-maq" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="procesos-en-medias-móviles-maq"><span class="header-section-number">5.2</span> Procesos en medias móviles MA(q)</h2>
<section id="definición-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-1">Definición</h3>
<p>El modelo general <strong>en medias móviles de orden q</strong>, <span class="math inline">\(y_t \sim MA(q)\)</span> viene definido por <span class="math display">\[y_t=c + \varepsilon_t + \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2} + \ldots + \theta_q \varepsilon_{t-q},\]</span> que usando el operador retardo queda <span class="math display">\[y_t = c + (1 + \theta_1 L + \theta_2 L^2 + \ldots + \theta_q L^q) \varepsilon_t\]</span></p>
<p>En este y en cualquier proceso ARIMA, al polinomio en <span class="math inline">\(L\)</span> que acompaña a <span class="math inline">\(\varepsilon_t\)</span> se le denomina <strong>polinomio en medias móviles</strong>.</p>
</section>
<section id="ejemplos-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-1">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim MA(1): \;\;y_t = c + \varepsilon_t + \theta_1 \varepsilon_{t-1}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_1 L)\varepsilon_t\)</span></li>
<li><span class="math inline">\(y_t \sim MA(2): \;\;y_t=c + \varepsilon_t + \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_1 L + \theta_2 L^2)\varepsilon_t\)</span></li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="procesos-armapq" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="procesos-armapq"><span class="header-section-number">5.3</span> Procesos ARMA(p,q)</h2>
<section id="definición-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-2">Definición</h3>
<p>El modelo general <span class="math inline">\(y_t \sim ARMA(p,q)\)</span> viene dado por <span class="math display">\[y_t = c + \phi_1 y_{t-1} + \phi_2 y_{t-2} + \ldots + \phi_p y_{t-p}  +
        \theta_1 \varepsilon_{t-1} + \theta_2 \varepsilon_{t-2} + \ldots +
        \theta_q \varepsilon_{t-q}+ \varepsilon_t,\]</span> que usando el operador retardo queda <span class="math display">\[(1 - \phi_1 L - \ldots - \phi_p L^p)y_t = c + (1 + \theta_1 L + \ldots + \theta_q L^q) \varepsilon_t.\]</span></p>
</section>
<section id="ejemplos-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-2">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim ARMA(1, 1): \;\;y_t = c + \phi_1 y_{t-1} + \theta_1 \varepsilon_{t-1} + \varepsilon_{t}\)</span> o <span class="math inline">\((1 - \phi_1 L)y_t = c + (1 + \theta_1 L)\varepsilon_t\)</span></li>
<li><span class="math inline">\(y_t \sim ARMA(0, 0): \;\;y_t = c + \varepsilon_{t}\)</span>. Si <span class="math inline">\(c = 0\)</span>, a este proceso se le denomina <strong>ruido blanco</strong>.</li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="proceso-arimapdq" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="proceso-arimapdq"><span class="header-section-number">5.4</span> Proceso ARIMA(p,d,q)</h2>
<p><strong>Si la serie</strong> <span class="math inline">\(y_t\)</span> no es estacionaria, pero tras diferenciarla <span class="math inline">\(d\)</span> veces se hace estacionaria, diremos que la serie es integrada de orden <span class="math inline">\(d\)</span>: <span class="math inline">\(y_t \sim I(d)\)</span>. Por tanto,</p>
<ul>
<li>una serie estacionaria se indicará como <span class="math inline">\(y_t \sim I(0)\)</span></li>
<li><span class="math inline">\(y_t \sim I(d)\)</span> es equivalente a <span class="math inline">\(\nabla^d y_t = (1 - L)^d y_t \sim I(0)\)</span></li>
</ul>
<p>Una serie <span class="math inline">\(y_t\)</span> sigue un proceso <span class="math inline">\(ARIMA(p,d,q)\)</span> si:</p>
<ol type="1">
<li><span class="math inline">\(y_t \sim I(d)\)</span>, hay que diferenciarla <span class="math inline">\(d\)</span> veces para hacerla estacionaria, y</li>
<li><span class="math inline">\(\nabla^d y_t \sim ARMA(p,q)\)</span>.</li>
</ol>
<p>Entonces, podemos escribir <span class="math inline">\(y_t \sim ARIMA(p,d,q)\)</span>:</p>
<span class="math display">\[\begin{equation*}
  \begin{array}{c@{\qquad}c@{\quad}ccc}
   (1 - \phi_1 L - \ldots - \phi_p L^p) &amp; (1- L)^d y_t &amp; = &amp; c + (1 + \theta_1 L + ... + \theta_q L^q) \varepsilon_t \\
                           \uparrow                            &amp; \uparrow      &amp;   &amp; \uparrow \\
                           AR(p)                               &amp; I(d)          &amp;   &amp; MA(q)
  \end{array}
\end{equation*}\]</span>
<section id="ejemplos-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-3">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim ARIMA(1, 1, 1): \;\;(1 - \phi_1 L)(1- L) y_t = c + (1 + \theta_1 L) \varepsilon_t\)</span> o <span class="math inline">\(y_t = c + y_{t-1} + \phi_1(y_{t-1} - y_{t-2}) + \theta_1 \varepsilon_{t-1} + \varepsilon_t\)</span>.</li>
<li><span class="math inline">\(y_t \sim ARIMA(0, 1, 0): \;\;(1- L) y_t = c + \varepsilon_t\)</span> o <span class="math inline">\(y_t = c + y_{t-1} + \varepsilon_t\)</span>. Si <span class="math inline">\(c=0\)</span>, tenemos un <strong>paseo aleatorio</strong>; si <span class="math inline">\(c \neq 0\)</span>, tenemos un <strong>paseo aleatorio con deriva</strong>.</li>
</ul>
<p><br>
<br>
</p>
</section>
</section>
</section>
<section id="aproximación-de-box-jenkins" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Aproximación de Box-Jenkins</h1>
<p>La siguiente figura muestra el flujo de procesos asociado a la modelización por modelos ARIMA, con cuatro grandes áreas:</p>
<ul>
<li><p><strong>Identificación</strong>, que requiere primero transformar la serie para que sea estacionaria y ergódica, para después identificar los valores de p y q.</p>
<p>La FAC y la función de autocorrelación parcial (que no hemos visto) teóricas son diferentes en cada tipo de proceso. Idealmente, su estimación a partir de la serie temporal podría servir de ayuda en la identificación del proceso estocástico. En la práctica, la funciones estimadas son tan diferentes de las teóricas que resultan de muy poca ayuda.</p>
<p>Nosotros haremos uso de algunas funciones de <em>auto</em> identificación que nos ayudaran en este punto.</p></li>
<li><p><strong>Estimación</strong> de los parámetros del modelo, incluidas las variables de intervención y obtención del error. El método usual de estimación de los parámetros es por máxima verosimilitud.</p></li>
<li><p><strong>Validación</strong> de las hipótesis sobre el modelo. Analizaremos que no es necesaria más intervención y veremos la pertinencia de los parámetros del modelo (bien contrastando su significatividad o bien por alguna regla más sencilla).</p>
<p>Si la validación no se pasa, puede ser necesario volver al proceso inicial y realizar una nueva identificación del modelo.</p></li>
<li><p><strong>Predicción</strong> e interpretación del modelo válido. Si las predicciones se alejan de los valores reales más de lo esperado o presentan sesgo, puede ser necesario identificar y estimar un nuevo modelo.</p></li>
</ul>
<div id="fig-AproximaciónBoxJenkins" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./imagenes/BoxJenkins.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figura 6: Esquema de la aproximación de Box-Jenkins a la modelización de procesos ARIMA</figcaption><p></p>
</figure>
</div>
<p><br>
<br>
</p>
<section id="identificación-automática" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-automática">Identificación automática</h3>
<p>El paquete <code>forecast</code> dispone de la función <code>auto.arima()</code> que localiza el mejor modelo basándose en el AIC corregido para pequeñas muestras (<code>AICc</code>). No hay que fiarse ciegamente de los resultados de esta función, pero ayuda en la identificación. Básicamente el algoritmo seguido es el siguiente:</p>
<ol type="1">
<li>Determina el orden de diferenciación regular <span class="math inline">\(0 \leq d \leq 2\)</span> usando la función <code>ndiffs</code>.</li>
<li>Tras diferenciar la serie:
<ul>
<li>se estiman una serie de modelos básicos predeterminados.</li>
<li>se usa el criterio AICc para seleccionar el mejor de estos modelos.</li>
<li>a partir del modelo seleccionado, se hacen pequeñas variaciones modificando en una unidad <em>p</em> y <em>q</em> y añadiendo/quitando la constante y se vuelve a seleccionar el mejor de los nuevos modelos.</li>
</ul></li>
<li>Se repite el paso 2 hasta que no se puede mejorar el AICc.</li>
</ol>
<p>Cuando usemos esta función, debemos tener cuenta que:</p>
<ul>
<li>La función <code>auto.arima</code> no permite constante si se diferencia dos veces.</li>
<li>Si se desea hacer una búsqueda exhaustiva entre todos los posibles modelos, se debe usar el argumento <code>stepwise = FALSE</code>.</li>
<li>Si se desea que el cálculo de AICc sea exacto (por defecto para ganar tiempo calcula una aproximación), se debe usar el argumento <code>approximation = FALSE</code>.</li>
<li>Si se desea ver para todos los modelos analizados el valor de AICc, se debe incluir el argumento <code>trace = TRUE</code>.</li>
</ul>
<p>La función <code>auto.arima</code> tiende a sobre-parametrizar los modelos y es muy recomendable <em>ayudarla</em> indicando las diferenciaciones, la posible intervención…</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="ejemplos-4" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Ejemplos</h1>
<p><br>
</p>
<section id="títulos-de-libros-y-panfletos" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="títulos-de-libros-y-panfletos"><span class="header-section-number">7.1</span> Títulos de libros y panfletos</h2>
<p>Vamos a aplicar la metodología de Box-Jenkins a la serie Libros (número de títulos publicados anualmente en España desde 1993 hasta 2019).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/libros.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>libros <span class="ot">&lt;-</span> <span class="fu">ts</span>(libros[, <span class="dv">2</span>], <span class="at">start =</span> <span class="dv">1993</span>, <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(libros,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Titulos"</span>, </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Libros" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-Libros-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 7: Títulos publicados</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="transformación-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie">Transformación de la serie</h3>
<p>El primer paso es transformar la serie original para que sea estacionaria. La <a href="#fig-LibrosFAC">Figura&nbsp;8</a> muestra la gráfica temporal y la FAC para la serie original y su primera diferencia.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(libros, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(libros), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(libros, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(libros), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-LibrosFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-LibrosFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-LibrosFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 8: Gráfica y FAC para Libros</figcaption><p></p>
</figure>
</div>
<p>Además,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(libros)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Podemos concluir que la primera diferencia de la serie Libros es estacionaria y ergódica. Es decir, <span class="math inline">\(d=1\)</span> o <span class="math inline">\(libros_t \sim I(1)\)</span>.</p>
</section>
<section id="identificación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación">Identificación</h3>
<p>Tras diferenciar la serie, vamos a identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span>. Este es el proceso más difícil y para simplificar las cosas vamos a ayudarnos de la función <code>auto.arima</code>. Como ya hemos decidido el número de diferenciaciones, fijamos este parámetro con <code>d = 1</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(libros, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ARIMA(2,1,2) with drift         : Inf
 ARIMA(0,1,0) with drift         : 529.2727
 ARIMA(1,1,0) with drift         : 531.8087
 ARIMA(0,1,1) with drift         : 531.8033
 ARIMA(0,1,0)                    : 527.5277
 ARIMA(1,1,1) with drift         : Inf

 Best model: ARIMA(0,1,0)                    </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: libros 
ARIMA(0,1,0) 

sigma^2 = 34911235:  log likelihood = -262.68
AIC=527.36   AICc=527.53   BIC=528.62</code></pre>
</div>
</div>
<p>Observa como la identificación automática da como mejor modelo <span class="math inline">\(p=q=0\)</span>. Es decir <span class="math inline">\(libros_t \sim ARIMA(0,1,0)\)</span> sin deriva (sin constante), por tanto, sigue un paseo aleatorio: <span class="math display">\[libros_t = libros_{t-1} + \varepsilon_t\]</span></p>
</section>
<section id="estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación">Estimación</h3>
<p>Aunque existe la función <code>arima</code> de <code>stats</code>, vamos a usar la función <code>Arima</code> de la librería <code>forecast</code> para estimar el modelo identificado por ser más versátil. El argumento <code>order</code> indica los valores de (p, d , q) como un vector y el argumento lógico <code>include.constant</code> indica si se desea incluir la constante <span class="math inline">\(c\)</span> en el modelo.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>arima010 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(libros, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>arima010</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: libros 
ARIMA(0,1,0) 

sigma^2 = 34911235:  log likelihood = -262.68
AIC=527.36   AICc=527.53   BIC=528.62</code></pre>
</div>
</div>
<p>Nuestro modelo estimado es: <span class="math inline">\(\widehat{libros}_t = libros_{t-1}\)</span>. La mejor predicción para un año, es la observación del año anterior, ¡el método ingenuo I!</p>
</section>
<section id="intervención" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="intervención">Intervención</h3>
<p>Se analiza si para algún año se observa un error atípico (por ejemplo 3 veces superior al error estándar). La <a href="#fig-LibrosError">Figura&nbsp;9</a> muestra que en este caso en varios periodos, años 2008, 2009 y 2013, el residuo sobrepasa los dos errores estándar pero queda lejos de los tres errores estándar así que asumiremos que no hay valores atípicos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima010)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1993</span>, <span class="dv">2019</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LibrosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 9: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="medidas-de-error" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="medidas-de-error">Medidas de error</h3>
<p>El error medio es 5798 títulos (RMSE) y el error porcentual medio (MAPE) es 6.88%.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima010)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                 ME    RMSE     MAE  MPE MAPE MASE  ACF1
Training set 868.03 5798.12 4358.32 1.29 6.88 0.96 -0.04</code></pre>
</div>
</div>
<p>Además, hay cierto sesgo (las previsiones intra-muestrales en media subestiman los datos reales) y la fórmula usada para la previsión por intervalo es correcta.</p>
</section>
<section id="predicción" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción">Predicción</h3>
<p>Una vez validado el modelo podemos pasar a realizar <strong>predicciones</strong>, en este caso a 5 años vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>parima010 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima010, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>parima010</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020          64154 52573.41 75734.59
2021          64154 47776.57 80531.43
2022          64154 44095.83 84212.17
2023          64154 40992.82 87315.18
2024          64154 38259.01 90048.99</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima010, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Títulos"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1993</span>, <span class="dv">2024</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LibrosPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-LibrosPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 10: Libros (1993-2019) y predicción (2020-2024)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-LibrosPre">Figura&nbsp;10</a> muestra la serie, la previsión y el intervalo de confianza al 95%. La predicción es constante e igual al último dato. En las series diferenciadas el intervalo de confianza de las predicciones crece muy rápidamente porque los errores se van acumulando sin ningún tipo de amortiguamiento.</p>
<p><br>
</p>
</section>
</section>
<section id="aforo-de-vehículos" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="aforo-de-vehículos"><span class="header-section-number">7.2</span> Aforo de vehículos</h2>
<p>Vamos a aplicar de nuevo la metodología de Box-Jenkins a la serie <strong>aforo de vehículos</strong> por Oropesa, carretera N-340, km. 996,48 (fuente Ministerio de Fomento). La serie es anual de 1960 a 2019 (60 datos).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>aforo <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/aforo_oropesa.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>aforo <span class="ot">&lt;-</span> <span class="fu">ts</span>(aforo, <span class="at">start =</span> <span class="dv">1960</span>, <span class="at">freq =</span> <span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(aforo, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Vehículos (000)"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Aforo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-Aforo-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 11: Aforo de vehículos en N-340, Oropesa</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>En este ejemplo incluiremos, por primera vez, intervención y veremos como <strong>la presencia de valores atípicos puede distorsionar el proceso de identificación automática</strong>. Por ello, es conveniente realizar en paralelo ambas actividades, identificar el proceso y detectar valores atípicos.</p>
<p><br>
</p>
<section id="transformación-de-la-serie-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-1">Transformación de la serie</h3>
<p>La <a href="#fig-AforoFAC">Figura&nbsp;12</a> muestra que la serie Aforo no es estacionaria. Así, el primer paso es transformar la serie original para que lo sea. La serie no es estacionaria, pero sí lo es su primera diferencia. Ten siempre presente que diferenciar más veces de las necesarias puede dificultar la identificación y la interpretación. Por otro lado, la función <code>ndiffs</code> aconseja una diferenciación. Así, optamos por fijar <span class="math inline">\(d = 1\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(aforo, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(aforo), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(aforo, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(aforo), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-AforoFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AforoFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-AforoFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 12: Gráfica y FAC para Aforo</figcaption><p></p>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(aforo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p><br>
</p>
</section>
<section id="identificación-y-estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación">Identificación y Estimación</h3>
<p>Veamos a identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span> a partir de <code>auto.arima</code>, indicándole que <code>d = 1</code>. La función sugiere un proceso ARIMA(2,1,2).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(aforo, <span class="at">d =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
ARIMA(2,1,2) 

Coefficients:
         ar1      ar2      ma1     ma2
      1.3202  -0.6730  -1.2817  0.9363
s.e.  0.1311   0.1194   0.0979  0.1955

sigma^2 = 642488:  log likelihood = -477.45
AIC=964.91   AICc=966.04   BIC=975.3</code></pre>
</div>
</div>
<p>Una forma rápida, aunque imprecisa, de determinar si un coeficiente es relevante (significativo) es compararlo con su error estándar (standard error, s.e). Si el coeficiente es mayor que dos veces su error estándar, hay evidencia de que es significativo. En la salida de <code>R</code>, en la tabla <code>Coefficients</code> tienes en la primera fila el nombre de los coeficientes (<code>ar</code> en lugar de <span class="math inline">\(\phi\)</span> y <code>ma</code> en lugar de <span class="math inline">\(\theta\)</span>); su valor aparece en la segunda fila de la tabla; y los errores estándar en la tercera fila (encabezada por s.e.). Todos los coeficientes estimados superan las dos desviaciones estándar y parece que son significativos.</p>
<p>Vamos a ver la gráfica de los residuos del modelo ARIMA(2,1,2) para identificar los valores extremos (intervención).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>arima212 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(aforo, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima212)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2020</span>, <span class="dv">4</span>)) </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co">#time(error)[abs(error) &gt; 2.5*sderror]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 13: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Se identifican dos posibles valores extremos en los años 1979 y 2011 (el error supera las 2.5 desviaciones típicas). Ahora, creamos una variable ficticia asociada a cada año, que denominaremos d1979 y d2011, y las incluimos en la auto-identificación.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>d1979 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">time</span>(error) <span class="sc">==</span> <span class="dv">1979</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>d2011 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">time</span>(error) <span class="sc">==</span> <span class="dv">2011</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(aforo,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">xreg =</span> <span class="fu">cbind</span>(d1979,  d2011))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
Regression with ARIMA(2,1,0) errors 

Coefficients:
         ar1     ar2       d1979       d2011
      0.1852  0.4420  -1716.4503  -1194.6499
s.e.  0.1181  0.1206    489.4467    455.9998

sigma^2 = 593139:  log likelihood = -474.07
AIC=958.14   AICc=959.27   BIC=968.53</code></pre>
</div>
</div>
<p>Observa como la inclusión de intervención modifica la auto-identificación, que ahora es un proceso ARIMA(2,1,0).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>arima210 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(aforo, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">FALSE</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xreg =</span> <span class="fu">cbind</span>(d1979, d2011))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>arima210</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: aforo 
Regression with ARIMA(2,1,0) errors 

Coefficients:
         ar1     ar2       d1979       d2011
      0.1852  0.4420  -1716.4503  -1194.6499
s.e.  0.1181  0.1206    489.4467    455.9998

sigma^2 = 593139:  log likelihood = -474.07
AIC=958.14   AICc=959.27   BIC=968.53</code></pre>
</div>
</div>
<p>La <a href="#fig-AforoError2">Figura&nbsp;14</a> muestra que para ningún año se observa un error atípico. Es decir, no es necesaria más intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima210)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2020</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoError2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoError2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 14: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="validación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación">Validación</h3>
<p>La identificación de errores atípicos –para la posterior inclusión de sus variables de intervención asociadas– ha sido un tanto arbitraria: ¿es atípico el error que supera las 2 desviaciones típicas, las dos y media, las tres desviaciones típicas?</p>
<p>A fin de poner un poco de <em>objetividad</em> en la decisión, podemos ver si sus coeficientes son significativos y dejar solo aquellas variables de intervención cuyo coeficientes lo sean. Aunque si la serie es suficientemente larga, también podríamos saltarnos este paso y dejar las variables de intervención que mejoren las predicciones extra-muestrales del modelo o las que recojan efectos conocidos.</p>
<p>La prueba de Wald permite contrastar si un subconjunto de coeficientes es significativo (se precisa la librería <code>aod</code>). Esta función requiere de tres argumentos: el vector de coeficientes (<code>b</code>), su matriz de covarianzas (<code>Sigma</code>) y la posición de los coeficientes cuya significatividad conjunta deseamos contrastar (<code>Terms</code>). Los dos primeros argumentos los podemos obtener del objeto <code>arima210</code> con las funciones <code>coef</code> y <code>vcov</code>.</p>
<p>Por ejemplo, para ver la significatividad de la primera variable de intervención (tercer coeficiente del modelo), tendríamos</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima210), </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima210), </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">Terms =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 12.3, df = 1, P(&gt; X2) = 0.00045</code></pre>
</div>
</div>
<p>Con algo más de código se puede comprobar qué coeficientes estimados son significativos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima210)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(arima210))) {</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima210), </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima210), </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(arima210))[i], <span class="at">width =</span> ancho), </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ar1     valor de p:  0.1168
Coeficiente:  ar2     valor de p:  0.0002
Coeficiente:  d1979   valor de p:  0.0005
Coeficiente:  d2011   valor de p:  0.0088</code></pre>
</div>
</div>
<p>Las dos variables de intervención son significativas y el coeficiente <span class="math inline">\(\phi_2\)</span> (<code>ar2</code>) también. No es significativo el coeficiente <span class="math inline">\(\phi_1\)</span> (<code>ar1</code>), pero no lo podemos eliminar. Los modelos Arima son modelos jerárquicos donde la presencia de un coeficiente significativo de cierto orden exige que los coeficientes de orden inferior estén presentes, sean o no significativos. En nuestro caso, como el coeficiente <span class="math inline">\(\phi_2\)</span> es significativo, se debe dejar en el modelo el coeficiente <span class="math inline">\(\phi_1\)</span>.</p>
<p>Confirmamos que <span class="math inline">\(aforo_t \sim ARIMA(2,1,0)\)</span> con intervención.</p>
<p><br>
</p>
</section>
<section id="medidas-de-error-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="medidas-de-error-1">Medidas de error</h3>
<p>El error medio es 737 miles de vehículos (RMSE) y el error porcentual medio (MAPE) es 5.67%. No hay sesgo de predicción y las fórmulas empleadas para el cálculo de los intervalos de confianza de las predicciones son válidos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima210)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>               ME   RMSE    MAE  MPE MAPE MASE ACF1
Training set 47.2 737.37 535.16 1.32 5.67 0.79 0.04</code></pre>
</div>
</div>
<p><br>
</p>
</section>
<section id="interpretación-del-modelo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-del-modelo">Interpretación del modelo</h3>
<p>El <strong>modelo teórico</strong> es <span class="math inline">\(aforo_t \sim ARIMA(2,1,0) + d1979 + d2011\)</span>: <span class="math display">\[(1 - \phi_1 L - \phi_2 L^2)(1 - L)aforo_t =  \varepsilon_t + \gamma_1 \cdot d1979 + \gamma_2 \cdot d2011.\]</span></p>
<p>Si desarrollamos, queda: <span class="math display">\[aforo_t = aforo_{t-1} + \phi_1(aforo_{t-1}-aforo_{t-2}) + \phi_2(aforo_{t-2}-aforo_{t-3}) +\]</span> <span class="math display">\[\gamma_1 \cdot d1979 +  \gamma_2 \cdot d2011 + \varepsilon_t.\]</span></p>
<p>Finalmente, el <strong>modelo estimado</strong> es: <span class="math display">\[\widehat{aforo}_t = aforo_{t-1} + 0.19(aforo_{t-1}-aforo_{t-2}) + 0.44(aforo_{t-2}-aforo_{t-3})\]</span> <span class="math display">\[-1716 \cdot d1979 -1195 \cdot d2011\]</span> Cada año el aforo es el mismo que el aforo del año pasado más un 19% del último incremento observado y un 44% del incremento anterior.</p>
<p>Respecto de la intervención, en 1979 hubo un 1.7 millones menos de vehículos de lo esperado, debido a la apertura de la autopista AP-7 y en 2011 hubo 1.2 millones menos de vehículos, posiblemente debido a la Gran Recesión.</p>
</section>
<section id="predicción-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-1">Predicción</h3>
<p>Como hemos incluido dos variables ficticias en el ajuste, de cara a predecir el aforo hemos de indicar cuales serán los valores futuros para estas variables. En este caso serán cero puesto que son intervenciones que no responden a un efecto calendario. La causa detrás de estas dos intervenciones no se espera que se repitan en el futuro.</p>
<p>En <code>R</code> esto se hace incluyendo en el comando <code>forecast</code> el argumento <code>xreg = cbind(rep(0, 5), rep(0, 5))</code> que añade cinco ceros por cada variable de intervención porque la predicción va a ser a cinco años vista.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>parima210 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima210, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xreg =</span> <span class="fu">cbind</span>(<span class="at">d1979=</span><span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">d2011=</span><span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>)))</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>parima210</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2020       9700.908 8191.432 11210.38
2021       9647.604 7306.822 11988.39
2022       9643.437 6212.738 13074.14
2023       9619.103 5212.971 14025.24
2024       9612.754 4207.919 15017.59</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima210, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Vehículos (000)"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2024</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AforoPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AforoPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 15: Aforo (1960-2019) y predicción (2020-2024)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
<section id="validación-con-origen-de-predicción-móvil" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-con-origen-de-predicción-móvil">Validación con origen de predicción móvil</h3>
<p>Vamos a calcular el error extra-muestral según el horizonte temporal de previsión. En este caso, la presencia de variables de intervención hace el código algo más complejo.</p>
<p>Asumiremos que se precisan 30 años para estimar el modelo, fijaremos el horizonte temporal en 5 años y calcularemos el error MAPE, que para la predicción intra-muestral era de 5.7%.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">30</span>                  </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">5</span>                    </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(aforo)     </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> T <span class="sc">-</span> k <span class="sc">-</span> h    </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(d1979, d2011))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(aforo, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(aforo, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(train.set, </span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>,</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg=</span><span class="fu">as.matrix</span>(X.train))</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>    fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test))</span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>      fit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(train.set, </span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.constant =</span> <span class="cn">FALSE</span>,</span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>      fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>  mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima)</span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a>mapeArima</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  5.651824  9.691844 14.902944 19.538856 23.247141</code></pre>
</div>
</div>
<p>El error de previsión extra-muestral crece notablemente con el horizonte temporal. El error de las previsiones a un año vista es del 5.7%, prácticamente igual al error intra-muestral, pero para dos años vista casi alcanza el 10% y a cinco años vista supera el 20%.</p>
<p><br>
</p>
</section>
</section>
<section id="consumo-de-alimentos-en-el-hogar-per-cápita" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="consumo-de-alimentos-en-el-hogar-per-cápita"><span class="header-section-number">7.3</span> Consumo de alimentos en el hogar per cápita</h2>
<p>Analizaremos el <strong>consumo alimentario en hogar per cápita</strong> en España. Esta serie está construida a partir de la serie de consumo alimentario en hogar (disponible en el Ministerio de Agricultura, Alimentación y Medio Ambiente), y la serie de población (disponible en el Instituto Nacional de Estadística). Es una serie anual de 1987 a 2021 (35 datos) y la unidad es el Kg per cápita. La <a href="#fig-Alimentos">Figura&nbsp;16</a> muestra que es una serie estacionaria.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>alimentospc <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/alimentacionpc.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>alimentospc <span class="ot">&lt;-</span> <span class="fu">ts</span>(alimentospc, <span class="at">start =</span> <span class="dv">1987</span>, <span class="at">freq =</span> <span class="dv">1</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(alimentospc, </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Kg per cápita"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">700</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Alimentos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-Alimentos-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 16: Consumo alimentario en hogar</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>El pico en el año 2020 se debe al aumento del consumo de alimentos en el hogar causado por el periodo de confinamiento por la Covid-19 (marzo a junio) y el aumento del <em>tele-trabajo</em>.</p>
<section id="transformación-de-la-serie-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-2">Transformación de la serie</h3>
<p>La <a href="#fig-AlimentosFAC">Figura&nbsp;17</a> indica que la serie original ya es estacionaria y la función <code>ndiffs</code> lo corrobora. Por tanto asumimos que <span class="math inline">\(d=0\)</span> o <span class="math inline">\(alimentospc_t \sim I(0)\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(alimentospc, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">diff</span>(alimentospc), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(alimentospc, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(alimentospc), <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-AlimentosFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(b) Dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(c) FAC serie original</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-AlimentosFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-AlimentosFAC"></p>
<p></p><figcaption class="figure-caption">(d) FAC dif. de la serie</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura 17: Gráfica y FAC para Alimentos</figcaption><p></p>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(alimentospc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="identificación-y-estimación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-y-estimación-1">Identificación y Estimación</h3>
<p>Para identificar los valores de <span class="math inline">\(p\)</span> y <span class="math inline">\(q\)</span> veremos que nos sugiere <code>auto.arima</code> :</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(alimentospc,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">d =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: alimentospc 
ARIMA(1,0,0) with non-zero mean 

Coefficients:
         ar1      mean
      0.3359  638.4829
s.e.  0.1711    3.8911

sigma^2 = 254.2:  log likelihood = -145.61
AIC=297.22   AICc=297.99   BIC=301.88</code></pre>
</div>
</div>
<p>La identificación automática sugiere un proceso AR(1) con constante. El coeficiente de la constante (“mean” en la salida) es significativo –su valor supera dos veces su error estándar–, pero el del proceso autorregresivo no está tan claro.</p>
<p>Vamos a ver la gráfica de los residuos de este proceso para identificar rápidamente si hay valores extremos (<a href="#fig-AlimentosError">Figura&nbsp;18</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>arima100 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(alimentospc, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">TRUE</span>,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima100)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1987</span>, <span class="dv">2021</span>, <span class="dv">3</span>)) </span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="co">#time(alimentospc)[abs(error) &gt; 2 * sderror]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AlimentosError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 18: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Hay un claro valor extremos en 2020. Tras incluirla y estimar el nuevo modelo aparecen otras variables de intervención asociadas a los años 1993, 1995 y 2009. Aunque ninguna supera las 2.5 desviaciones típicas, su efecto es significativo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>d1993 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">1993</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>d1995 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">1995</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>d2009 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">2009</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>d2020 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span> (<span class="fu">time</span>(alimentospc) <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>arima100 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(alimentospc, </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">include.constant =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xreg =</span> <span class="fu">cbind</span>(d1993, d1995, d2009, d2020))</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>arima100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: alimentospc 
Regression with ARIMA(1,0,0) errors 

Coefficients:
         ar1  intercept    d1993     d1995    d2009    d2020
      0.8164   638.5062  21.9317  -15.8202  21.3736  55.8455
s.e.  0.1153     7.7231   7.1062    7.1049   7.1063   7.1295

sigma^2 = 101.5:  log likelihood = -127.76
AIC=269.53   AICc=273.67   BIC=280.41</code></pre>
</div>
</div>
</section>
<section id="validación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-1">Validación</h3>
<p>Tanto <span class="math inline">\(\phi_1\)</span> como el intercepto <span class="math inline">\(\mu\)</span> y las variables de intervención son significativas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 50.2, df = 1, P(&gt; X2) = 0.0000000000014</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 6835.1, df = 1, P(&gt; X2) = 0.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 9.5, df = 1, P(&gt; X2) = 0.002</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 5.0, df = 1, P(&gt; X2) = 0.026</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 9.0, df = 1, P(&gt; X2) = 0.0026</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(arima100), <span class="at">Sigma =</span> <span class="fu">vcov</span>(arima100), <span class="at">Terms =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 61.4, df = 1, P(&gt; X2) = 0.0000000000000048</code></pre>
</div>
</div>
<p>Consideraremos que <span class="math inline">\(alimentospc_t \sim ARIMA(1,0,0)\)</span> con constante e intervención.</p>
</section>
<section id="medidas-de-error-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="medidas-de-error-2">Medidas de error</h3>
<p>El error medio es 9.2 Kg per cápita (RMSE) y el error porcentual medio (MAPE) es 1.2%. No hay sesgo y los intervalos de confianza de las predicciones son correctos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(arima100)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                ME RMSE  MAE   MPE MAPE MASE ACF1
Training set -1.26 9.17 7.57 -0.22 1.19 0.62 0.05</code></pre>
</div>
</div>
</section>
<section id="interpretación-del-modelo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-del-modelo-1">Interpretación del modelo</h3>
<p>El <strong>modelo teórico</strong> identificado es <span class="math display">\[(1 - \phi_1 L) alimentospc_t = c + \gamma_1 d1993 + \gamma_2 d1995 + \gamma_3 d2009 + \gamma_4 d2020 + \varepsilon_t,\]</span> que desarrollando queda <span class="math display">\[alimentospc_t = c + \phi_1 alimentospc_{t-1} + \gamma_1 d1993 + \gamma_2 d1995 + \gamma_3 d2009 + \gamma_4 d2020 + \varepsilon_t.\]</span></p>
<p>Finalmente, el <strong>modelo estimado</strong> es <span class="math display">\[\widehat{alimentospc}_t = 117.2 + 0.82 \cdot alimentospc_{t-1} +\]</span> <span class="math display">\[21.93\cdot d1993 - 15.82\cdot d1995 + 21.37\cdot d2009 + 55.85\cdot d2020\]</span></p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
La contante del modelo teórico y la media del modelo estimado
</div>
</div>
<div class="callout-body-container callout-body">
<p>El término contante <span class="math inline">\(\mu\)</span> que estima <code>R</code> no es el valor “c” que hemos visto en la teoría. Para convertir la contante estimada por <code>R</code> en “c” hemos de multiplicarla por el polinomio autorregresivo. En este caso, <span class="math display">\[c = \mu \cdot (1 - \phi_1) = 638.5062\cdot(1 - 0.8164) = 117.23\]</span></p>
</div>
</div>
<p>Cada año el consumo de alimentos per cápita en el hogar es 117.2 kilos más un 82% del consumo del año pasado.</p>
<p>En 2020, debido al efecto combinado del periodo de confinamiento entre marzo y junio y el incremento del trabajo en casa, se produjo un fuerte aumento del consumo de alimentos en el hogar, estimado en 56 Kg. per cápita. En 1993 y 2009 el consumo medio de alimentos per cápita fue entre 21 y 22 kg superior a los esperado. Posiblemente, este incremento se deba al aumento del paro y la caída de los ingresos debida al crisis de 1993 y la Gran Recesión (2008-2014), respectivamente. Finalmente, en 1995 se observa un consumo 16 kg. menor de lo esperado.</p>
</section>
<section id="predicciones-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicciones-de-la-serie">Predicciones de la serie</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>parima100 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(arima100, </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">h =</span> <span class="dv">5</span>, </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">level =</span> <span class="dv">95</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xreg =</span> <span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">5</span>)))</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>parima100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Point Forecast    Lo 95    Hi 95
2022       626.9791 607.2378 646.7203
2023       629.0957 603.6114 654.5800
2024       630.8237 602.1434 659.5040
2025       632.2344 601.6088 662.8600
2026       633.3860 601.5298 665.2422</code></pre>
</div>
</div>
<p>Puedes comprobar que cada valor de la predicción se ha obtenido a partir del modelo estimado, donde <span class="math inline">\(alimentospc_{t-1}\)</span> se sustituye por la predicción del año precedente.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(parima100, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Kilos per cápita"</span>,</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1986</span>, <span class="dv">2026</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-AlimentosPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-06-Tema6_files/figure-html/fig-AlimentosPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura 19: Consumo de alimentos y predicción</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="comparación-con-alisado-exponencial" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="comparación-con-alisado-exponencial"><span class="header-section-number">7.4</span> Comparación con alisado exponencial</h2>
<p>Veamos una comparativa, para los tres ejemplos vistos, entre los resultados obtenidos con ARIMA y con Alisado exponencial.</p>
<ul>
<li>Libros:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(6.88\%\)</span> - ARIMA(0,1,0) sin deriva</p></li>
<li><p>MAPE ETS: <span class="math inline">\(6.90\%\)</span> - ETS(M,N,N), <span class="math inline">\(\alpha=1\)</span></p></li>
<li><p>Ambos métodos han estimado el mismo modelo.</p></li>
</ul></li>
</ul>
<ul>
<li>Aforo:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(5.67\%\)</span> - ARIMA(2,1,0) sin deriva, con intervención</p></li>
<li><p>MAPE ETS: <span class="math inline">\(6.09\%\)</span> - ETS(M,A,N), <span class="math inline">\(\alpha=1\)</span>, <span class="math inline">\(\beta=0.1\)</span></p></li>
<li><p>Cada método estima un modelo diferente</p></li>
<li><p>ARIMA tiene menor error a costa de incluir variables de intervención</p></li>
</ul></li>
</ul>
<ul>
<li>Alimentos per cápita:
<ul>
<li><p>MAPE ARIMA: <span class="math inline">\(1.19\%\)</span> - ARIMA(1,0,0) con constante e intervención</p></li>
<li><p>MAPE ETS: <span class="math inline">\(1.93\%\)</span> - ETS(A,N,N), <span class="math inline">\(\alpha = 0.37\)</span></p></li>
<li><p>Cada método ha estimado un modelo diferente</p></li>
<li><p>ARIMA tiene menor error a costa de incluir variables de intervención</p></li>
</ul></li>
</ul>
<p><br>
<br>
</p>
</section>
</section>
<section id="resumen-de-los-comandos-utilizados" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Resumen de los comandos utilizados</h1>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Función</th>
<th style="text-align: left;">Paquete</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Arima</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">estima un proceso ARIMA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>auto.arima</code></td>
<td style="text-align: left;">forecast</td>
<td style="text-align: left;">identificación automática de un modelo ARIMA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>wald.test</code></td>
<td style="text-align: left;">aod</td>
<td style="text-align: left;">contrasta la significatividad conjunta de varios parámetros</td>
</tr>
</tbody>
</table>
<p><br>
<br>
</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-BoxJenkins76" class="csl-entry" role="doc-biblioentry">
Box, G. E. P., and G. M. Jenkins. 1976. <em>Time Series Analysis: Forecasting and Control</em>. Holden-Day, San Francisco.
</div>
</div></section><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>La transformación logarítmica es un caso concreto de otra más general, la transformación de Box-Cox que no veremos en este curso: <span class="math display">\[
  z_t =
  \begin{cases}
    (y_t^{\lambda}-1)/\lambda &amp; \,\,\,\lambda \neq 0 \\
    \log(y_t) &amp; \,\,\, \lambda = 0
  \end{cases}
  \]</span> Se puede demostrar que <span class="math inline">\(\lim_{\lambda \rightarrow 0} \;\; (y_t^{\lambda}-1)/\lambda = log(y_t)\)</span>.</p>
<p>El argumento <code>lambda</code> que hemos usado en algunas funciones de la librería <code>forecast</code> hace referencia al parámetro <span class="math inline">\(\lambda\)</span> de la transformación Box-Cox. Siempre lo hemos fijado a cero, indicando la transformación logarítmica.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Mira en la ayuda de la función <code>Arima</code> la diferencia entre los argumentos <code>include.mean</code>, <code>include.drift</code> e <code>include.constant</code><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2022, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.e</a></div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>