<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Procesos ARIMA con estacionalidad</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Inicio</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html">Guía del curso</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html">Logística</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false">Diapos</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html">
 <span class="dropdown-text">Tema 3: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html">
 <span class="dropdown-text">Tema 4: Media móvil</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html">
 <span class="dropdown-text">Tema 5: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html">
 <span class="dropdown-text">Tema 6: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html">
 <span class="dropdown-text">Tema 7: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo2.html">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo3.html">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo4.html">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo5.html">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-12-Ejemplo6.html">
 <span class="dropdown-text">Ejemplo Tema 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo7.html">
 <span class="dropdown-text">Ejemplo Tema 7</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo-Pasajeros.html">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">Píldoras</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Pasajeros.html">
 <span class="dropdown-text">Efecto de la Covid-19 en Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html">Recursos de la asignatura</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html">Evaluacion Continua</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false">Más</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="toc-section-number">1</span>  Introducción</a></li>
  <li><a href="#transformaciones-de-una-serie-con-estacionalidad" id="toc-transformaciones-de-una-serie-con-estacionalidad" class="nav-link" data-scroll-target="#transformaciones-de-una-serie-con-estacionalidad"><span class="toc-section-number">2</span>  Transformaciones de una serie con estacionalidad</a>
  <ul class="collapse">
  <li><a href="#diferenciación-estacional" id="toc-diferenciación-estacional" class="nav-link" data-scroll-target="#diferenciación-estacional"><span class="toc-section-number">2.1</span>  Diferenciación estacional</a></li>
  <li><a href="#diferencia-logaritmo-y-tasa-de-variación" id="toc-diferencia-logaritmo-y-tasa-de-variación" class="nav-link" data-scroll-target="#diferencia-logaritmo-y-tasa-de-variación"><span class="toc-section-number">2.2</span>  Diferencia, Logaritmo y Tasa de variación</a></li>
  </ul></li>
  <li><a href="#procesos-arima-con-estacionalidad" id="toc-procesos-arima-con-estacionalidad" class="nav-link" data-scroll-target="#procesos-arima-con-estacionalidad"><span class="toc-section-number">3</span>  Procesos ARIMA con estacionalidad</a>
  <ul class="collapse">
  <li><a href="#procesos-autorregresivos-ar_mp" id="toc-procesos-autorregresivos-ar_mp" class="nav-link" data-scroll-target="#procesos-autorregresivos-ar_mp"><span class="toc-section-number">3.1</span>  Procesos autorregresivos <span class="math inline">\(AR_m(P)\)</span></a>
  <ul class="collapse">
  <li><a href="#definición" id="toc-definición" class="nav-link" data-scroll-target="#definición">Definición</a></li>
  <li><a href="#ejemplos" id="toc-ejemplos" class="nav-link" data-scroll-target="#ejemplos">Ejemplos</a></li>
  </ul></li>
  <li><a href="#procesos-en-medias-móviles-ma_mq" id="toc-procesos-en-medias-móviles-ma_mq" class="nav-link" data-scroll-target="#procesos-en-medias-móviles-ma_mq"><span class="toc-section-number">3.2</span>  Procesos en medias móviles <span class="math inline">\(MA_m(Q)\)</span></a>
  <ul class="collapse">
  <li><a href="#definición-1" id="toc-definición-1" class="nav-link" data-scroll-target="#definición-1">Definición</a></li>
  <li><a href="#ejemplos-1" id="toc-ejemplos-1" class="nav-link" data-scroll-target="#ejemplos-1">Ejemplos</a></li>
  </ul></li>
  <li><a href="#procesos-arma_mpq" id="toc-procesos-arma_mpq" class="nav-link" data-scroll-target="#procesos-arma_mpq"><span class="toc-section-number">3.3</span>  Procesos <span class="math inline">\(ARMA_m(P,Q)\)</span></a>
  <ul class="collapse">
  <li><a href="#definición-2" id="toc-definición-2" class="nav-link" data-scroll-target="#definición-2">Definición</a></li>
  <li><a href="#ejemplos-2" id="toc-ejemplos-2" class="nav-link" data-scroll-target="#ejemplos-2">Ejemplos</a></li>
  </ul></li>
  <li><a href="#procesos-arima_mpdq" id="toc-procesos-arima_mpdq" class="nav-link" data-scroll-target="#procesos-arima_mpdq"><span class="toc-section-number">3.4</span>  Procesos <span class="math inline">\(ARIMA_m(P,D,Q)\)</span></a>
  <ul class="collapse">
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo">Ejemplo</a></li>
  </ul></li>
  <li><a href="#proceso-arima_mpdqpdq" id="toc-proceso-arima_mpdqpdq" class="nav-link" data-scroll-target="#proceso-arima_mpdqpdq"><span class="toc-section-number">3.5</span>  Proceso <span class="math inline">\(ARIMA_m(p,d,q)(P,D,Q)\)</span></a></li>
  </ul></li>
  <li><a href="#ejemplos-3" id="toc-ejemplos-3" class="nav-link" data-scroll-target="#ejemplos-3"><span class="toc-section-number">4</span>  Ejemplos</a>
  <ul class="collapse">
  <li><a href="#nacimientos" id="toc-nacimientos" class="nav-link" data-scroll-target="#nacimientos"><span class="toc-section-number">4.1</span>  Nacimientos</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie" id="toc-transformación-de-la-serie" class="nav-link" data-scroll-target="#transformación-de-la-serie">Transformación de la serie</a></li>
  <li><a href="#identificación" id="toc-identificación" class="nav-link" data-scroll-target="#identificación">Identificación</a></li>
  <li><a href="#estimación-y-valores-extremos" id="toc-estimación-y-valores-extremos" class="nav-link" data-scroll-target="#estimación-y-valores-extremos">Estimación (y valores extremos)</a></li>
  <li><a href="#validación" id="toc-validación" class="nav-link" data-scroll-target="#validación">Validación</a></li>
  <li><a href="#error-de-estimación" id="toc-error-de-estimación" class="nav-link" data-scroll-target="#error-de-estimación">Error de estimación</a></li>
  <li><a href="#error-de-predicción-extra-muestral-según-horizonte-temporal" id="toc-error-de-predicción-extra-muestral-según-horizonte-temporal" class="nav-link" data-scroll-target="#error-de-predicción-extra-muestral-según-horizonte-temporal">Error de predicción extra-muestral según horizonte temporal</a></li>
  <li><a href="#interpretación" id="toc-interpretación" class="nav-link" data-scroll-target="#interpretación">Interpretación</a></li>
  <li><a href="#predicción-de-la-serie" id="toc-predicción-de-la-serie" class="nav-link" data-scroll-target="#predicción-de-la-serie">Predicción de la serie</a></li>
  </ul></li>
  <li><a href="#exportaciones" id="toc-exportaciones" class="nav-link" data-scroll-target="#exportaciones"><span class="toc-section-number">4.2</span>  Exportaciones</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-1" id="toc-transformación-de-la-serie-1" class="nav-link" data-scroll-target="#transformación-de-la-serie-1">Transformación de la serie</a></li>
  <li><a href="#identificación-1" id="toc-identificación-1" class="nav-link" data-scroll-target="#identificación-1">Identificación</a></li>
  <li><a href="#estimación-y-valores-extremos-1" id="toc-estimación-y-valores-extremos-1" class="nav-link" data-scroll-target="#estimación-y-valores-extremos-1">Estimación (y valores extremos)</a></li>
  <li><a href="#validación-1" id="toc-validación-1" class="nav-link" data-scroll-target="#validación-1">Validación</a></li>
  <li><a href="#error-de-estimación-1" id="toc-error-de-estimación-1" class="nav-link" data-scroll-target="#error-de-estimación-1">Error de estimación</a></li>
  <li><a href="#error-de-predicción-extra-muestral-según-horizonte-temporal-1" id="toc-error-de-predicción-extra-muestral-según-horizonte-temporal-1" class="nav-link" data-scroll-target="#error-de-predicción-extra-muestral-según-horizonte-temporal-1">Error de predicción extra-muestral según horizonte temporal</a></li>
  <li><a href="#interpretación-1" id="toc-interpretación-1" class="nav-link" data-scroll-target="#interpretación-1">Interpretación</a></li>
  <li><a href="#predicción-de-la-serie-1" id="toc-predicción-de-la-serie-1" class="nav-link" data-scroll-target="#predicción-de-la-serie-1">Predicción de la serie</a></li>
  </ul></li>
  <li><a href="#chocolate" id="toc-chocolate" class="nav-link" data-scroll-target="#chocolate"><span class="toc-section-number">4.3</span>  Chocolate</a>
  <ul class="collapse">
  <li><a href="#transformación-de-la-serie-2" id="toc-transformación-de-la-serie-2" class="nav-link" data-scroll-target="#transformación-de-la-serie-2">Transformación de la serie</a></li>
  <li><a href="#identificación-2" id="toc-identificación-2" class="nav-link" data-scroll-target="#identificación-2">Identificación</a></li>
  <li><a href="#estimación" id="toc-estimación" class="nav-link" data-scroll-target="#estimación">Estimación</a></li>
  <li><a href="#validación-2" id="toc-validación-2" class="nav-link" data-scroll-target="#validación-2">Validación</a></li>
  <li><a href="#error-de-estimación-2" id="toc-error-de-estimación-2" class="nav-link" data-scroll-target="#error-de-estimación-2">Error de estimación</a></li>
  <li><a href="#error-de-predicción-extra-muestral-según-horizonte-temporal-2" id="toc-error-de-predicción-extra-muestral-según-horizonte-temporal-2" class="nav-link" data-scroll-target="#error-de-predicción-extra-muestral-según-horizonte-temporal-2">Error de predicción extra-muestral según horizonte temporal</a></li>
  <li><a href="#interpretación-2" id="toc-interpretación-2" class="nav-link" data-scroll-target="#interpretación-2">Interpretación</a></li>
  <li><a href="#predicción-de-la-serie-2" id="toc-predicción-de-la-serie-2" class="nav-link" data-scroll-target="#predicción-de-la-serie-2">Predicción de la serie</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparación-con-el-método-de-alisado-exponencial" id="toc-comparación-con-el-método-de-alisado-exponencial" class="nav-link" data-scroll-target="#comparación-con-el-método-de-alisado-exponencial"><span class="toc-section-number">5</span>  Comparación con el método de alisado exponencial</a>
  <ul class="collapse">
  <li><a href="#nacimientos-log" id="toc-nacimientos-log" class="nav-link" data-scroll-target="#nacimientos-log">Nacimientos (log)</a></li>
  <li><a href="#exportaciones-log" id="toc-exportaciones-log" class="nav-link" data-scroll-target="#exportaciones-log">Exportaciones (log)</a></li>
  <li><a href="#chocolate-log" id="toc-chocolate-log" class="nav-link" data-scroll-target="#chocolate-log">Chocolate (log)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Procesos ARIMA con estacionalidad</h1>
<p class="subtitle lead">Previsión con Datos Temporales (GBIA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">

</div>
<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>En general, la capacidad de toma de datos posibilita que el fechado de las series sea inferior al año, apareciendo la componente estacional. No es difícil disponer de series mensuales, trimestrales, diarias o incluso con frecuencia superior.</p>
<p>En este tema revisaremos los conocimientos del tema previo, ampliándolos a fin de contemplar la presencia de estacionalidad en las series temporales</p>
<p>Se mantienen las hipótesis sobre el proceso generador de datos, <em>estacionario</em> y <em>ergódico</em>.</p>
<p>Recuerda que <span class="math inline">\(m\)</span> es el orden estacional.</p>
<p><br>
<br>
</p>
</section>
<section id="transformaciones-de-una-serie-con-estacionalidad" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Transformaciones de una serie con estacionalidad</h1>
<p>En el el tema previo vimos como usar la diferenciación regular para conseguir que una serie no estacionaria pase a serlo. También vimos la transformación logarítmica que puede ayudar a interpretar mejor el modelo estimado cuando la serie ha sido diferenciada.</p>
<p>Veamos estas mismas transformaciones en el contexto de una serie con estacionalidad.</p>
<section id="diferenciación-estacional" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="diferenciación-estacional"><span class="header-section-number">2.1</span> Diferenciación estacional</h2>
<p>La <strong>diferencia estacional</strong> consiste en restar a la observación de un periodo la observación precedente de la misma estación. Si el orden estacional es <span class="math inline">\(m\)</span>, entonces la diferencia estacional de <span class="math inline">\(y_t\)</span> es <span class="math display">\[\nabla_m y_t = y_t - y_{t-m}.\]</span> Una serie no estacionaria en media puede pasar a serlo tras diferenciarla estacionalmente. Es general, cualquiera de las dos diferenciaciones vistas (regular o estacional) o ambas a la vez son alternativas para obtener la estacionariedad.</p>
<p>Además, <strong>la diferenciación (regular, estacional o ambas) también permite alcanzar la ergodicidad</strong>.</p>
<p>La <a href="#fig-NacimientosDif">Figura&nbsp;1</a> muestra un ejemplo de diferenciación regular y/o estacional. En el primer panel aparece la serie original Nacimientos <span class="math inline">\(y_t\)</span>; el segundo panel muestra la serie diferenciada regularmente <span class="math inline">\(\nabla y_t\)</span>; en el tercer panel la serie diferenciada estacionalmente <span class="math inline">\(\nabla_{12} y_t\)</span>; y en el cuarto panel muestra la serie diferenciada regular y estacionalmente <span class="math inline">\(\nabla\nabla_{12} y_t\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-NacimientosDif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacimientosDif-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;1: Nacimientos mensuales y diferenciaciones</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><em>¿Qué transformación para nacimientos consideras que genera una serie estacionaria, tanto en media como en varianza?</em> Siempre hay un cierto grado de subjetividad en la elección de las diferencias que hay que aplicar a una serie. En la <a href="#fig-NacimientosDif">Figura&nbsp;1</a> podemos considerar que la diferenciación regular (panel 2) es suficiente para lograr la estacionariedad en media y en varianza y terminar el proceso de diferenciación. Pero también podemos considerar que la serie es estacionaria en media pero no lo suficiente en varianza, y optar por la doble diferenciación, regular y estacional (panel 4).</p>
<p>Recuerda que <code>diff(x, lag = m)</code> calcula la diferencia de orden <span class="math inline">\(m\)</span>. Si necesitas calcular una diferencia regular y otra estacional, <span class="math inline">\(\nabla\nabla_m y_t\)</span>, debes usar <code>diff(diff(x, lag = m))</code>. El orden de las diferenciaciones no cambia el resultado.</p>
<p>Además, en <code>forecast</code> está disponible la función <code>nsdiffs</code> que estima el número de diferencias estacionales necesarias usando un criterio <em>ad-hoc</em>. Recuerda que también dispones de <code>ndiffs</code> para determinar el número de diferencias regulares.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nsdiffs</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Para nacimientos estas dos funciones sugieren la doble diferenciación regular y estacional. La doble diferenciación es muy usual.</p>
</section>
<section id="diferencia-logaritmo-y-tasa-de-variación" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="diferencia-logaritmo-y-tasa-de-variación"><span class="header-section-number">2.2</span> Diferencia, Logaritmo y Tasa de variación</h2>
<p>Cuando una serie estacional tiene que ser diferenciada dos veces para conseguir su estacionariedad, vale la pena usar la transformación logarítmica para ganar en interpretabilidad. Es decir, frente a <span class="math inline">\(\nabla \nabla_m y_t\)</span> es preferible usar <span class="math inline">\(\nabla \nabla_m \log(y_t)\)</span>.</p>
<p>Ya vimos que la diferencia regular del logaritmo es una tasa de variación, <span class="math inline">\(\nabla \log(y_t) =TV y_t\)</span>. Por tanto, podemos escribir <span class="math display">\[\nabla \nabla_m \log(y_t) = \nabla_m \nabla \log(y_t) = \nabla_m TV y_t = TV y_t - TV y_{t-m}.\]</span></p>
<p>Por ejemplo, para una serie mensual, <em>la diferencia regular del logaritmo (natural) es la Tasa de Variación Mensual de la serie</em> <span class="math inline">\((\nabla \log(y_t)=TVM y_t)\)</span> y la doble diferenciación es seria <span class="math inline">\(TVM y_t - TVM y_{t-12}\)</span>.</p>
<p>Si se opta por la diferencia estacional, entonces <span class="math inline">\(\nabla_m \log(y_t) \approx \frac{y_t - y_{t-m}}{y_{t-m}} =TV_m y_t\)</span> y <span class="math display">\[\nabla \nabla_m \log(y_t) = \nabla TV_m y_t = TV_m y_t - TV_m y_{t-1}.\]</span></p>
<p>Es decir, para una serie mensual <em>la diferencia estacional del logaritmo es la Tasa de Variación Anual de la serie</em> <span class="math inline">\((\nabla_{12} \log(y_t)=TVA y_t)\)</span> y la doble diferenciación seria <span class="math inline">\(TVA y_t - TVA y_{t-1}\)</span>.</p>
<p><br>
</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
La diferenciacion y el logaritmo en series con estacionalidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si se tiene una serie con estacionalidad y no estacionaria, lo usual es tener que diferenciarla una vez (regular o estacionalmente) o aplicar ambas diferenciaciones para que sea estacionaria en media, en sentido amplio y ergódica.</p>
<p>Si hay una doble diferenciación, la transformación logarítmica se puede usar para ganar en interpretabilidad o para intentar mejorar las predicciones. La transformación logarítmica no es necesaria para alcanzar la estacionariedad de la serie.</p>
</div>
</div>
<p><br>
<br>
</p>
</section>
</section>
<section id="procesos-arima-con-estacionalidad" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Procesos ARIMA con estacionalidad</h1>
<section id="procesos-autorregresivos-ar_mp" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="procesos-autorregresivos-ar_mp"><span class="header-section-number">3.1</span> Procesos autorregresivos <span class="math inline">\(AR_m(P)\)</span></h2>
<section id="definición" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición">Definición</h3>
<p>El modelo general <strong>autorregresivo estacional de orden P</strong>, <span class="math inline">\(y_t \sim AR_m(P)\)</span> viene definido por <span class="math display">\[y_t=c + \phi_m y_{t-m} + \phi_{2m} y_{t-2m} + \ldots + \phi_{Pm} y_{t-Pm} + \varepsilon_t,\]</span> que usando el operador retardo queda <span class="math display">\[(1 - \phi_m L^m - \phi_{2m} L^{2m} - \ldots - \phi_{Pm} L^{Pm})y_t = c + \varepsilon_t.\]</span></p>
</section>
<section id="ejemplos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim AR_{12}(1):\;\;y_t = c + \phi_{12} y_{t-12} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_{12} L^{12})y_t = c + \varepsilon_t\)</span></li>
<li><span class="math inline">\(y_t \sim AR_7(2):\;\;y_t = c + \phi_7 y_{t-7} + \phi_{14} y_{t-14} + \varepsilon_t\)</span> o <span class="math inline">\((1 - \phi_7 L^7 - \phi_{14} L^{14})y_t = c + \varepsilon_t\)</span></li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="procesos-en-medias-móviles-ma_mq" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="procesos-en-medias-móviles-ma_mq"><span class="header-section-number">3.2</span> Procesos en medias móviles <span class="math inline">\(MA_m(Q)\)</span></h2>
<section id="definición-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-1">Definición</h3>
<p>El modelo general <strong>en medias móviles estacional de orden Q</strong>, <span class="math inline">\(y_t \sim MA_m(Q)\)</span> viene definido por <span class="math display">\[y_t=c + \varepsilon_t + \theta_m \varepsilon_{t-m} + \theta_{2m} \varepsilon_{t-2m} + \ldots +
  \theta_{Qm} \varepsilon_{t-Qm},\]</span> que usando el operador retardo queda <span class="math display">\[y_t = c + (1 + \theta_m L^m + \theta_{2m} L^{2m} + \ldots + \theta_{Qm} L^{Qm}) \varepsilon_t.\]</span></p>
</section>
<section id="ejemplos-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-1">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim MA_7(1):\;\;y_t = c + \varepsilon_t + \theta_7 \varepsilon_{t-7}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_7 L^7)\varepsilon_t\)</span></li>
<li><span class="math inline">\(y_t \sim MA_{12}(2):\;\;y_t=c + \varepsilon_t + \theta_{12} \varepsilon_{t-12} + \theta_{24} \varepsilon_{t-24}\)</span> o <span class="math inline">\(y_t = c + (1 + \theta_{12} L^{12} + \theta_{24} L^{24})\varepsilon_t\)</span></li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="procesos-arma_mpq" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="procesos-arma_mpq"><span class="header-section-number">3.3</span> Procesos <span class="math inline">\(ARMA_m(P,Q)\)</span></h2>
<section id="definición-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definición-2">Definición</h3>
<p>El modelo general <span class="math inline">\(y_t \sim ARMA_m(P,Q)\)</span> viene definido por <span class="math display">\[ y_t = c + \phi_m y_{t-m} + \phi_{2m} y_{t-2m} + \ldots + \phi_{Pm} y_{t-Pm}  +
  \varepsilon_t + \theta_m \varepsilon_{t-m} + \theta_{2m} \varepsilon_{t-2m} + \ldots +
  \theta_{Qm} \varepsilon_{t-Qm},
\]</span> que usando el operador retardo queda <span class="math display">\[(1 - \phi_m L^m - \ldots - \phi_{Pm} L^{Pm})y_t = c + (1 + \theta_m L^m + \ldots + \theta_{Qm} L^{Qm}) \varepsilon_t.\]</span></p>
</section>
<section id="ejemplos-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplos-2">Ejemplos</h3>
<ul>
<li><span class="math inline">\(y_t \sim ARMA_7(1, 1):\;\;y_t = c + \phi_7 y_{t-7} + \theta_7 \varepsilon_{t-7} + \varepsilon_{t}\)</span> o <span class="math inline">\((1 - \phi_7 L^7)y_t = c + (1 + \theta_7 L^7)\varepsilon_t\)</span>.</li>
<li><span class="math inline">\(y_t \sim ARMA_{12}(1, 1):\;\;y_t = c + \phi_{12} y_{t-12} + \theta_{12} \varepsilon_{t-12} + \varepsilon_{t}\)</span> o <span class="math inline">\((1 - \phi_{12} L^{12})y_t = c + (1 + \theta_{12} L^{12})\varepsilon_t\)</span>.</li>
</ul>
<p><br>
</p>
</section>
</section>
<section id="procesos-arima_mpdq" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="procesos-arima_mpdq"><span class="header-section-number">3.4</span> Procesos <span class="math inline">\(ARIMA_m(P,D,Q)\)</span></h2>
<p>Si la serie <span class="math inline">\(y_t\)</span> no es estacionaria en su parte estacional, pero tras diferenciarla <span class="math inline">\(D\)</span> veces se hace estacionaria, diremos que la serie es integrada estacionalmente de orden <span class="math inline">\(D\)</span>: <span class="math inline">\(y_t \sim I_m(D)\)</span>. Por tanto,</p>
<ul>
<li>una serie estacionaria estacionalmente se indicará como <span class="math inline">\(y_t \sim I_m(0)\)</span>.</li>
<li><span class="math inline">\(y_t \sim I_m(1)\)</span> es equivalente a <span class="math inline">\(\nabla_m y_t = (1 - L^m)y_t \sim I_m(0)\)</span></li>
</ul>
<p>Una serie <span class="math inline">\(y_t\)</span> sigue un proceso <span class="math inline">\(ARIMA_m(P,D,Q)\)</span> si:</p>
<ol type="1">
<li><span class="math inline">\(y_t \sim I_m(D)\)</span>, hay que diferenciarla estacionalmente <span class="math inline">\(D\)</span> veces para hacerla estacionaria, y</li>
<li><span class="math inline">\(\nabla_m^D y_t \sim ARMA_m(P,Q)\)</span>.</li>
</ol>
<p>Entonces, podemos escribir <span class="math inline">\(y_t \sim ARIMA_m(P,D,Q)\)</span> como <span class="math display">\[\begin{equation*}
\begin{array}{c@{\quad}ccc}
  (1 - \phi_m L^m - \ldots - \phi_{Pm} L^{Pm}) &amp; (1- L^m)^D y_t &amp; = &amp; c + (1 + \theta_m L^m + \ldots + \theta_{Qm} L^{Qm}) \varepsilon_t \\
  \uparrow                                     &amp; \uparrow       &amp;   &amp; \uparrow \\
   AR_m(P)                                     &amp; I_m(D)         &amp;   &amp; MA_m(Q)
\end{array}
\end{equation*}\]</span></p>
<section id="ejemplo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo">Ejemplo</h3>
<p><span class="math inline">\(y_t \sim ARIMA_{12}(1, 1, 1):\;\;(1 - \phi_{12} L^{12})(1- L^{12}) y_t = c + (1 + \theta_{12} L^{12}) \varepsilon_t\)</span> o</p>
<p><span class="math inline">\(y_t = c + y_{t-12} + \phi_{12}(y_{t-12} - y_{t-24}) + \theta_{12} \varepsilon_{t-12} + \varepsilon_t\)</span>.</p>
<p><br>
</p>
</section>
</section>
<section id="proceso-arima_mpdqpdq" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="proceso-arima_mpdqpdq"><span class="header-section-number">3.5</span> Proceso <span class="math inline">\(ARIMA_m(p,d,q)(P,D,Q)\)</span></h2>
<p>La realidad nos muestra que la mayoría de las series con estacionalidad se ajustan a una combinación de <em>procesos regulares y estacionales</em>.</p>
<p>El proceso <span class="math inline">\(ARIMA_m(p, d, q)(P, D, Q)\)</span> puede ser expresado como <span class="math display">\[\begin{equation*}
\begin{array}{ccccc}
  AR(p) &amp; AR_m(P) &amp; I(d) &amp; I_m(D) &amp;  \\
  \downarrow &amp; \downarrow &amp; \downarrow &amp; \downarrow  &amp;  \\
  (1 - \phi_1 L - \ldots - \phi_p L^p) &amp; (1 - \phi_m L^m - \ldots - \phi_{Pm} L^{Pm}) &amp; (1 - L)^d &amp; (1- L^m)^Dy_t &amp; = \\
  c + (1 + \theta_1 L + \ldots + \theta_q L^q) &amp; (1 + \theta_m L^m + \ldots + \theta_{Qm} L^{Qm}) \varepsilon_t &amp; &amp; &amp; \\
  \uparrow &amp; \uparrow &amp; &amp; &amp; \\
  MA(q) &amp; MA_m(Q)  &amp; &amp; &amp;
\end{array}
\end{equation*}\]</span></p>
<p>Por ejemplo, entre las series mensuales uno de los procesos más comunes es <span class="math inline">\(ARIMA_{12}(0, 1, 1)(0, 1, 1)\)</span>, denominado <em>modelo de las aerolíneas</em> por ser el proceso generador de datos de muchas series mensuales de transporte de pasajeros, en concreto la serie mensual de pasajeros de avión. La ecuación de este modelo es</p>
<p><span class="math display">\[(1-L)(1-L^{12})y_t = (1+ \theta_1L)(1 + \theta_{12}L^{12})\varepsilon_t\]</span> que si desarrollamos queda <span class="math display">\[y_t = y_{t-1} + (y_{t-12} - y_{t-13}) + \theta_1 \varepsilon_{t-1} + \theta_{12} \varepsilon_{t-12} + \theta_{1}\theta_{12} \varepsilon_{t-13} + \varepsilon_t \]</span></p>
<ul>
<li>El número de pasajeros del mes <span class="math inline">\(t\)</span> es el mismo que el del mes previo <span class="math inline">\(t-1\)</span>, más la diferencia entre estos meses observada el año pasado.</li>
<li>Si en los meses usados para la predicción (<span class="math inline">\(t-1\)</span>, <span class="math inline">\(t-12\)</span> y <span class="math inline">\(t-12\)</span>) ha ocurrido algo extraordinario, hay que tenerlo en cuenta a la hora de afinar la predicción.</li>
</ul>
<p>Si usamos la <strong>transformación logarítmica</strong>, tendríamos <span class="math display">\[(1-L)(1-L^{12})\log(y_t) = (1+ \theta_1L)(1 + \theta_{12}L^{12})\varepsilon_t\]</span> o <span class="math display">\[(1-L)TVAy_t = (1+ \theta_1L)(1 + \theta_{12}L^{12})\varepsilon_t\]</span> que desarrollando queda <span class="math display">\[TVAy_t = TVAy_{t-1} + \theta_1 \varepsilon_{t-1} + \theta_{12} \varepsilon_{t-12} + \theta_{1}\theta_{12} \varepsilon_{t-13} + \varepsilon_t \]</span></p>
<ul>
<li>La tasa de variación anual en el número de pasajeros del mes <span class="math inline">\(t\)</span> es la misma que la del mes previo <span class="math inline">\(t-1\)</span>.</li>
<li>Si en los meses usados para la predicción (<span class="math inline">\(t-1\)</span>, <span class="math inline">\(t-12\)</span> y <span class="math inline">\(t-12\)</span>) ha ocurrido algo extraordinario, hay que tenerlo en cuenta a la hora de afinar la predicción.</li>
</ul>
<p><br>
<br>
</p>
</section>
</section>
<section id="ejemplos-3" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Ejemplos</h1>
<section id="nacimientos" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="nacimientos"><span class="header-section-number">4.1</span> Nacimientos</h2>
<p>Vamos a aplicar la metodología de Box-Jenkins a la serie de <strong>nacimientos en España</strong> desde el año 2000 (véase <a href="#fig-Nacimientos">Figura&nbsp;2</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/nacimientos.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">ts</span>(nacimientos[, <span class="dv">2</span>],</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1975</span>, <span class="dv">1</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">freq =</span> <span class="dv">12</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>nacimientos <span class="ot">&lt;-</span> <span class="fu">window</span>(nacimientos, <span class="at">start =</span> <span class="dv">2000</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(nacimientos,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Nacimientos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-Nacimientos-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: Nacimientos mensuales</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="transformación-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie">Transformación de la serie</h3>
<p>Ya hemos visto en el epígrafe previo que para que la serie sea estacionaria hay que diferenciarla regularmente y estacionalmente. Veamos ahora que transformación es necesaria para que sea ergódica. Además, trabajaremos con el logaritmo de la serie para ganar en interpretabilidad.</p>
<p>Observa el diferente uso que hacemos del argumento <code>lag</code>. Como argumento de la función <code>diff</code> indica el orden estacional de la diferenciación y vale 12 (<code>lag = 12</code>). Como argumento de la función <code>ggAcf</code> indica el número de autocorrelaciones que queremos mostrar y lo hemos fijado en 48 (<code>lag = 48</code>) para ver al menos lo que ocurre en 4 años.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(nacimientos), <span class="at">lag =</span> <span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-NacFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-NacFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-NacFAC"></p>
<p></p><figcaption class="figure-caption">(b) Diferencia regular</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-NacFAC"></p>
<p></p><figcaption class="figure-caption">(c) Diferencia estacional</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-NacFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-NacFAC"></p>
<p></p><figcaption class="figure-caption">(d) Diferencia regular y estacional</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura&nbsp;3: FAC para Nacimientos (log)</figcaption><p></p>
</figure>
</div>
<p>Para que la serie sea ergódica también es necesaria la doble diferenciación regular y estacional. Es decir, trabajaremos con la siguiente serie transformada <span class="math display">\[\nabla\nabla_{12}\log(nacimientos_t) \sim I(0)I_{12}(0).\]</span></p>
</section>
<section id="identificación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación">Identificación</h3>
<p>¿Qué nos indica <code>auto.arima</code>? Primero vamos a generar e incluir en el proceso de auto-identificación las variables asociadas a los efectos de intervención que hemos detectado en los temas previos. En concreto, hemos visto que el número de días del mes explica el número de nacimientos. Este efecto era muy claro para los meses de febrero bisiestos. Para el calculo de la variable que recoge el número de días del mes usaremos la función <code>monthdays</code> de la librería <code>forecast</code> que devuelve el número de días de cada mes o trimestre de una serie.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">monthdays</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
2015  31  28  31  30  31  30  31  31  30  31  30  31
2016  31  29  31  30  31  30  31  31  30  31  30  31
2017  31  28  31  30  31  30  31  31  30  31  30  31
2018  31  28  31  30  31  30  31  31  30  31  30  31
2019  31  28  31  30  31  30  31  31  30  31  30  31</code></pre>
</div>
</div>
<p>Por otro lado, los periodos vacacionales pueden afectar la programación de las cesáreas e influir en el número de nacimientos. Como la Semana Santa es un periodo festivo que puede caer en marzo o abril, dependiendo del año, los nacimientos en estos dos meses pueden variar según como cae la Semana Santa. Para capturar este efecto, usaremos la función <code>easter</code> de la librería <code>forecast</code> que devuelve para cada mes la proporción de días de la Semana Santa que contiene (considerando solo del Viernes Santo al Domingo de Resurrección, tres días).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">easter</span>(nacimientos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
2015 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2016 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2017 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2018 0.00 0.00 0.67 0.33 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2019 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00</code></pre>
</div>
</div>
<p>Además, en enero de 2011 el número de nacimientos era atípico.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>DiasMes <span class="ot">&lt;-</span> <span class="fu">monthdays</span>(nacimientos)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">easter</span>(nacimientos)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>d0111 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(nacimientos) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(nacimientos)) <span class="sc">==</span> <span class="dv">2011</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(nacimientos, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">D =</span> <span class="dv">1</span>, </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta, d0111))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: nacimientos 
Regression with ARIMA(0,1,1)(0,1,2)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1     sma2  DiasMes  SemanaSanta    d0111
      -0.4544  -0.6131  -0.1738   0.0341      -0.0156  -0.0694
s.e.   0.0666   0.0674   0.0668   0.0078       0.0047   0.0164

sigma^2 = 0.0004364:  log likelihood = 555.16
AIC=-1096.31   AICc=-1095.8   BIC=-1072.34</code></pre>
</div>
</div>
<p>Indica <span class="math inline">\(ARIMA_{12}(0,1,1)(0,1,2)\)</span>.</p>
<p><br>
</p>
<p>Una alternativa a <code>auto.arima</code> es la función <code>seas</code> de la librería <code>seasonal</code>. La función <code>seas</code> tiene como ventajas que también analiza la conveniencia de usar la transformación logarítmica, que identifica posibles efectos calendario y valores extremos, y que suele ser más parsimoniosa que <code>auto.arima</code>. Su desventaja es que sólo se puede aplicar para series mensuales o trimestrales. Veamos que identificación ofrece <code>seas</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">seas</span>(nacimientos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
seas(x = nacimientos)

Coefficients:
                    Estimate Std. Error z value             Pr(&gt;|z|)    
Weekday            0.0028161  0.0002681  10.504 &lt; 0.0000000000000002 ***
Easter[1]         -0.0127198  0.0037801  -3.365             0.000766 ***
AO2010.Dec         0.0656998  0.0133509   4.921         0.0000008611 ***
MA-Nonseasonal-01  0.3447018  0.0612765   5.625         0.0000000185 ***
MA-Seasonal-12     0.7477045  0.0466619  16.024 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 240  Transform: log
AICc:  3597, BIC:  3617  QS (no seasonality in final):    0  
Box-Ljung (no autocorr.): 27.65   Shapiro (normality): 0.993  </code></pre>
</div>
</div>
<p>En primer lugar, la función identifica el modelo de las aerolíneas para la transformación logarítmica de Nacimientos. Este resultado está en consonancia con el alcanzado con la función <code>auto.arima</code>. Además, identifica un valor extremo en diciembre de 2010, un efecto calendario Semana Santa y un efecto calendario días laborables del mes (que podemos entender similar a nuestro efecto días del mes).</p>
<p>Tras estos análisis alternativos, decidimos que la identificación de partida es <span class="math inline">\(ARIMA_{12}(0,1,1)(0,1,2)+AI\)</span>, <span class="math display">\[(1 - L^{12})(1 - L)\log(nacimientos_t) = (1 + \theta_1 L)(1 + \theta_{12} L^{12} + \theta_{24} L^{24})\varepsilon_t + AI.\]</span> donde <em>AI</em> recoge las variables de intervención incluidas en <code>auto.arima</code> y la identificada por <code>seas</code>.</p>
</section>
<section id="estimación-y-valores-extremos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación-y-valores-extremos">Estimación (y valores extremos)</h3>
<p>Vamos a estimar el modelo identificado, incluidas las variables de intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>d1210 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(nacimientos) <span class="sc">==</span> <span class="dv">12</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(nacimientos)) <span class="sc">==</span> <span class="dv">2010</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>nac.ar1 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(nacimientos, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta, d1210,  d0111))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>nac.ar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: nacimientos 
Regression with ARIMA(0,1,1)(0,1,2)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1     sma2  DiasMes  SemanaSanta   d1210    d0111
      -0.4835  -0.6222  -0.1545   0.0330      -0.0156  0.0583  -0.0532
s.e.   0.0649   0.0698   0.0698   0.0077       0.0046  0.0168   0.0166

sigma^2 = 0.0004167:  log likelihood = 561.17
AIC=-1106.34   AICc=-1105.68   BIC=-1078.94</code></pre>
</div>
</div>
<p>Ya tenemos un modelo de partida, veamos si es necesaria más intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nac.ar1)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>,<span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2020</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Se observa que hay tres candidatos a valores atípicos en diciembre 2006, abril de 2016 y junio de 2016, dado que los errores asociados se acercan o superan las 3 desviaciones típicas. Por tanto,</p>
<ul>
<li>Se crea una variable de intervención para cada caso</li>
<li>Se estima de nuevo el modelo incluyendo estas variables (<code>auto.arima</code> identifica el mismo modelo).</li>
<li>Se vuelve a analizar si quedan valores atípicos</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>d1206 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(nacimientos) <span class="sc">==</span> <span class="dv">12</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(nacimientos)) <span class="sc">==</span> <span class="dv">2006</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>d0416 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(nacimientos) <span class="sc">==</span> <span class="dv">4</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(nacimientos)) <span class="sc">==</span> <span class="dv">2016</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>d0616 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(nacimientos) <span class="sc">==</span> <span class="dv">6</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(nacimientos)) <span class="sc">==</span> <span class="dv">2016</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>nac.ar2 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(nacimientos, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta, </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                              d1206, d1210, d0111, d0416, d0616))</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>nac.ar2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: nacimientos 
Regression with ARIMA(0,1,1)(0,1,2)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1     sma2  DiasMes  SemanaSanta    d1206   d1210    d0111
      -0.4427  -0.6395  -0.1399   0.0321      -0.0206  -0.0404  0.0559  -0.0545
s.e.   0.0690   0.0730   0.0742   0.0073       0.0046   0.0155  0.0160   0.0158
        d0416   d0616
      -0.0504  0.0293
s.e.   0.0161  0.0152

sigma^2 = 0.0003855:  log likelihood = 571.64
AIC=-1121.28   AICc=-1120.05   BIC=-1083.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nac.ar2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2020</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacError2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacError2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;5: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Es posible que alguno de los errores más elevados corresponda a un intervención, pero a fin de no alargar este ejemplo vamos a asumir que ya no hay valores extremos.</p>
</section>
<section id="validación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación">Validación</h3>
<p>Por último, veamos si todos los coeficientes del modelo son significativos. Para ello, aplicamos la prueba de Wald.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(nac.ar2)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(nac.ar2))) {</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(nac.ar2), </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(nac.ar2), </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(nac.ar2))[i], <span class="at">width =</span> ancho), </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ma1           valor de p:  0.0000
Coeficiente:  sma1          valor de p:  0.0000
Coeficiente:  sma2          valor de p:  0.0592
Coeficiente:  DiasMes       valor de p:  0.0000
Coeficiente:  SemanaSanta   valor de p:  0.0000
Coeficiente:  d1206         valor de p:  0.0092
Coeficiente:  d1210         valor de p:  0.0005
Coeficiente:  d0111         valor de p:  0.0006
Coeficiente:  d0416         valor de p:  0.0018
Coeficiente:  d0616         valor de p:  0.0545</code></pre>
</div>
</div>
<p>El coeficiente estacional en medias móviles de orden dos no resulta <em>individualmente</em> significativo al 5% (aunque si lo sería al 10%). Vamos a optar por eliminarlo. Tampoco es significativo el coeficiente de la intervención de junio de 2016, sin embargo su efecto (<a href="#fig-NacError">Figura&nbsp;4</a>) es tan patente que vamos a dejarlo en el modelo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>nac.ar2 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(nacimientos, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seasonal =</span>  <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                              d1206, d1210, d0111, d0416, d0616))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>nac.ar2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: nacimientos 
Regression with ARIMA(0,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1  DiasMes  SemanaSanta    d1206   d1210    d0111    d0416
      -0.4758  -0.7522   0.0317      -0.0209  -0.0469  0.0606  -0.0559  -0.0510
s.e.   0.0629   0.0478   0.0077       0.0049   0.0156  0.0163   0.0162   0.0166
       d0616
      0.0295
s.e.  0.0158

sigma^2 = 0.0003898:  log likelihood = 569.88
AIC=-1119.75   AICc=-1118.73   BIC=-1085.5</code></pre>
</div>
</div>
</section>
<section id="error-de-estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-estimación">Error de estimación</h3>
<p>El error medio de -76 es muy bajo en comparación con el valor medio de la serie, es decir, no hay sesgo.</p>
<p>En media nos equivocamos en 706 bebés (RMSE) y el error porcentual medio es del 1.5%.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(nac.ar2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                 ME   RMSE   MAE   MPE MAPE MASE ACF1
Training set -75.89 705.77 568.9 -0.22 1.54 0.41 0.02</code></pre>
</div>
</div>
</section>
<section id="error-de-predicción-extra-muestral-según-horizonte-temporal" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-predicción-extra-muestral-según-horizonte-temporal">Error de predicción extra-muestral según horizonte temporal</h3>
<p>Asumimos que se precisan diez años para hacer una buena estimación, <span class="math inline">\(k = 120\)</span>, y fijaremos el horizonte temporal en un año, <span class="math inline">\(h = 12\)</span> meses.</p>
<p>El código es aun más complejo que el visto en el tema previo. Por un lado, hemos de tener en cuenta que hay variables de intervención y por otro lado que la función <code>Arima</code> podría fallar en el proceso de estimación.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">120</span>                   </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span>                    </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(nacimientos)   </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span>T <span class="sc">-</span> k <span class="sc">-</span> h               </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(DiasMes, SemanaSanta, d1206, d1210, d0111, d0416, d0616))</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(nacimientos, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(nacimientos, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg=</span><span class="fu">as.matrix</span>(X.train)))</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>))</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.element</span>(<span class="st">"try-error"</span>, <span class="fu">class</span>(fit))) {</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) </span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>      fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test)) <span class="cf">else</span></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>        fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>    mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a>errorArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a>errorArima</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.890887 2.103159 2.253288 2.574191 2.539895 2.593832 2.764437 2.746884
 [9] 2.824433 3.054107 3.139687 3.277289</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> errorArima), <span class="at">colour =</span> <span class="st">"Blue"</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Horizonte temporal de predicción"</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"%"</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacMAPE" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacMAPE-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;6: Error de predicción (MAPE) según horizonte temporal</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-NacMAPE">Figura&nbsp;6</a> revela que el error de predicción aumenta de forma regular según aumenta el horizonte de predicción, pero incluso a un año vista, se mantiene bajo.</p>
</section>
<section id="interpretación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación">Interpretación</h3>
<p>El <em>modelo teórico</em> es <span class="math inline">\(log(nacimientos) \sim ARIMA_{12}(0, 1, 1)(0, 1, 1) + AI\)</span>, <span class="math display">\[(1 - L^{12})(1 - L)\log(nacimientos_t) = (1 + \theta_1 L)(1 + \theta_{12} L^{12})\varepsilon_t + AI.\]</span></p>
<p>Si sustituimos <span class="math inline">\((1 - L^{12})\log(nacimientos_t)\)</span> por <span class="math inline">\(TVA_{nacimientos_t}\)</span>, la tasa de variación anual de los nacimientos, y desarrollamos queda <span class="math display">\[TVA_{nacimientos_t} = TVA_{nacimientos_{t-1}} + \theta_1 \varepsilon_{t-1} + \theta_{12} \varepsilon_{t-12} + \theta_1\theta_{12} \varepsilon_{t-13} +  \varepsilon_{t}+\]</span> <span class="math display">\[\gamma_1 \cdot DiasMes_t + \gamma_2 \cdot SemanaSanta +\gamma_3 \cdot d1206_t + \gamma_4 \cdot d1210_t +\gamma_5 \cdot d0111_t +\]</span> <span class="math display">\[\gamma_6 \cdot d0416_t + \gamma_7 \cdot d0616_t.\]</span></p>
<p>Finalmente, el <em>modelo estimado</em> es, <span class="math display">\[\widehat{TVA}_{nacimientos_{t}} = TVA_{nacimientos_{t-1}}  - 0.48\varepsilon_{t-1} - 0.75\varepsilon_{t-12} + 0.36\varepsilon_{t-13} + \]</span> <span class="math display">\[0.032 \cdot DiasMes_t - 0.021 \cdot SemanaSanta - 0.047 \cdot d1206_t + 0.061 \cdot d1210_t\]</span> <span class="math display">\[- 0.056 \cdot d0111_t - 0.051 \cdot d0416_t + 0.029 \cdot d0616_t.\]</span></p>
<ul>
<li><p>En cada mes, <strong>la tasa de variación anual de los nacimientos es la misma que la del mes pasado</strong> (<span class="math inline">\(\widehat{TVA}_{nacimientos_t} = TVA_{nacimientos_{t-1}}\)</span>).</p></li>
<li><p>Además, si algunos de los meses necesarios para predecir fue anómalo, el error hay que tenerlo en cuenta para afinar la previsión.</p></li>
<li><p>Respecto de la intervención, cada día adicional de un mes nacen un 3.2% más bebés. El mes en que cae la Semana Santa los nacimientos caen un 2.1%. Por alguna razón, en diciembre de 2006 hubo un 4.7% menos de nacimientos de lo esperado; en diciembre de 2010 hubo un 6.1% más de nacimientos de lo esperado; en enero de 2011 hubo un 5.6% menos de nacimientos de lo esperado; en abril de 2016 hubo un 5.1% menos de nacimientos de lo esperado; y en junio de 2016 hubo un 2.9% más de nacimientos de lo esperado.</p></li>
</ul>
</section>
<section id="predicción-de-la-serie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-de-la-serie">Predicción de la serie</h3>
<p>Una vez dado por válido el modelo podemos pasar a realizar predicciones. Hay que tener en cuenta que hay siete variables de intervención, dos de ellas son efectos calendario (DiasMes y SemanaSanta), para las que debemos indicar qué valores tomarán en el periodo de predicción. Vamos a fijar el horizonte de predicción en cuatro años y mostrar los resultados numérica (solo para el primer año) y gráficamente (<a href="#fig-NacPre">Figura&nbsp;7</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">48</span>), <span class="at">start =</span> <span class="dv">2020</span>, <span class="at">freq =</span> <span class="dv">12</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>pdm <span class="ot">&lt;-</span> <span class="fu">monthdays</span>(tmp)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>pss <span class="ot">&lt;-</span> <span class="fu">easter</span>(tmp)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>pnac.ar2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(nac.ar2, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h =</span> <span class="dv">48</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg =</span> <span class="fu">cbind</span>(pdm, pss, <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>)), </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>pnac.ar2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2020       29286.50 28174.90 30441.94
Feb 2020       26972.04 25819.03 28176.54
Mar 2020       28726.74 27375.83 30144.31
Apr 2020       27438.92 26041.68 28911.14
May 2020       28708.27 27143.10 30363.69
Jun 2020       27881.72 26268.02 29594.54
Jul 2020       29975.66 28146.16 31924.08
Aug 2020       29934.95 28018.53 31982.45
Sep 2020       29783.82 27792.47 31917.85
Oct 2020       30479.37 28358.83 32758.47
Nov 2020       28584.76 26521.71 30808.28
Dec 2020       28335.74 26219.85 30622.39</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pnac.ar2, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Nacimientos"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2024</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-NacPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-NacPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;7: Nacimientos (2000-2019) y predicción (2020-2023)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="exportaciones" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="exportaciones"><span class="header-section-number">4.2</span> Exportaciones</h2>
<p>Consideremos las serie de <strong>exportaciones de bienes desde España hacía la UE27</strong> (conjunto de 27 países de la Unión Europea, con Reino Unido ya ha excluido). La serie va de enero de 1999 hasta diciembre de 2021 y está en millones de euros.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>exportaciones <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Exportaciones.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>exportaciones <span class="ot">&lt;-</span> <span class="fu">ts</span>(exportaciones,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">1</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">freq =</span> <span class="dv">12</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exportaciones,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Millones de €"</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Exportaciones" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-Exportaciones-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8: Exportaciones de España a la EU27</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="transformación-de-la-serie-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-1">Transformación de la serie</h3>
<p>La <a href="#fig-Exportaciones">Figura&nbsp;8</a> deja claro que la serie precisa ser diferenciada para ser estacionaria. Por la naturaleza de la serie previsiblemente será necesaria la doble diferenciación regular y estacional, y trabajaremos con la transformación logarítmica.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(exportaciones), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(exportaciones)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(exportaciones), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(exportaciones), <span class="at">lag =</span> <span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-ExpFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ExpFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-ExpFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ExpFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-ExpFAC"></p>
<p></p><figcaption class="figure-caption">(b) Diferencia regular</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ExpFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-ExpFAC"></p>
<p></p><figcaption class="figure-caption">(c) Diferencia estacional</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ExpFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-ExpFAC"></p>
<p></p><figcaption class="figure-caption">(d) Diferencia regular y estacional</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura&nbsp;9: FAC para Exportaciones (log)</figcaption><p></p>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(<span class="fu">log</span>(exportaciones))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nsdiffs</span>(<span class="fu">log</span>(exportaciones))       </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Para que la serie sea estacionaria y ergódica es necesaria la doble diferenciación regular y estacional. Es decir, trabajaremos con la siguiente serie transformada <span class="math display">\[\nabla\nabla_{12}\log(exportaciones_t) \sim I(0)I_{12}(0).\]</span></p>
</section>
<section id="identificación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-1">Identificación</h3>
<p>La <a href="#fig-Exportaciones">Figura&nbsp;8</a> muestra dos periodos con una marcada intervención: al inicio de la Gran Recesión (2008-2014) y durante el periodo más duro de la Covid-19 en el año 2020. Además, por la naturaleza de la serie es previsible que exista un efecto días del mes o días laborables y un efecto Semana Santa.</p>
<p>Si probamos con la función <code>auto.arima</code>, indicando la doble diferenciación, los días del mes y la Semana Santa, no sugiere <span class="math inline">\(ARIMA_{12}(1,1,1)(2,1,2)\)</span>. Demasiado complejo.</p>
<p>Veamos qué nos indica <code>seas</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">seas</span>(exportaciones))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
seas(x = exportaciones)

Coefficients:
                    Estimate Std. Error z value             Pr(&gt;|z|)    
Weekday            0.0094000  0.0005091  18.462 &lt; 0.0000000000000002 ***
Easter[1]         -0.0671147  0.0073688  -9.108 &lt; 0.0000000000000002 ***
AO2007.Dec        -0.0992204  0.0268412  -3.697             0.000219 ***
LS2008.Dec        -0.2042548  0.0289028  -7.067   0.0000000000015837 ***
LS2020.Mar        -0.2066604  0.0310729  -6.651   0.0000000000291460 ***
AO2020.Apr        -0.3803478  0.0300162 -12.671 &lt; 0.0000000000000002 ***
AO2020.May        -0.1820426  0.0293634  -6.200   0.0000000005659057 ***
MA-Nonseasonal-01  0.4151852  0.0555305   7.477   0.0000000000000762 ***
MA-Seasonal-12     0.6278005  0.0481551  13.037 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 276  Transform: log
AICc:  3871, BIC:  3906  QS (no seasonality in final):    0  
Box-Ljung (no autocorr.): 43.82 ** Shapiro (normality): 0.9953  
Messages generated by X-13:
Warnings:
- At least one visually significant trading day peak has been
  found in one or more of the estimated spectra.</code></pre>
</div>
</div>
<p>El modelo identificado es el de las aerolíneas para la transformación logarítmica de Exportaciones. Respecto de la intervención, identifica dos efectos calendario: días laborables y Semana Santa. También se identifican hasta cinco intervenciones no asociadas a efectos calendario: tres pulsos –intervenciones que afectan un solo mes (AO)– y dos cambios permanentes –intervenciones que afectan un rango elevado de meses (LS):<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<ul>
<li>Un cambio permanente (<em>level shift</em> o LS) empieza en diciembre de 2008. Es decir, la Gran Recesión generó una caída permanente de las exportaciones españolas a la UE27.</li>
<li>El otro cambio permanente empieza en marzo de 2020: el confinamiento generó otra caída permanente de las exportaciones.</li>
<li>También asociado a la Covid-19 están los pulsos de abril y mayo de 2020.</li>
<li>Por último, hay un pulso asociado a diciembre de 2007</li>
</ul>
</section>
<section id="estimación-y-valores-extremos-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación-y-valores-extremos-1">Estimación (y valores extremos)</h3>
<p>Vamos a estimar el modelo identificado con <code>seas</code>, incluidas las variables de intervención. A este respecto unas palabras sobre como obtener los días laborables de un mes.</p>
<p>Entenderemos por días laborables los lunes a viernes de cada mes, menos los días festivos. Este valor se puede obtener con la función <code>bizdays</code>. Un inconveniente de esta función, es que su valor depende de los festivos de cada país. Por ejemplo, en Estados Unidos el día del trabajador se celebra el primer lunes de septiembre, en Reino Unido el primer lunes de mayo y en España el 1 de mayo.</p>
<p>La función <code>bizdays</code> devuelve el número de días laborables de cada mes para determinados centros financieros (equivalentes a países). Por proximidad <em>geográfica</em>, usaremos el calendario de Londres para España.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Para los pulsos, que solo afectan un mes, se crea una variable que vale cero excepto para el mes a intervenir que vale 1.</p>
<p>Para los cambios permanentes que afectan desde un mes en adelante, se crea una variable que vale cero antes del mes de inicio de la intervención y 1 desde ese mes en adelante.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>DiasLaborables <span class="ot">&lt;-</span> <span class="fu">bizdays</span>(exportaciones, <span class="at">FinCenter =</span> <span class="st">"London"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">easter</span>(exportaciones)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>l1208 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">&gt;</span> <span class="dv">2008</span>) <span class="sc">+</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(exportaciones) <span class="sc">==</span> <span class="dv">12</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">==</span> <span class="dv">2008</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>l0320 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">&gt;</span> <span class="dv">2020</span>) <span class="sc">+</span> </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(exportaciones)   <span class="sc">&gt;</span> <span class="dv">2</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>d1207 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(exportaciones) <span class="sc">==</span> <span class="dv">12</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">==</span> <span class="dv">2007</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>d0420 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(exportaciones) <span class="sc">==</span>  <span class="dv">4</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>d0520 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(exportaciones) <span class="sc">==</span>  <span class="dv">5</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(exportaciones)) <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>exp.ar1 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(exportaciones, </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>                 <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasLaborables, SemanaSanta, </span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>                              l1208, l0320, d1207, d0420, d0520))</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>exp.ar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: exportaciones 
Regression with ARIMA(0,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1  DiasLaborables  SemanaSanta    l1208    l0320    d1207
      -0.4248  -0.6283          0.0305      -0.0235  -0.2030  -0.2104  -0.1052
s.e.   0.0527   0.0547          0.0017       0.0085   0.0293   0.0324   0.0274
        d0420    d0520
      -0.3842  -0.1864
s.e.   0.0310   0.0301

sigma^2 = 0.001308:  log likelihood = 501.67
AIC=-983.34   AICc=-982.46   BIC=-947.61</code></pre>
</div>
</div>
<p>Ya tenemos un modelo de partida, en el que parece que todos los coeficientes son significativos. Veamos si es necesaria más intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(exp.ar1)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>,<span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1998</span>, <span class="dv">2022</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ExpError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;10: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Se observan hasta siete candidatos a valores atípicos por superar el error las 2.5 desviaciones típicas. Sin embargo, a fin de aligerar este ejemplo no se van a incluir las variables de intervención asociadas.</p>
</section>
<section id="validación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-1">Validación</h3>
<p>Veamos si los coeficientes del modelo son significativos. Para ello, aplicamos la prueba de Wald.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(exp.ar1)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(exp.ar1))) {</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(exp.ar1), </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(exp.ar1), </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(exp.ar1))[i], <span class="at">width =</span> ancho), </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ma1              valor de p:  0.0000
Coeficiente:  sma1             valor de p:  0.0000
Coeficiente:  DiasLaborables   valor de p:  0.0000
Coeficiente:  SemanaSanta      valor de p:  0.0059
Coeficiente:  l1208            valor de p:  0.0000
Coeficiente:  l0320            valor de p:  0.0000
Coeficiente:  d1207            valor de p:  0.0001
Coeficiente:  d0420            valor de p:  0.0000
Coeficiente:  d0520            valor de p:  0.0000</code></pre>
</div>
</div>
<p>Todos los coeficientes son significativos.</p>
</section>
<section id="error-de-estimación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-estimación-1">Error de estimación</h3>
<p>En media nos equivocamos en 365 millones de euros (RMSE) y el error porcentual medio es del 2.6%, muy reducido.</p>
<p>La serie no presenta sesgo y el intervalo de confianza para las predicciones es válido.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(exp.ar1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                ME   RMSE    MAE   MPE MAPE MASE  ACF1
Training set -5.75 365.16 274.31 -0.17 2.63  0.3 -0.02</code></pre>
</div>
</div>
</section>
<section id="error-de-predicción-extra-muestral-según-horizonte-temporal-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-predicción-extra-muestral-según-horizonte-temporal-1">Error de predicción extra-muestral según horizonte temporal</h3>
<p>Asumimos que se precisan diez años para hacer una buena estimación, <span class="math inline">\(k = 120\)</span>, y fijaremos el horizonte temporal en un año, <span class="math inline">\(h = 12\)</span> meses.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">120</span>                   </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span>                    </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(exportaciones)   </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span>T <span class="sc">-</span> k <span class="sc">-</span> h               </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(DiasLaborables, SemanaSanta, </span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>                      l1208, l0320, d1207, d0420, d0520))</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(exportaciones, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(exportaciones, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg=</span><span class="fu">as.matrix</span>(X.train),</span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">optim.method =</span> <span class="st">"BFGS"</span>))</span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb48-32"><a href="#cb48-32" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb48-33"><a href="#cb48-33" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>))</span>
<span id="cb48-34"><a href="#cb48-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb48-35"><a href="#cb48-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-36"><a href="#cb48-36" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.element</span>(<span class="st">"try-error"</span>, <span class="fu">class</span>(fit))) {</span>
<span id="cb48-37"><a href="#cb48-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) </span>
<span id="cb48-38"><a href="#cb48-38" aria-hidden="true" tabindex="-1"></a>      fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test)) <span class="cf">else</span></span>
<span id="cb48-39"><a href="#cb48-39" aria-hidden="true" tabindex="-1"></a>        fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb48-40"><a href="#cb48-40" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb48-41"><a href="#cb48-41" aria-hidden="true" tabindex="-1"></a>    mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb48-42"><a href="#cb48-42" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb48-43"><a href="#cb48-43" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>errorArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>errorArima</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.794000 3.050736 3.338473 3.650616 3.892606 4.116590 4.313629 4.535789
 [9] 4.626596 4.963904 5.050367 5.351044</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> errorArima), <span class="at">colour =</span> <span class="st">"Blue"</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Horizonte temporal de predicción"</span>) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"%"</span>) <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ExpMAPE" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpMAPE-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;11: Error de predicción (MAPE) según horizonte temporal</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-ExpMAPE">Figura&nbsp;11</a> revela que el error de predicción aumenta lentamente según aumenta el horizonte de predicción, pasando del 2.8% a un mes vista hasta el 5.4% a 12 meses vista.</p>
</section>
<section id="interpretación-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-1">Interpretación</h3>
<p>La parte regular del modelo estimado es la misma que la obtenida para la serie Nacimientos y su interpretación es, por tanto, idéntica: en cada mes, <strong>la tasa de variación anual de las exportaciones es la misma que la del mes pasado</strong>. Además, si algunos de los meses necesarios para predecir fue anómalo, el error hay que tenerlo en cuenta para afinar la previsión.</p>
<p>Vamos por tanto a centrarnos en la interpretación de la intervención:</p>
<ul>
<li>Cada día laborable adicional en un mes aumenta las exportaciones en un 3% (coeficiente <span class="math inline">\(0.0305\)</span> de <code>DiasLAborables</code>)</li>
<li>El mes en que cae la Semana Santa las exportaciones caen un 2.3%. (coeficiente <span class="math inline">\(0.0235\)</span> de <code>SemanaSanta</code>)</li>
<li>A raíz de la Gran Recesión, las exportaciones se redujeron de forma permanente un 20.3% desde diciembre de 2008. Es decir, <strong>sin</strong> la Gran Recesión, las exportaciones ahora serían un 20% superiores (coeficiente <span class="math inline">\(-0.2030\)</span> de <code>l1208</code>)</li>
<li>A raíz de la Covid-19, las exportaciones se redujeron de forma permanente un 21% desde marzo de 2020, inicio del confinamiento (coeficiente <span class="math inline">\(-0.2104\)</span> de <code>l0320</code>).</li>
<li>Además, la caída de las exportaciones por la Covid-19 fue aún más acusada en los meses de marzo y abril de 2020, con una caída adicional (a añadir al 21% ya comentado) del 38% y 19% respectivamente (coeficiente <span class="math inline">\(-0.3842\)</span> de <code>d0320</code> y <span class="math inline">\(-0.1864\)</span> de <code>d0520</code>).</li>
<li>En diciembre de 2007 se observó una caída de las exportaciones del 10.5%.</li>
</ul>
</section>
<section id="predicción-de-la-serie-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-de-la-serie-1">Predicción de la serie</h3>
<p>Una vez dado por válido el modelo, podemos pasar a realizar predicciones teniendo en cuenta las siete variables de intervención:</p>
<ul>
<li>Dos de ellas son efectos calendario (DiasLaborables y SemanaSanta), para las que debemos indicar qué valores tomarán en el periodo de predicción</li>
<li>Otras dos son cambios permanentes y su valor debe ser 1 en el futuro.</li>
<li>Solo para los pulsos, se fijará un valor futuro de 0.</li>
</ul>
<p>Vamos a fijar el horizonte de predicción en cuatro años y mostrar los resultados numérica (solo para el primer año) y gráficamente (<a href="#fig-ExpPre">Figura&nbsp;12</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">48</span>), <span class="at">start =</span> <span class="dv">2022</span>, <span class="at">freq =</span> <span class="dv">12</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pdl <span class="ot">&lt;-</span> <span class="fu">bizdays</span>(tmp, <span class="at">FinCenter =</span> <span class="st">"London"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>pss <span class="ot">&lt;-</span> <span class="fu">easter</span>(tmp)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>pexp.ar1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(exp.ar1, </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h =</span> <span class="dv">48</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg =</span> <span class="fu">cbind</span>(pdl, pss, </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">48</span>), </span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>)), </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>pexp.ar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>         Point Forecast    Lo 95    Hi 95
Jan 2022       17038.34 15872.47 18289.85
Feb 2022       17914.41 16507.87 19440.79
Mar 2022       22244.01 20301.71 24372.15
Apr 2022       18695.72 16915.72 20663.01
May 2022       20202.45 18133.59 22507.36
Jun 2022       21456.66 19116.67 24083.07
Jul 2022       19338.28 17109.38 21857.54
Aug 2022       15532.75 13651.96 17672.65
Sep 2022       21436.31 18722.63 24543.31
Oct 2022       21014.04 18243.91 24204.78
Nov 2022       21848.13 18859.08 25310.93
Dec 2022       19956.25 17130.79 23247.73</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pexp.ar1, </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Millones de euros"</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PI =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1998</span>, <span class="dv">2026</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ExpPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ExpPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;12: Exportaciones (1999-2021) y predicción (2022-2025)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="chocolate" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="chocolate"><span class="header-section-number">4.3</span> Chocolate</h2>
<p>Vamos a aplicar la metodología de Box-Jenkins a la serie mensual de <strong>producción de chocolate en Australia</strong> desde enero de 1958 hasta diciembre de 1994, 444 meses.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>chocolate <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Chocolate.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>chocolate <span class="ot">&lt;-</span> <span class="fu">ts</span>(chocolate, <span class="at">start =</span> <span class="dv">1958</span>, <span class="at">freq =</span> <span class="dv">12</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(chocolate, </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>, </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Toneladas"</span>,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Chocolate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-Chocolate-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;13: Producción de Chocolate (Australia)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La producción de chocolate presenta una tendencia creciente, especialmente desde los años 80 del siglo pasado, una marcada componente estacional (donde la máxima producción se da en el invierno austral, meses de mayo a agosto, y la menor producción en enero), combinados en un esquema multiplicativo. Trabajaremos con el logaritmo de la serie para linealizar las componentes y reducir la falta de estacionariedad en varianza.</p>
<section id="transformación-de-la-serie-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="transformación-de-la-serie-2">Transformación de la serie</h3>
<p>La <a href="#fig-ChoFAC">Figura&nbsp;14</a> muestra que solo la doble diferenciación regular y estacional consigue que la transformación logarítmica de Chocolate sea estacionaria y ergódica.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(chocolate), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(chocolate)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(chocolate), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(chocolate), <span class="at">lag =</span> <span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-ChoFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ChoFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-ChoFAC"></p>
<p></p><figcaption class="figure-caption">(a) Serie</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ChoFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-ChoFAC"></p>
<p></p><figcaption class="figure-caption">(b) Diferencia regular</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ChoFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-ChoFAC"></p>
<p></p><figcaption class="figure-caption">(c) Diferencia estacional</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-ChoFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-ChoFAC"></p>
<p></p><figcaption class="figure-caption">(d) Diferencia regular y estacional</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura&nbsp;14: FAC para Chocolate (log)</figcaption><p></p>
</figure>
</div>
<p>Las funciones que identifican la diferenciación de forma automática avalan esta decisión.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(<span class="fu">log</span>(chocolate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nsdiffs</span>(<span class="fu">log</span>(chocolate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Podemos concluir que <span class="math inline">\(d = 1\)</span> y <span class="math inline">\(D = 1\)</span> o <span class="math inline">\(\log(chocolate_t) \sim I(1)I_{12}(1)\)</span>.</p>
</section>
<section id="identificación-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identificación-2">Identificación</h3>
<p>¿Qué nos indica <code>auto.arima</code>? Para ayudar a esta función lo máximo posible vamos a definir la variable de intervención <em>días laborables</em>. Por proximidad cultural, histórica y política, usaremos el calendario de Londres para Australia.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bizdays</span>(chocolate, <span class="at">FinCenter =</span> <span class="st">"London"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
1958  23  20  21  20  21  21  23  20  22  23  20  21
1959  22  20  20  22  20  22  23  20  22  22  21  22
1960  21  21  23  19  22  21  21  22  22  21  22  21
1961  22  20  22  19  22  22  21  22  21  22  22  19
1962  23  20  22  19  23  20  22  22  20  23  22  19</code></pre>
</div>
</div>
<p>Vamos a crear esta variable y a incluirla en la auto-identificación.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Efecto año días laborables</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>DiasLaborables <span class="ot">&lt;-</span>  <span class="fu">bizdays</span>(chocolate, <span class="at">FinCenter =</span> <span class="st">"London"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(chocolate, <span class="at">d =</span> <span class="dv">1</span>, <span class="at">D =</span> <span class="dv">1</span>, </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasLaborables))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: chocolate 
Regression with ARIMA(1,1,1)(0,1,2)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
         ar1      ma1     sma1     sma2    xreg
      0.3032  -0.9078  -0.6174  -0.0922  0.0339
s.e.  0.0619   0.0326   0.0501   0.0487  0.0040

sigma^2 = 0.009433:  log likelihood = 391.34
AIC=-770.68   AICc=-770.48   BIC=-746.28</code></pre>
</div>
</div>
<p>Indica <span class="math inline">\(ARIMA_{12}(1,1,1)(0,1,2)\)</span>, donde el parámetro <span class="math inline">\(\theta_{24}\)</span> (sma2) no está claro si es significativo. Además, el efecto días laborables es claramente significativo.</p>
<p><br>
</p>
<p>Por último, la función <code>seas</code> (también con un poco de ayuda) identifica un proceso <span class="math inline">\(ARIMA_{12}(1,1,1)(0,1,1)\)</span>, con un efecto Semana Santa (de quince días) un efecto día de la semana y un efecto año bisiesto, que conjuntamente equivalen al efecto días laborables.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">seas</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(chocolate), <span class="at">lag =</span> <span class="dv">12</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
seas(x = diff(diff(log(chocolate), lag = 12)))

Coefficients:
                   Estimate Std. Error z value             Pr(&gt;|z|)    
Leap Year          0.037906   0.031418   1.207             0.227622    
Mon                0.021718   0.017931   1.211             0.225819    
Tue                0.007760   0.018019   0.431             0.666733    
Wed                0.025674   0.018144   1.415             0.157080    
Thu               -0.002852   0.018096  -0.158             0.874763    
Fri               -0.015197   0.018124  -0.838             0.401771    
Sat               -0.063503   0.018205  -3.488             0.000486 ***
Easter[15]        -0.095747   0.045962  -2.083             0.037234 *  
AR-Nonseasonal-01  0.226982   0.056597   4.010            0.0000606 ***
MA-Nonseasonal-01  0.879176   0.027636  31.812 &lt; 0.0000000000000002 ***
MA-Seasonal-12     0.650157   0.040017  16.247 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

SEATS adj.  ARIMA: (1 0 1)(0 0 1)  Obs.: 431  Transform: none
AICc: -737.6, BIC: -689.5  QS (no seasonality in final):    0  
Box-Ljung (no autocorr.): 16.86   Shapiro (normality): 0.9879 ***
Messages generated by X-13:
Warnings:
- Automatic transformation selection cannot be done on a series
  with zero or negative values.
- At least one visually significant seasonal peak has been found
  in one or more of the estimated spectra.
- Series should not be a candidate for seasonal adjustment
  because the spectrum of the prior adjusted series (Table B1)
  has no visually significant seasonal peaks.</code></pre>
</div>
</div>
<p>Aparentemente ambas funciones identifican el mismo modelo, si del modelo identificado con <code>auto.arima</code> excluimos el parámetro no significativo. Ten en cuenta que los días laborables ya descuentan el efecto de la Semana Santa, así que no es necesario incluir el efecto Semana Santa de forma independiente.</p>
</section>
<section id="estimación" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación">Estimación</h3>
<p>Vamos a realizar la primera estimación.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>choco.ar1 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(chocolate, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xreg =</span> DiasLaborables)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>choco.ar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: chocolate 
Regression with ARIMA(1,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
         ar1      ma1     sma1    xreg
      0.2844  -0.8972  -0.6718  0.0339
s.e.  0.0620   0.0333   0.0462  0.0038

sigma^2 = 0.009501:  log likelihood = 389.55
AIC=-769.1   AICc=-768.96   BIC=-748.77</code></pre>
</div>
</div>
<p>Ya tenemos un modelo de partida, veamos si es necesaria más intervención.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(choco.ar1)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1958</span>, <span class="dv">1994</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ChoError" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoError-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;15: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Se observan tres valores claramente atípicos en enero de 1986, 1991 y 1994. Además, hay otro candidato a valor extremo, por superar las 2.5 desviaciones típicas, en septiembre de 1975. Por tanto,</p>
<ul>
<li>Se crea una variable de intervención para cada caso</li>
<li>Se estima de nuevo el modelo incluyendo estas variables</li>
<li>Se vuelve a analizar si quedan valores atípicos</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>d0975 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(chocolate) <span class="sc">==</span> <span class="dv">9</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(chocolate)) <span class="sc">==</span> <span class="dv">1975</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>d0186 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(chocolate) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(chocolate)) <span class="sc">==</span> <span class="dv">1986</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>d0191 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(chocolate) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(chocolate)) <span class="sc">==</span> <span class="dv">1991</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>d0194 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(chocolate) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(chocolate)) <span class="sc">==</span> <span class="dv">1994</span>)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>choco.ar2 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(chocolate, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">seasonal =</span>  <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>), </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasLaborables, d0975, d0186, d0191, d0194))</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>choco.ar2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: chocolate 
Regression with ARIMA(1,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
         ar1      ma1     sma1  DiasLaborables    d0975   d0186    d0191
      0.3052  -0.8889  -0.6778          0.0363  -0.1630  0.1291  -0.3385
s.e.  0.0646   0.0355   0.0413          0.0035   0.0753  0.0755   0.0769
       d0194
      0.5128
s.e.  0.0838

sigma^2 = 0.008197:  log likelihood = 423.4
AIC=-828.8   AICc=-828.37   BIC=-792.2</code></pre>
</div>
</div>
<p>Ahora debemos volver a verificar si en el nuevo modelo hay valores extremos. Observamos que no hay.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(choco.ar2)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1958</span>, <span class="dv">1994</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ChoError2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoError2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;16: Error + Intervención</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="validación-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="validación-2">Validación</h3>
<p>Por último, veamos si todos los coeficientes del modelo son significativos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>ancho <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nchar</span>(<span class="fu">names</span>(<span class="fu">coef</span>(choco.ar2)))) <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">coef</span>(choco.ar2))) {</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  wt <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(choco.ar2), </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sigma =</span> <span class="fu">vcov</span>(choco.ar2), </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Terms =</span> i)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Coeficiente: "</span>, </span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">names</span>(<span class="fu">coef</span>(choco.ar2))[i], <span class="at">width =</span> ancho),</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"valor de p: "</span>, </span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(wt<span class="sc">$</span>result<span class="sc">$</span>chi2[<span class="dv">3</span>], <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"f"</span>))</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coeficiente:  ar1              valor de p:  0.0000
Coeficiente:  ma1              valor de p:  0.0000
Coeficiente:  sma1             valor de p:  0.0000
Coeficiente:  DiasLaborables   valor de p:  0.0000
Coeficiente:  d0975            valor de p:  0.0303
Coeficiente:  d0186            valor de p:  0.0874
Coeficiente:  d0191            valor de p:  0.0000
Coeficiente:  d0194            valor de p:  0.0000</code></pre>
</div>
</div>
<p>Aunque uno de ellos (enero 1986) no lo es al 5%, si lo es al 10% así que optamos por dejarlo.</p>
</section>
<section id="error-de-estimación-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-estimación-2">Error de estimación</h3>
<p>Analizando los criterios de bondad de ajuste se tiene que: el error medio de 3 es prácticamente cero por lo que no parece que haya sesgo en las predicciones; en media nos equivocamos en 488 toneladas (RMSE); y el error porcentual medio es 7%, razonable.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(choco.ar2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>             ME   RMSE    MAE   MPE MAPE MASE  ACF1
Training set  3 488.05 360.71 -0.33 6.99 0.69 -0.05</code></pre>
</div>
</div>
</section>
<section id="error-de-predicción-extra-muestral-según-horizonte-temporal-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="error-de-predicción-extra-muestral-según-horizonte-temporal-2">Error de predicción extra-muestral según horizonte temporal</h3>
<p>Asumimos que se precisan veinte años para hacer una buena estimación, <span class="math inline">\(k = 240\)</span>, y fijaremos el horizonte temporal en un año, <span class="math inline">\(h = 12\)</span> meses.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">240</span>                </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span>                 </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(chocolate)  </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span>T <span class="sc">-</span> k <span class="sc">-</span> h            </span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(DiasLaborables, d0975, d0186, d0191, d0194))</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(chocolate, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(chocolate, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb77-19"><a href="#cb77-19" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb77-20"><a href="#cb77-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-21"><a href="#cb77-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb77-22"><a href="#cb77-22" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb77-23"><a href="#cb77-23" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb77-24"><a href="#cb77-24" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb77-25"><a href="#cb77-25" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb77-26"><a href="#cb77-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg=</span><span class="fu">as.matrix</span>(X.train)))</span>
<span id="cb77-27"><a href="#cb77-27" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb77-28"><a href="#cb77-28" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb77-29"><a href="#cb77-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb77-30"><a href="#cb77-30" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb77-31"><a href="#cb77-31" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lambda =</span> <span class="dv">0</span>))</span>
<span id="cb77-32"><a href="#cb77-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb77-33"><a href="#cb77-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-34"><a href="#cb77-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.element</span>(<span class="st">"try-error"</span>, <span class="fu">class</span>(fit))) {</span>
<span id="cb77-35"><a href="#cb77-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(X.train) <span class="sc">&gt;</span> <span class="dv">0</span>) </span>
<span id="cb77-36"><a href="#cb77-36" aria-hidden="true" tabindex="-1"></a>      fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test)) <span class="cf">else</span></span>
<span id="cb77-37"><a href="#cb77-37" aria-hidden="true" tabindex="-1"></a>        fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h)</span>
<span id="cb77-38"><a href="#cb77-38" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb77-39"><a href="#cb77-39" aria-hidden="true" tabindex="-1"></a>    mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb77-40"><a href="#cb77-40" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb77-41"><a href="#cb77-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb77-42"><a href="#cb77-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-43"><a href="#cb77-43" aria-hidden="true" tabindex="-1"></a>errorArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb77-44"><a href="#cb77-44" aria-hidden="true" tabindex="-1"></a>errorArima</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 8.377471 8.600894 8.872539 9.262283 9.405912 9.251936 9.321219 9.354090
 [9] 9.070492 9.241635 9.157093 9.303983</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> errorArima), <span class="at">colour =</span> <span class="st">"Blue"</span>) <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Horizonte temporal de predicción"</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"%"</span>) <span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ChoMAPE" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoMAPE-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;17: Error de predicción (MAPE) según horizonte temporal</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-ChoMAPE">Figura&nbsp;17</a> revela que el error de predicción a un periodo vista es 1.4 puntos porcentuales superior al error de ajuste. Hasta los 5 meses el error aumenta según aumenta el horizonte de predicción. Desde el sexto mes, el error se mantiene estable en torno al 9%-9.5%.</p>
</section>
<section id="interpretación-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretación-2">Interpretación</h3>
<p>El <em>modelo teórico</em> es <span class="math inline">\(log(chocolate) \sim ARIMA_{12}(1, 1, 1)(0, 1, 1) + AI\)</span>, <span class="math display">\[(1 - \phi_1 L)(1 - L^{12})(1 - L)\log(chocolate_t) = (1 + \theta_1 L)(1 + \theta_{12} L^{12})\varepsilon_t + AI.\]</span></p>
<p>Si sustituimos <span class="math inline">\((1 - L^{12})\log(chocolate_t)\)</span> por <span class="math inline">\(TVA_{chocolate_t}\)</span>, desarrollamos el modelo y sustituimos los parámetros por sus estimaciones, queda <span class="math display">\[\widehat{TVA}_{chocolate_t} = TVA_{chocolate_{t-1}} + 0.31(TVA_{chocolate_{t-1}} - TVA_{chocolate_{t-2}})\]</span> <span class="math display">\[- 0.89\varepsilon_{t-1} - 0.68\varepsilon_{t-12} + 0.60\varepsilon_{t-13}\]</span> <span class="math display">\[+0.036\cdot DiasLaborables - 0.16\cdot d0975 + 0.13 \cdot d0186-0.34 \cdot d0191 + 0.51\cdot d0194.\]</span></p>
<p>Por tanto:</p>
<ul>
<li>La tasa de variación anual en la producción de chocolate para un mes es la misma que la del mes pasado más un 31% del último incremento observado.</li>
<li>Si en los meses pasados el valor esperado en la tasa de variación se alejó de la real, hay que tenerlo en cuenta para corregir las previsiones.</li>
<li>Cada día laborable adicional en un mes supone un incremento del 3.6% en la producción.</li>
<li>En determinados meses hubo unos valores de producción muy alejados de lo esperado.</li>
</ul>
</section>
<section id="predicción-de-la-serie-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicción-de-la-serie-2">Predicción de la serie</h3>
<p>Una vez dado por válido el modelo podemos pasar a realizar predicciones. Hay que tener en cuenta que hay una variable de intervención de efecto calendario (Días laborables), para la que debemos indicar qué valores tomará en el periodo de predicción. Vamos a fijar el horizonte de predicción en cuatro años (1995 a 1998).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">48</span>), <span class="at">start =</span> <span class="dv">1995</span>, <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>pdl <span class="ot">&lt;-</span> <span class="fu">bizdays</span>(tmp, <span class="at">FinCenter =</span> <span class="st">"London"</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>pchoco.ar2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(choco.ar2, </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h =</span> <span class="dv">48</span>,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xreg =</span> <span class="fu">cbind</span>(pdl, </span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>), <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">48</span>)), </span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pchoco.ar2, </span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Toneladas"</span>,</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">1958</span>, <span class="dv">1998</span>, <span class="dv">4</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ChoPre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-07-Tema7_files/figure-html/fig-ChoPre-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;18: Chocolate (1958-1994) y predicción (1995-1998)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
</section>
<section id="comparación-con-el-método-de-alisado-exponencial" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Comparación con el método de alisado exponencial</h1>
<p>Veamos una comparativa, para los dos ejemplos vistos, entre los resultados obtenidos con ARIMA y con Alisado exponencial</p>
<section id="nacimientos-log" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="nacimientos-log">Nacimientos (log)</h3>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Método</th>
<th style="text-align: left;">Modelo</th>
<th style="text-align: center;">MAPE</th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Ajuste</td>
<td style="text-align: center;">Extra h = 1</td>
<td style="text-align: center;">Extra h = 6</td>
<td style="text-align: center;">Extra h = 12</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA</td>
<td style="text-align: left;">ARIMA(0,1,1)(0,1,1) + AI</td>
<td style="text-align: center;">1.54</td>
<td style="text-align: center;">1.89</td>
<td style="text-align: center;">2.59</td>
<td style="text-align: center;">3.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alisado</td>
<td style="text-align: left;">ETS(A,Ad,A)</td>
<td style="text-align: center;">1.74</td>
<td style="text-align: center;">1.93</td>
<td style="text-align: center;">2.77</td>
<td style="text-align: center;">3.67</td>
</tr>
</tbody>
</table>
<p>Para Nacimientos, la mejora en los indicadores de calidad con ARIMA respecto de Alisado es tan pequeña que no justifica su aplicación. Incluso para previsiones extra-muestrales a 12 meses vista, Alisado sólo es inferior en medio punto porcentual a ARIMA.</p>
</section>
<section id="exportaciones-log" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exportaciones-log">Exportaciones (log)</h3>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Método</th>
<th style="text-align: left;">Modelo</th>
<th style="text-align: center;">MAPE</th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Ajuste</td>
<td style="text-align: center;">Extra h = 1</td>
<td style="text-align: center;">Extra h = 6</td>
<td style="text-align: center;">Extra h = 12</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA</td>
<td style="text-align: left;">ARIMA(0,1,1)(0,1,1) + AI</td>
<td style="text-align: center;">2.63</td>
<td style="text-align: center;">2.79</td>
<td style="text-align: center;">4.11</td>
<td style="text-align: center;">5.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alisado</td>
<td style="text-align: left;">ETS(A,Ad,A)</td>
<td style="text-align: center;">4.80</td>
<td style="text-align: center;">5.23</td>
<td style="text-align: center;">6.38</td>
<td style="text-align: center;">7.92</td>
</tr>
</tbody>
</table>
<p>En el caso de Exportaciones, la mejora en la calidad del ajuste con ARIMA respecto de Alisado es de más de 2 puntos porcentuales, con independencia del horizonte temporal. En este caso, ARIMA gracias a de la intervención ofrece mejores resultados.</p>
</section>
<section id="chocolate-log" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="chocolate-log">Chocolate (log)</h3>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Método</th>
<th style="text-align: left;">Modelo</th>
<th style="text-align: center;">MAPE</th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Ajuste</td>
<td style="text-align: center;">Extra h = 1</td>
<td style="text-align: center;">Extra h = 6</td>
<td style="text-align: center;">Extra h = 12</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARIMA</td>
<td style="text-align: left;">ARIMA(1,1,1)(0,1,1) + AI</td>
<td style="text-align: center;">6.99</td>
<td style="text-align: center;">8.38</td>
<td style="text-align: center;">9.25</td>
<td style="text-align: center;">9.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alisado</td>
<td style="text-align: left;">ETS(A,A,A)</td>
<td style="text-align: center;">8.15</td>
<td style="text-align: center;">9.43</td>
<td style="text-align: center;">11.39</td>
<td style="text-align: center;">9.73</td>
</tr>
</tbody>
</table>
<p>En el caso de Chocolate, la mejora en la calidad del ajuste con ARIMA respecto de Alisado es entre 1 y 2 puntos porcentuales en previsiones a unos pocos meses vista. Sin embargo, a doce meses vista ambos métodos ofrecen igual calidad en sus predicciones.</p>
<p><br>
<br>
<br>
<br>
</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Acude al epígrafe Intervención del Tema 2 para refrescar estos conceptos<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><code>R</code> permite crear tu propio calendario de festivos y existen otras librerías que extienden las opciones de <code>bizdays</code>. En el ejemplo de Pasajeros puedes ver como construir la serie de días laborables del mes para España paso a paso.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2022, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.e</a></div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>