<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Iván Arribas (Depto. Análisis Económico. Universitat de València)">

<title>Predicción con Datos Temporales - Pernoctaciones en alojamientos turísticos de turistas extranjeros</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicción con Datos Temporales</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./01-Guia-curso.html" rel="" target="">
 <span class="menu-text">Guía del curso</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-Logistica.html" rel="" target="">
 <span class="menu-text">Logística</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diapos" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Diapos</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-diapos">    
        <li class="dropdown-header">Teoría</li>
        <li>
    <a class="dropdown-item" href="./03-01-Tema1.html" rel="" target="">
 <span class="dropdown-text">Tema 1: Introducción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-02-Tema2.html" rel="" target="">
 <span class="dropdown-text">Tema 2: Definición</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-03-Tema3.html" rel="" target="">
 <span class="dropdown-text">Tema 3: Métodos sencillos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-04-Tema4.html" rel="" target="">
 <span class="dropdown-text">Tema 4: Media móvil</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-05-Tema5.html" rel="" target="">
 <span class="dropdown-text">Tema 5: Alisado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-06-Tema6.html" rel="" target="">
 <span class="dropdown-text">Tema 6: ARIMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-07-Tema7.html" rel="" target="">
 <span class="dropdown-text">Tema 7: SARIMA</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Ejemplo de aplicación</li>
        <li>
    <a class="dropdown-item" href="./03-08-Ejemplo2.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-09-Ejemplo3.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-10-Ejemplo4.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-11-Ejemplo5.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-12-Ejemplo6.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-13-Ejemplo7.html" rel="" target="">
 <span class="dropdown-text">Ejemplo Tema 7</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otro ejemplo</li>
        <li>
    <a class="dropdown-item" href="./03-14-Ejemplo-Pasajeros.html" rel="" target="">
 <span class="dropdown-text">Ejemplo de Pasajeros</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-píldoras" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Píldoras</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-píldoras">    
        <li>
    <a class="dropdown-item" href="./04-01-Bootstrapping.html" rel="" target="">
 <span class="dropdown-text">Bootstrapping para IC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-02-Multiples_CS.html" rel="" target="">
 <span class="dropdown-text">Múltiples componentes estacionales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-03-Redes_neuronales.html" rel="" target="">
 <span class="dropdown-text">Predicción con Redes Neuronales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-04-Series_acotadas.html" rel="" target="">
 <span class="dropdown-text">Series acotadas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-05-Valores_perdidos_Outliers.html" rel="" target="">
 <span class="dropdown-text">Valores perdidos y outliers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-06-Covid_Nacimientos.html" rel="" target="">
 <span class="dropdown-text">Efecto de la Covid-19 en Nacimientos</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./05-Recursos-R.html" rel="" target="">
 <span class="menu-text">Recursos de la asignatura</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-Evaluacion_Continua.html" rel="" target="">
 <span class="menu-text">Evaluacion Continua</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-más" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Más</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-más">    
        <li class="dropdown-header">R</li>
        <li>
    <a class="dropdown-item" href="https://cran.r-project.org" rel="" target="">
 <span class="dropdown-text">Dónde está R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rstudio.com" rel="" target="">
 <span class="dropdown-text">Donde está RStudio</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Markdown</li>
        <li>
    <a class="dropdown-item" href="https://bookdown.org/yihui/rmarkdown/" rel="" target="">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rmarkdown.rstudio.com/lesson-1.html" rel="" target="">
 <span class="dropdown-text">R Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf" rel="" target="">
 <span class="dropdown-text">R Markdown (pdf)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://quarto.org/docs/tools/rstudio.html" rel="" target="">
 <span class="dropdown-text">Quatro</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Otros</li>
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com" rel="" target="">
 <span class="dropdown-text">Blog sobre R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://bookdown.org" rel="" target="">
 <span class="dropdown-text">Libros online que debes conocer</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#identificación" id="toc-identificación" class="nav-link" data-scroll-target="#identificación"><span class="header-section-number">2</span> Identificación</a>
  <ul class="collapse">
  <li><a href="#diferenciación-y-logaritmo" id="toc-diferenciación-y-logaritmo" class="nav-link" data-scroll-target="#diferenciación-y-logaritmo"><span class="header-section-number">2.1</span> Diferenciación y logaritmo</a></li>
  <li><a href="#identificación-del-orden-regular-y-estacional" id="toc-identificación-del-orden-regular-y-estacional" class="nav-link" data-scroll-target="#identificación-del-orden-regular-y-estacional"><span class="header-section-number">2.2</span> Identificación del orden regular y estacional</a></li>
  </ul></li>
  <li><a href="#estimación" id="toc-estimación" class="nav-link" data-scroll-target="#estimación"><span class="header-section-number">3</span> Estimación</a></li>
  <li><a href="#validación" id="toc-validación" class="nav-link" data-scroll-target="#validación"><span class="header-section-number">4</span> Validación</a></li>
  <li><a href="#ecuación-del-modelo-identificado" id="toc-ecuación-del-modelo-identificado" class="nav-link" data-scroll-target="#ecuación-del-modelo-identificado"><span class="header-section-number">5</span> Ecuación del modelo identificado</a></li>
  <li><a href="#predicción-de-las-pernoctaciones" id="toc-predicción-de-las-pernoctaciones" class="nav-link" data-scroll-target="#predicción-de-las-pernoctaciones"><span class="header-section-number">6</span> Predicción de las pernoctaciones</a></li>
  <li><a href="#comparación-con-otros-modelos" id="toc-comparación-con-otros-modelos" class="nav-link" data-scroll-target="#comparación-con-otros-modelos"><span class="header-section-number">7</span> Comparación con otros modelos</a>
  <ul class="collapse">
  <li><a href="#calidad-de-ajuste" id="toc-calidad-de-ajuste" class="nav-link" data-scroll-target="#calidad-de-ajuste"><span class="header-section-number">7.1</span> Calidad de ajuste</a></li>
  <li><a href="#predicciones-extramuestrales" id="toc-predicciones-extramuestrales" class="nav-link" data-scroll-target="#predicciones-extramuestrales"><span class="header-section-number">7.2</span> Predicciones extramuestrales</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pernoctaciones en alojamientos turísticos de turistas extranjeros</h1>
<p class="subtitle lead">Procesos ARIMA con estacionalidad</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Iván Arribas (Depto. Análisis Económico. Universitat de València) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p><br>
<br>
</p>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Consideremos de nuevo la serie temporal correspondiente al número de pernoctaciones que los turistas extranjeros realizan en España en alojamientos turísticos autorizados (que llamaremos Pernoctaciones en adelante). Esta serie está disponible en Eurostat desde enero de 2000 hasta diciembre de 2022, un total de 23 años y 276 observaciones.</p>
<p>La serie temporal muestra una tendencia suavemente decreciente en el número de pernoctaciones en la primera década del presente siglo. Con el cambio de década se produce un cambio en la tendencia, que pasa a ser creciente. A finales de la década pasada se observa una caída en el número de pernoctaciones y en los últimos años el efecto de la Covid-19 y posterior recuperación. El esquema es multiplicativo.</p>
<p>Para este análisis consideraremos la serie hasta diciembre de 2019, eliminando el periodo afectado por la pandemia de Covid-19. Posteriormente usaremos las predicciones para los años 2020 a 2022 para cuantificar el efecto de la pandemia sobre las pernoctaciones y su impacto económico.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Pernoctaciones <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./series/Pernoctaciones.csv"</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Pernoctaciones <span class="ot">&lt;-</span> <span class="fu">ts</span>(Pernoctaciones[,<span class="dv">2</span>], </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">start =</span> <span class="dv">2000</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Pernoctaciones,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Noches (millones)"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2022</span>, <span class="dv">2</span>))  </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>Pernoctacionesb <span class="ot">&lt;-</span> <span class="fu">window</span>(Pernoctaciones, <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2019</span>, <span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Pernoctaciones" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-Pernoctaciones-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figura&nbsp;1: Pernoctaciones</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
<br>
</p>
</section>
<section id="identificación" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Identificación</h1>
<p><br>
</p>
<section id="diferenciación-y-logaritmo" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="diferenciación-y-logaritmo"><span class="header-section-number">2.1</span> Diferenciación y logaritmo</h2>
<p>El esquema multiplicativo de la serie aconseja el uso de la transformación logarítmica. Además, vamos a ver que para que la serie sea estacionaria es necesario diferenciarla tanto regular como estacionalmente, así que el uso de logaritmo vuelve a ser aconsejable si queremos ganar en interpretabilidad.</p>
<p>La <a href="#fig-PernoctacionesFAC">Figura&nbsp;2</a> muestra la FAC para la serie Pernoctaciones (log) y algunas de sus transformaciones. En los paneles a) y b) las autocorrelaciones estacionales decrecen muy lentamente, indicando que la serie analizada no es ergódica. El panel c) muestra que las autocorrelaciones en la parte regular decrecen lentamente, indicando que la serie analizada no es estacionaria. Solo la doble diferenciación regular y estacional de la serie muestra un rápido descenso en los coeficiente de autocorrelación (panel d), indicando que la serie así transformada es estacionaria en media y ergódica.</p>
<div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">log</span>(Pernoctacionesb), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(Pernoctacionesb)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">log</span>(Pernoctacionesb), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(<span class="fu">diff</span>(<span class="fu">diff</span>(<span class="fu">log</span>(Pernoctacionesb), <span class="at">lag=</span><span class="dv">12</span>)), <span class="at">lag =</span> <span class="dv">48</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-PernoctacionesFAC" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-PernoctacionesFAC-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-PernoctacionesFAC-1.png" class="img-fluid figure-img" data-ref-parent="fig-PernoctacionesFAC"></p>
<figcaption class="figure-caption">(a) Log serie</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-PernoctacionesFAC-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-PernoctacionesFAC-2.png" class="img-fluid figure-img" data-ref-parent="fig-PernoctacionesFAC"></p>
<figcaption class="figure-caption">(b) Dif. regular log serie</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-PernoctacionesFAC-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-PernoctacionesFAC-3.png" class="img-fluid figure-img" data-ref-parent="fig-PernoctacionesFAC"></p>
<figcaption class="figure-caption">(c) Dif. estacional log serie</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-PernoctacionesFAC-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-PernoctacionesFAC-4.png" class="img-fluid figure-img" data-ref-parent="fig-PernoctacionesFAC"></p>
<figcaption class="figure-caption">(d) Dif. regular y estacional log serie</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: FAC para Pernoctaciones</figcaption><p></p>
</figure>
</div>
</div>
<p>Por otro lado, la identificación automática de la diferenciación también concluye que es necesaria la doble diferenciación.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ndiffs</span>(<span class="fu">log</span>(Pernoctacionesb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nsdiffs</span>(<span class="fu">log</span>(Pernoctacionesb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Vamos a asumir que el proceso debe ser doblemente diferenciado <span class="math inline">\(\log(Pernoctaciones) \sim I(1)I_{12}(1)\)</span>.</p>
<p><br>
</p>
</section>
<section id="identificación-del-orden-regular-y-estacional" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="identificación-del-orden-regular-y-estacional"><span class="header-section-number">2.2</span> Identificación del orden regular y estacional</h2>
<p>Vamos a identificar los valores de <span class="math inline">\(p\)</span>, <span class="math inline">\(q\)</span>, <span class="math inline">\(P\)</span> y <span class="math inline">\(Q\)</span>. Para ello solicitaremos con <code>auto.arima</code> y <code>seas</code> una identificación automática.</p>
<p>Con <code>auto.arima</code> incluiremos dos efectos calendarios, uno para el número de días del mes y otro para el efecto Semana Santa.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>DiasMes <span class="ot">&lt;-</span> <span class="fu">monthdays</span>(Pernoctacionesb)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">easter</span>(Pernoctacionesb)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(Pernoctacionesb, </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">d =</span> <span class="dv">1</span>, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">D =</span> <span class="dv">1</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: Pernoctacionesb 
Regression with ARIMA(0,1,1)(2,1,2)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sar1     sar2    sma1     sma2  DiasMes  SemanaSanta
      -0.3207  -0.7187  -0.0442  0.3377  -0.4315   0.0293       0.0426
s.e.   0.0709   0.1720   0.1677  0.1683   0.1689   0.0077       0.0060

sigma^2 = 0.0008503:  log likelihood = 483.35
AIC=-950.7   AICc=-950.04   BIC=-923.3</code></pre>
</div>
</div>
<p>La función <code>auto.arima</code> identifica un proceso <span class="math inline">\(ARIMA_{12}(0,1,1)(2,1,2)\)</span>, donde el coeficiente para <code>sar2</code> no parece ser significativo (el coeficiente no supera los dos errores estándar).</p>
<p>La identificación alcanzada por <code>seas</code> es un proceso <span class="math inline">\(ARIMA_{12}(0,1,1)(0,1,1)\)</span> (modelo de las aerolíneas) de la transformación logarítmica, con intervención en Semana Santa y días laborables. Además, se identifica un cambio de nivel desde marzo de 2005.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">seas</span>(Pernoctacionesb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
seas(x = Pernoctacionesb)

Coefficients:
                    Estimate Std. Error z value             Pr(&gt;|z|)    
Weekday           -0.0009593  0.0003988  -2.406             0.016143 *  
Easter[8]          0.0425480  0.0051831   8.209 0.000000000000000223 ***
LS2005.Mar        -0.0819394  0.0225926  -3.627             0.000287 ***
MA-Nonseasonal-01  0.2976707  0.0633552   4.698 0.000002621542191344 ***
MA-Seasonal-12     0.4286878  0.0590994   7.254 0.000000000000405599 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 240  Transform: log
AICc:  6634, BIC:  6654  QS (no seasonality in final):    0  
Box-Ljung (no autocorr.):  38.2 * Shapiro (normality): 0.9964  
Messages generated by X-13:
Warnings:
- At least one visually significant trading day peak has been
  found in one or more of the estimated spectra.</code></pre>
</div>
</div>
<p>Vemos que ambas identificaciones difieren notablemente. Así, vamos a partir de la identificación obtenida por <code>seas</code>, el clásico modelo de las aerolíneas: <span class="math display">\[log(Pernoctaciones) \sim ARIMA_{12}(0,1,1)(0,1,1)\]</span>.</p>
<p>Respecto de la intervención, incluiremos días del mes y Semana Santa. No se incluirá el cambio de nivel identificado por <code>seas</code> dado que no existe una justificación para ello. En 2005 no ocurrió nada que justifique una caída permanente del 8.2% en el número de pernoctaciones internacionales (coeficiente -0.0819).</p>
<p><br>
<br>
</p>
</section>
</section>
<section id="estimación" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Estimación</h1>
<p>Antes se estimar el modelo identificado, vamos mejorar la implementación del efecto de la Semana Santa. Para ello, vamos a crear una variable que permita estimar el efecto del periodo de dos semanas que comprende Semana Santa y Pascua. Es decir, el periodo que va desde el lunes previo a Semana Santa hasta el Viernes posterior a Domingo de Resurrección. Esta nueva variable (<em>SemanaSanta</em>) valdrá cero para los meses distintos de marzo y abril; para marzo valdrá la proporción de días vacacionales que recaen en marzo; y para abril la proporción de días vacacionales que caen el abril.</p>
<p>La librería <code>timeData</code> proporciona una serie de funciones que permiten definir un calendario de festividades, identificar los fines de semana, etc. En concreto la función <code>isBizday</code> permite saber si un día es festivo (a partir de un calendario de festivos) e identificar los días laborables; y la función <code>Easter</code> permite identificar donde ha caído la Semana Santa.</p>
<p>El proceso seguido es el siguiente:</p>
<ul>
<li><p>Con <code>Easter</code> se define la festividad de cada día del periodo considerado.</p>
<p>Por claridad, cada festivo se ha definido de forma independiente para después crear una variable con todos los festivos de Semana Santa (<em>SemanaSanta</em>).</p>
<p>El rango para todos los cálculos va desde 2000 hasta 2022 que incluye el rango de la serie Pernoctaciones más tres años de predicción.</p></li>
<li><p>A continuación, con <code>timeSequence</code> se crea una serie diaria desde el 1 de enero de 2000 hasta el 31 de diciembre de 2022.</p></li>
<li><p>Las dos siguientes líneas de código eliminan de la serie diaria los festivos de Semana Santa, para después dar a esta nueva serie abreviada el formato año-mes eliminando el día. De esta forma, la serie abreviada tendrá el mismo identificador para todos los días del mismo mes.</p>
<p>El argumento <code>wday = 0:6</code> de la función <code>isBizday</code> indica que se deben preservar todos los días de la semana. Cuando se usa este argumento hay que tener en cuenta que el domingo es el día 0 y el sábado el día 6. Así <code>wday = 1:5</code> dejaría todos laborables de la semana y <code>wday = c(0, 6)</code> solo los fines de semana.</p></li>
<li><p>Después, se crea una tabla que, por la naturaleza de la serie abreviada, tendrá para cada año-mes el numero de días del mes, excepto para marzo y abril que tendrán el número de días del mes que no caen en Semana Santa.</p></li>
<li><p>Fechamos la tabla, que es nuestra serie de días del mes sin Semana Santa.</p>
<p>Mostramos los resultados de este proceso para ayudar a entenderlo. Observa que para todos los meses de año excepto marzo y abril, lo que tenemos es simplemente el número de días del mes. Para marzo y abril tenemos el número de días del mes excepto los festivos de Semana Santa. Por ejemplo, en 2002 la Semana Santa cayó entre marzo y abril, de forma que los días no festivos en marzo fueron 24 y en abril 25.</p></li>
<li><p>Las siguientes líneas calculan que proporción de días de Semana Santa caen en cada mes y generan el efecto SemanaSanta: para marzo valdrá la proporción de días vacacionales que recaen en marzo y lo mismo para abril. Por ejemplo, en 2002 siete días de la Semana Santa cayeron en marzo y cinco en abril, es decir, 0.58 días en marzo y 0.42 en abril.</p></li>
<li><p>Las dos últimas líneas de código parten la serie en el periodo muestral y el de predicción.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>LunSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">6</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>MarSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">5</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>MieSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">4</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>JueSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">3</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>VieSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>SabSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>DomSanto <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">0</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>LunPascu <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">1</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>MarPascu <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">2</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>MiePascu <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">3</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>JuePascu <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">4</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>ViePascu <span class="ot">&lt;-</span> <span class="fu">Easter</span>(<span class="dv">2000</span><span class="sc">:</span><span class="dv">2022</span>, <span class="at">shift =</span>  <span class="dv">5</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">c</span>(LunSanto, MarSanto, MieSanto, JueSanto, VieSanto,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>                 SabSanto, DomSanto, LunPascu ,MarPascu, MiePascu, </span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>                 JuePascu, ViePascu)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>fechaDiaria <span class="ot">&lt;-</span> <span class="fu">timeSequence</span>(<span class="at">from =</span> <span class="st">"2000-01-01"</span>, <span class="at">to =</span> <span class="st">"2022-12-31"</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>biz <span class="ot">&lt;-</span> fechaDiaria[<span class="fu">isBizday</span>(fechaDiaria, <span class="at">holidays =</span> SemanaSanta, <span class="at">wday =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>)]</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>bizdays <span class="ot">&lt;-</span> <span class="fu">format</span>(biz, <span class="at">format =</span> <span class="st">"%Y-%m"</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">table</span>(bizdays)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">ts</span>(SemanaSanta, <span class="at">start =</span> <span class="dv">2000</span>, <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>SemanaSanta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
2000  31  29  31  18  31  30  31  31  30  31  30  31
2001  31  28  31  18  31  30  31  31  30  31  30  31
2002  31  28  24  25  31  30  31  31  30  31  30  31
2003  31  28  31  18  31  30  31  31  30  31  30  31
2004  31  29  31  18  31  30  31  31  30  31  30  31
2005  31  28  20  29  31  30  31  31  30  31  30  31
2006  31  28  31  18  31  30  31  31  30  31  30  31
2007  31  28  31  18  31  30  31  31  30  31  30  31
2008  31  29  19  30  31  30  31  31  30  31  30  31
2009  31  28  31  18  31  30  31  31  30  31  30  31
2010  31  28  28  21  31  30  31  31  30  31  30  31
2011  31  28  31  18  31  30  31  31  30  31  30  31
2012  31  29  31  18  31  30  31  31  30  31  30  31
2013  31  28  24  25  31  30  31  31  30  31  30  31
2014  31  28  31  18  31  30  31  31  30  31  30  31
2015  31  28  29  20  31  30  31  31  30  31  30  31
2016  31  29  20  29  31  30  31  31  30  31  30  31
2017  31  28  31  18  31  30  31  31  30  31  30  31
2018  31  28  25  24  31  30  31  31  30  31  30  31
2019  31  28  31  18  31  30  31  31  30  31  30  31
2020  31  29  31  18  31  30  31  31  30  31  30  31
2021  31  28  28  21  31  30  31  31  30  31  30  31
2022  31  28  31  18  31  30  31  31  30  31  30  31</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> (<span class="fu">monthdays</span>(SemanaSanta) <span class="sc">-</span> SemanaSanta)<span class="sc">/</span><span class="dv">12</span> <span class="co">#Nuestra SS tiene 12 dias</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(SemanaSanta, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
2000 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2001 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2002 0.00 0.00 0.58 0.42 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2003 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2004 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2005 0.00 0.00 0.92 0.08 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2006 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2007 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2008 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2009 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2010 0.00 0.00 0.25 0.75 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2011 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2012 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2013 0.00 0.00 0.58 0.42 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2014 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2015 0.00 0.00 0.17 0.83 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2016 0.00 0.00 0.92 0.08 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2017 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2018 0.00 0.00 0.50 0.50 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2019 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2020 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2021 0.00 0.00 0.25 0.75 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
2022 0.00 0.00 0.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pSemanaSanta <span class="ot">&lt;-</span> <span class="fu">subset</span>(SemanaSanta, <span class="at">start =</span> <span class="fu">length</span>(SemanaSanta) <span class="sc">-</span> <span class="dv">35</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>SemanaSanta <span class="ot">&lt;-</span> <span class="fu">subset</span>(SemanaSanta, <span class="at">end =</span> <span class="fu">length</span>(SemanaSanta) <span class="sc">-</span> <span class="dv">36</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La siguiente salida muestra el modelo estimado y la <a href="#fig-Error1">Figura&nbsp;3</a> permite analizar la presencia de más valores extremos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>DiasMes <span class="ot">&lt;-</span> <span class="fu">monthdays</span>(Pernoctacionesb)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>Arima1 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Pernoctacionesb, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),  </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>Arima1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: Pernoctacionesb 
Regression with ARIMA(0,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1  DiasMes  SemanaSanta
      -0.3275  -0.4554   0.0260       0.0500
s.e.   0.0689   0.0711   0.0096       0.0071

sigma^2 = 0.0008881:  log likelihood = 477.86
AIC=-945.71   AICc=-945.44   BIC=-928.59</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Arima1)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2020</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Error1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-Error1-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figura&nbsp;3: Error + Intervención</figcaption>
</figure>
</div>
</div>
</div>
<p>Se observan dos valores claramente extremos en marzo de 2005 y mayo de 2013. Al estimar un nuevo modelo incluyendo estas dos intervenciones, el análisis del error revela una nueva intervención en abril de 2006, por lo que vamos a aprovechar para incluirla ya.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>d0305 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(Pernoctacionesb) <span class="sc">==</span> <span class="dv">3</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(Pernoctacionesb)) <span class="sc">==</span> <span class="dv">2005</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>d0406 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(Pernoctacionesb) <span class="sc">==</span> <span class="dv">4</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(Pernoctacionesb)) <span class="sc">==</span> <span class="dv">2006</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>d0513 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">cycle</span>(Pernoctacionesb) <span class="sc">==</span> <span class="dv">5</span> <span class="sc">&amp;</span> <span class="fu">trunc</span>(<span class="fu">time</span>(Pernoctacionesb)) <span class="sc">==</span> <span class="dv">2013</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>Arima2 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Pernoctacionesb, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),  </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                         <span class="at">xreg =</span> <span class="fu">cbind</span>(DiasMes, SemanaSanta, d0305, d0406, d0513))</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>Arima2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: Pernoctacionesb 
Regression with ARIMA(0,1,1)(0,1,1)[12] errors 
Box Cox transformation: lambda= 0 

Coefficients:
          ma1     sma1  DiasMes  SemanaSanta    d0305   d0406   d0513
      -0.3304  -0.3770   0.0279       0.0556  -0.0616  0.0371  0.0503
s.e.   0.0661   0.0767   0.0090       0.0073   0.0210  0.0197  0.0192

sigma^2 = 0.0008388:  log likelihood = 486.48
AIC=-956.96   AICc=-956.3   BIC=-929.56</code></pre>
</div>
</div>
<p>La <a href="#fig-Error2">Figura&nbsp;4</a> indica que aún hay candidatos a valores atípicos. Como ninguno alcanza las tres desviaciones típicas, vamos a dar por concluido este proceso.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Arima2)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sderror <span class="ot">&lt;-</span> <span class="fu">sd</span>(error)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(error, <span class="at">series=</span><span class="st">"Error"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)<span class="sc">*</span>sderror, </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"green"</span>, <span class="st">"red"</span>), </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2020</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Error2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-Error2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figura&nbsp;4: Error + Intervención</figcaption>
</figure>
</div>
</div>
</div>
<p>Por último, veamos si efectivamente todos los coeficientes del modelo son significativos.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(Arima2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
z test of coefficients:

              Estimate Std. Error z value            Pr(&gt;|z|)    
ma1         -0.3303816  0.0660871 -4.9992 0.00000057574208836 ***
sma1        -0.3770336  0.0767203 -4.9144 0.00000089057446340 ***
DiasMes      0.0278712  0.0090465  3.0809            0.002064 ** 
SemanaSanta  0.0555809  0.0072613  7.6544 0.00000000000001943 ***
d0305       -0.0616243  0.0210342 -2.9297            0.003393 ** 
d0406        0.0371492  0.0196842  1.8873            0.059125 .  
d0513        0.0503104  0.0192104  2.6189            0.008821 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Para un nivel de significatividad del 5% todos los coeficientes del modelo son significativos, excepto el de abril de 2006. Sin embargo, dejaremos esta variable ficticia por ser significativa al 10% y estar asociada a un error notoriamente elevado.</p>
<p><br>
<br>
</p>
</section>
<section id="validación" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Validación</h1>
<p>Analizando los criterios de bondad de ajuste se tiene que: el error medio (ME), igual a -10132.57 pernoctaciones, es prácticamente cero (en relación a los valores de la serie) por lo que no parece que haya sesgo en las predicciones; en media nos equivocamos en 606 mil pernoctaciones (RMSE); y el error porcentual medio es 2.2%, muy bajo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(Arima2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                    ME   RMSE      MAE   MPE MAPE MASE ACF1
Training set -10132.57 606418 443952.6 -0.04 2.19 0.49    0</code></pre>
</div>
</div>
<p><br>
<br>
</p>
</section>
<section id="ecuación-del-modelo-identificado" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Ecuación del modelo identificado</h1>
<p>Ahora que ya hemos dado por válido el modelo, veamos cuál es su ecuación.</p>
<p>El <strong>modelo teórico</strong> es <span class="math display">\[(1-L)(1-L^{12})log(Pernoctaciones_t) =(1+\theta_1 L)(1 + \theta_{12}L^{12})\varepsilon_t +\]</span> <span class="math display">\[\gamma_1 DiasMes + \gamma_2 SemanaSanta + \gamma_3 d0305  + \gamma_4 d0406 + \gamma_5 d0513.\]</span></p>
<p>Si se desarrolla el modelo y se deja en función de la tasa de variación anual del número de pernoctaciones, queda (la parte de intervención no cambia):</p>
<p><span class="math display">\[TVA_{Pernoctaciones_t} = TVA_{Pernoctaciones_{t-1}}  + \theta_1 \varepsilon_{t-1} + \theta_{12} \varepsilon_{t-12}+ \theta_1 \theta_{12} \varepsilon_{t-13}+\varepsilon_t + AI.\]</span></p>
<p>Finalmente, el modelo estimado es: <span class="math display">\[\widehat{TVA}_{Pernoctaciones_t} = TVA_{Pernoctaciones_{t-1}} - 0.33\varepsilon_{t-1} - 0.38 \varepsilon_{t-12} + 0.12 \varepsilon_{t-13} + \]</span> <span class="math display">\[0.028 \cdot DiasMes + 0.056 \cdot SemanaSanta - 0.062 \cdot  d0305  + 0.037 \cdot d0406 + 0.050 \cdot d0513.\]</span></p>
<ul>
<li><p>La tasa de variación anual de las pernoctaciones de un año es la misma que la del año pasado. Es decir, las pernoctaciones evolucionan a tasa constante.</p></li>
<li><p>Si en periodos previos se ha producido un shock, hay que tenerlo en cuenta en las predicciones.</p></li>
<li><p>Cada día del mes adicional las pernoctaciones aumentan un 2.8%. De otra forma, cada día del mes la tasa de variación anual de las pernoctaciones aumenta 2.8 puntos porcentuales.</p></li>
<li><p>En el mes en que cae la Semana Santa las pernoctaciones aumentan un 5.6% (la tasa variación anual de las pernoctaciones aumenta 5.6 puntos porcentuales).</p></li>
<li><p>En marzo de 2005 las pernoctaciones fueron significativamente menores de la esperado (6.2%).</p></li>
<li><p>En abril de 2006 y mayo de 2013 las pernoctaciones fueron significativamente mayor de la esperado (3.7% y 5%, respectivamente).</p></li>
</ul>
<p><br>
<br>
</p>
</section>
<section id="predicción-de-las-pernoctaciones" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Predicción de las pernoctaciones</h1>
<p>Una vez dado por válido el modelo, podemos pasar a realizar predicciones para los próximos años. Para días del mes generaremos para el periodo de previsión su correspondiente variable de intervención; para Semana Santa usaremos en las predicciones la variable antes generada; y para el resto de la intervención fijaremos sus valores previstos a cero.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">36</span>), <span class="at">start =</span> <span class="dv">2020</span>, <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>pDiasMes <span class="ot">&lt;-</span> <span class="fu">monthdays</span>(tmp)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>pArima2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(Arima2, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">h =</span> <span class="dv">36</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">xreg =</span> <span class="fu">cbind</span>(pDiasMes, pSemanaSanta, </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">36</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">36</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">36</span>)), </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">level =</span> <span class="dv">95</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pArima2, </span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Pernoctaciones"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2022</span>, <span class="dv">2</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Prevision" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-Prevision-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figura&nbsp;5: Pernoctaciones y predicciones</figcaption>
</figure>
</div>
</div>
</div>
<p>A partir de las predicciones podemos evaluar el efecto que la pandemia de la Covid-19 tuvo sobre las pernoctaciones.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Pernoctaciones <span class="sc">-</span> pArima2<span class="sc">$</span>mean, <span class="at">FUN =</span> sum) <span class="sc">/</span> <span class="dv">1000000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time Series:
Start = 2020 
End = 2022 
Frequency = 1 
[1] -245.15718 -195.30848  -42.38915</code></pre>
</div>
</div>
<p>En 2020 la caída estimada de las pernoctaciones fue de 245 millones y en 2021 de 195 millones. El efecto de la pandemia casi había desaparecido en el año 2022, con una caída de las pernoctaciones respecto de los valores previstos de 42 millones.</p>
<p><br>
<br>
</p>
</section>
<section id="comparación-con-otros-modelos" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Comparación con otros modelos</h1>
<section id="calidad-de-ajuste" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="calidad-de-ajuste"><span class="header-section-number">7.1</span> Calidad de ajuste</h2>
<p>La serie Pernoctaciones la hemos ajustado por el método ingenuo con estacionalidad, el método de Alisado Exponencial y procesos ARIMA. La <a href="#tbl-calidad">Tabla&nbsp;1</a> recoge el error medio (RMSE) y porcentual (MAPE) al usar estas tres aproximaciones con la serie original y su transformación logarítmica.</p>
<div id="tbl-calidad" class="anchored">
<table class="table">
<caption>Tabla&nbsp;1: Criterios de calidad para previsiones intramuestrales a un periodo vista. Varios modelos</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Serie</th>
<th style="text-align: left;">Método</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAPE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pernoctaciones</td>
<td style="text-align: left;">Ingenuo</td>
<td style="text-align: right;">1243441</td>
<td style="text-align: right;">4.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Pernoctaciones)</td>
<td style="text-align: left;">Ingenuo</td>
<td style="text-align: right;">1243441</td>
<td style="text-align: right;">4.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pernoctaciones</td>
<td style="text-align: left;">Alisado</td>
<td style="text-align: right;">727645</td>
<td style="text-align: right;">2.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Pernoctaciones)</td>
<td style="text-align: left;">Alisado</td>
<td style="text-align: right;">738036</td>
<td style="text-align: right;">2.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pernoctaciones</td>
<td style="text-align: left;">ARIMA</td>
<td style="text-align: right;">620624</td>
<td style="text-align: right;">2.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Pernoctaciones)</td>
<td style="text-align: left;">ARIMA</td>
<td style="text-align: right;">606418</td>
<td style="text-align: right;">2.19</td>
</tr>
</tbody>
</table>
</div>
<p>Podemos extraer varias conclusiones: i) la transformación logarítmica no mejora necesariamente el ajuste de los datos; ii) el proceso ARIMA con transformación logarítmica es el modelo con mejor ajuste; y iii) el método de alisado muestra una calidad de ajuste comparable a la de los procesos ARIMA. La ligera mejora en el ajuste de los modelos ARIMA respecto del método de Alisado se debe a la incorporación de variables ficticias para recoger la intervención.</p>
</section>
<section id="predicciones-extramuestrales" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="predicciones-extramuestrales"><span class="header-section-number">7.2</span> Predicciones extramuestrales</h2>
<p>Vamos a determinar si también la aplicación de modelos ARIMA mejora la calidad de las predicciones extra-muestrales lo suficiente como para justificar su uso –frente a los métodos de alisado, mucho más sencillos. Para ello, aplicaremos la metodología de origen de predicción móvil para estimar la capacidad predictiva del modelo ARIMA y compararla con el modelo de Alisado y el ingenuo con estacionalidad.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">120</span>                   </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">12</span>                    </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">length</span>(Pernoctacionesb)     </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> T <span class="sc">-</span> k <span class="sc">-</span> h               </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>mapeIngenuo <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>mapeAlisado <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>mapeAlisadoLog <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>mapeArimaLog <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, s <span class="sc">+</span> <span class="dv">1</span>, h)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(DiasMes, SemanaSanta, d0305, d0406, d0513))</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>s) {</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  train.set <span class="ot">&lt;-</span> <span class="fu">subset</span>(Pernoctacionesb, <span class="at">start =</span> i <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  test.set <span class="ot">&lt;-</span>  <span class="fu">subset</span>(Pernoctacionesb, <span class="at">start =</span> i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">end =</span> i <span class="sc">+</span> k <span class="sc">+</span> h) </span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k),])</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>  hay <span class="ot">&lt;-</span> <span class="fu">colSums</span>(X.train)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>  X.train <span class="ot">&lt;-</span> X.train[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(X[(i <span class="sc">+</span> k <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">+</span> k <span class="sc">+</span> h),])</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>  X.test <span class="ot">&lt;-</span> X.test[, hay<span class="sc">&gt;</span><span class="dv">0</span>]</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Ingenuo</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">snaive</span>(train.set, <span class="at">h =</span> h)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>  mapeIngenuo[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fit<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Alisado sin log</span></span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">ets</span>(train.set, <span class="at">model =</span> <span class="st">"MNM"</span>)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h) </span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>  mapeAlisado[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Alisado con log</span></span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">ets</span>(train.set, <span class="at">model =</span> <span class="st">"ANA"</span>, <span class="at">lambda =</span> <span class="dv">0</span>)</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>  fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h) </span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>  mapeAlisadoLog[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a>  <span class="co">#ARIMA sin log</span></span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a>                   <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a>                   <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.train)), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.element</span>(<span class="st">"try-error"</span>, <span class="fu">class</span>(fit))) {</span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a>    fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test))</span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a>    mapeArima[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a>  <span class="co">#ARIMA con log</span></span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">Arima</span>(train.set, </span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a>                   <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb29-54"><a href="#cb29-54" aria-hidden="true" tabindex="-1"></a>                   <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb29-55"><a href="#cb29-55" aria-hidden="true" tabindex="-1"></a>                   <span class="at">lambda =</span> <span class="dv">0</span>,</span>
<span id="cb29-56"><a href="#cb29-56" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.train)), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-57"><a href="#cb29-57" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-58"><a href="#cb29-58" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.element</span>(<span class="st">"try-error"</span>, <span class="fu">class</span>(fit))) {</span>
<span id="cb29-59"><a href="#cb29-59" aria-hidden="true" tabindex="-1"></a>    fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> h, <span class="at">xreg =</span> <span class="fu">as.matrix</span>(X.test)) </span>
<span id="cb29-60"><a href="#cb29-60" aria-hidden="true" tabindex="-1"></a>    mapeArimaLog[i <span class="sc">+</span> <span class="dv">1</span>,] <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">abs</span>(test.set <span class="sc">-</span> fcast<span class="sc">$</span>mean)<span class="sc">/</span>test.set</span>
<span id="cb29-61"><a href="#cb29-61" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-62"><a href="#cb29-62" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-63"><a href="#cb29-63" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-64"><a href="#cb29-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-65"><a href="#cb29-65" aria-hidden="true" tabindex="-1"></a>mapeIngenuo <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeIngenuo)</span>
<span id="cb29-66"><a href="#cb29-66" aria-hidden="true" tabindex="-1"></a>mapeAlisado <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeAlisado)</span>
<span id="cb29-67"><a href="#cb29-67" aria-hidden="true" tabindex="-1"></a>mapeAlisadoLog <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeAlisadoLog)</span>
<span id="cb29-68"><a href="#cb29-68" aria-hidden="true" tabindex="-1"></a>mapeArima <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArima, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-69"><a href="#cb29-69" aria-hidden="true" tabindex="-1"></a>mapeArimaLog <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(mapeArimaLog, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> mapeIngenuo, <span class="at">colour =</span> <span class="st">"Ingenuo"</span>)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> mapeAlisado, <span class="at">colour =</span> <span class="st">"Alisado"</span>)) <span class="sc">+</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> mapeAlisadoLog, <span class="at">colour =</span> <span class="st">"Alisado (log)"</span>)) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> mapeArima, <span class="at">colour =</span> <span class="st">"Arima"</span>)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">y =</span> mapeArimaLog, <span class="at">colour =</span> <span class="st">"Arima (log)"</span>)) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"MAPE"</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Modelos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-PrevisionRW" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-13-Ejemplo7_files/figure-html/fig-PrevisionRW-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figura&nbsp;6: Errores de previsión extra-muestral. Varios modelos</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-PrevisionRW">Figura&nbsp;6</a> revela que ARIMA con transformación logarítmica es siempre superior a Alisado en calidad de predicciones.</p>
<p>También se observa que la transformación logarítmica no afecta significativamente la calidad de las predicciones en los modelos de Alisado, pero es muy determinante en los procesos ARIMA.</p>
<p>Como ya vimos, el error con el método ingenuo parece independiente del horizonte temporal. A corto plazo es la peor aproximación, pero a largo plazo es tan bueno como el resto de métodos.</p>
<p><br>
<br>
<br>
<br>
</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2023, Iván Arribas. If you find any bugs please report them to <a href="mailto:ivan.arribas@uv.es">ivan.arribas@uv.es</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>